### ISSUE TITLE
Cleaning the servers table when stopped

### ISSUE THREAD

**Issue by brblord** [jupyterhub/dockerspawner#104]
If remove_containers is set, should the spawner remove the entry in the 'servers' table?  This table seems to grow quite large if servers are culled and restarted as the port changes, and with swarmspawner the IP may change as well.

**Comment by minrk** [comment]
It shouldn't be up to the spawner to do that, and it shouldn't actually matter whether containers are removed or not. The Hub should be responsible for deleting Server entries when they stop.

**Comment by brblord** [comment]
Thank you for the clarification.  I wasn't sure if the entries may be used for optimizing a start from a "soft" stop or other non-docker scenarios.  Is this cleanup planned to be added to the Hub, or should I open a ticket in that repo?

**Comment by minrk** [comment]
It's fine here. Should be fixed by jupyterhub/jupyterhub#634

**Comment by brblord** [comment]
Beautiful!  Thank you for all of the help!
