### ISSUE TITLE
perhaps migrate duplicated code to jupyter/docker-stacks and add support for systemuser

### ISSUE THREAD

**Issue by steverweber** [jupyterhub/dockerspawner#105]
perhaps migrate duplicated code to jupyter/docker-stacks
so things stay in sync.

https://github.com/jupyter/docker-stacks/issues/242

also would be nice if more advanced jupyter/docker-stacks had support for `systemuser`

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months and the docker-stacks and this spawner have evolved since then. If you still have a specific enhancement request, please file a new detailed issue. Thanks! :sunflower:
