### ISSUE TITLE
c.DockerSpawner.extra_host_config passes only network_mode to docker

### ISSUE THREAD

**Issue by matteoipri** [jupyterhub/dockerspawner#107]
Hi all,
I'm using DockerSpawner in a Docker Swarm setup.
I was able to set the docker overlay network but I can not set the memory limit for the notebook containers.
```python
# Additional args to create_host_config for container create
c.DockerSpawner.extra_host_config = {
    'mem_limit': '300m',
    'memswap_limit': '0b',
    'network_mode': 'nw-docker',
    'oom_kill_disable': False
}
```
This is the sample from my `jupyterhub_config.py` file. Only the `network_mode` setting is recognized by docker. I checked this by running `docker inspect` on a running notebook container.

How can we fix this?

Thanks

**Comment by willingc** [comment]
Hi @matteoipri,

Memory limits will be available using the systemdspawner:
https://github.com/jupyterhub/systemdspawner/blob/master/systemdspawner/systemdspawner.py#L13

Closing this issue as resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks. :sunny:

**Comment by matteoipri** [comment]
Hi @willingc I forgot I opened this issue!
I found a solution to the problem and reported it in the gitter.im chat. Maybe this was not the smartest move to spread the result...
Anyway, here is the solution I found:
I removed the `c.DockerSpawner.extra_start_kwargs` and `c.DockerSpawner.extra_create_kwargs` and put all my needed configurations in the `extra_host_config` dictionary as follows:
```
c.DockerSpawner.extra_host_config = {
    'network_mode': 'nw-docker',
    'mem_limit': '300m',
    'memswap_limit': '300m',
    'mem_swappiness': 0
}
```
now `docker inspect juyter-user` says the limits are in place and if a user runs code that eats too much memory her/his kernel is killed!

I add that in order to keep the host running smoothly I had to also set a limit on the number of containers run on each compute node where the user containers are spawned.
I added the following options to the kernel: `cgroup_enable=memory swapaccount=1`. Since I was running Ubuntu Server with GRUB, I set this option with the following command:
```
sudo tee -a /etc/default/grub <<< "GRUB_CMDLINE_LINUX=\"cgroup_enable=memory swapaccount=1\""
```
Moreover, I added `--label containerslots=N` to the options passed to the docker daemon, where N is the maximum number of users supported on each node. For example, with 8GB of RAM, 300MB allowed per user, we get that we can let up to 26 users run on that node. I set N=27 since the `swarm-agent` container needed for the Docker Swarm uses one of the slots.

It appears to me that when DockerSpawner spawns a container, only the `extra_host_config` dictionary gets used properly, even if its documentation and `docker-py`'s documentation say that different options should go in different dictionaries. I don't remember exactly where I found these inconsistencies, but I will report them if I will find them again.

So now we can say that we have memory limits available via `systemdspawner` locally and via `DockerSpawner` remotely! :-)

**Comment by willingc** [comment]
Super @matteoipri! Thanks for the detailed response :cake:

I'm going to label this a 'reference' since it will likely help someone else too.

**Comment by ZelphirKaltstahl** [comment]
To me it is not clear, if the line in `/etc/default/grub` has to be added for `DockerSpawner` to pick up the config parameters about memory and swap memory.
Can someone please clarify which of the steps @matteoipri described are necessary in which setup (DockerSpawner and normal Spawner used by JupyterHub)?

At the moment I see the opposite, with a configuration of:

    c.DockerSpawner.extra_host_config = {
        'network_mode': network_name,
        'cpuset_cpus': '0-3',
        'mem_limit': '1024m',
        'memswap_limit': '2048m'
    }

`DockerSpawner` does not set a swap limit. It does not appear in `docker inspect container-name`. Instead I see `-1` there for memory swap limit.

Also: Does the cgroup `memory` usually already exist on a Ubuntu machine? Or was it created and configured elsewhere, before running the containers the way described?

**Comment by akoripelly** [comment]
Hi
I am hoping someone to help with the config settings to run the spawner with network=host configuration.  I am unable to get this to work with jupyterhub.  However when I container using docker run command and --host network, the docker container runs with host networking.

I am basically looking for the configuration settings so that the dockerSpawner container in host network mode.

**jupyterhub_config.py settings**
from dockerspawner import DockerSpawner
c.DockerSpawner.image = 'jupyter/quad001'
c.JupyterHub.spawner_class = DockerSpawner
import netifaces
docker0 = netifaces.ifaddresses('docker0')
docker0_ipv4 = docker0[netifaces.AF_INET][0]
c.JupyterHub.hub_ip = docker0_ipv4['addr']
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = 'host'
c.DockerSpawner.extra_host_config = {'network_mode': 'host'}

Thank you for your help
