### ISSUE TITLE
Multiple Node Environment for Jupyterhub

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyterhub/dockerspawner#108]
I am having two hosts over which I am planning to build up an environment with Jupyterhub running on 2 nodes. Out of this, one node will be a docker server and the other to be base jupyerhub server. The main idea behind configuring this, is to establish a load balancing mechanism as well as clustering. Based on average load on the server, the user will be routed to a dedicated host for routing.

Can you please guide me on this configuration.

Is this on one host, I shall be configuring docker spawner and on the other node normal Jupyerhub server. If so how the configuration will be define. Also do I need to define Clustering at Unix OS level also?

Please suggest on this.

Regards,
Sudipta.

**Comment by willingc** [comment]
Hi @sudipto84goswami,

Sorry for the delay in responding. Perhaps the best approach would be to look at using Docker Swarm as described [here](https://github.com/jupyterhub/dockerspawner#using-docker-swarm).

Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
