### ISSUE TITLE
Stop / Delete container on use logout / inactivy

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/dockerspawner#113]
After reading the documentation and doing all possible config, after a user is logged out, or a socket not active anymore, the container is still running. How can I make it to be stopped/delete automatically?

**Comment by jhamrick** [comment]
You can use an external service to do this. For an example, check out the culling service I use for my class: https://github.com/compmodels/cull

The above dockerfile basically just wraps the example culling script from the JupyterHub repo: https://github.com/jupyterhub/jupyterhub/tree/master/examples/cull-idle

**Comment by katsar0v** [comment]
Thank you!
