### ISSUE TITLE
Review new Docker release for orchestration/swarm for usefulness in dockerspawner

### ISSUE THREAD

**Issue by willingc** [jupyterhub/dockerspawner#117]
Moved from https://github.com/jupyterhub/jupyterhub/issues/615

The intro of Docker 1.12 adds:

docker swarm init
docker swarm join

It handles sensible defaults for security by default.

We should investigate how this may simplify dockerspawner.

**Comment by rgbkrk** [comment]
Cool, I was wondering this too!

**Comment by manics** [comment]
I've only just noticed this issue, I did some work on getting `DockerSpawner` to run as a service under Docker Swarm: https://github.com/manics/dockerspawner

The main changes required were that docker 1.12 requires containers in a swarm to be run as services using `create_service`. However I've now seen https://github.com/docker/docker/pull/25962 which would allow non-service containers to be run on an overlay network in 1.13, so these changes may be moot.

**Comment by sshillo** [comment]
@manics creating the a service has the benefit of being able to go to another node, while just running a container could only run on the same node if I understand everything correctly

**Comment by manics** [comment]
@sshillo At the moment (Docker 1.12), yes, that's correct. My understanding of https://github.com/docker/docker/pull/25962 (Docker 1.13) is that it extends the scheduling capabilities of Docker swarm mode from services to normal containers started with `docker run` as usual.

**Comment by barrachri** [comment]
@sshillo one of the main benefit is also that if you put down a node the service will be recreated on another node.

I think that the concept of replica is not important for a jupyter server.

It's not the same with containers ( tested with version Docker 1.12.6).

Related to this PR (https://github.com/docker/docker/pull/25962):
-  containers connected to the same network across the cluster can discover and connect to each other.
- Get access to services(and their associated loadbalancers) connected to the same network

So it just extends the cluster network to normal containers.

Another think that we should probably face to use Swarm (apart from using the Service API) is using the service name instead of the ip in the hub.

**Comment by Wildcarde** [comment]
Would it be possible to add a clarification to the documentation for swarm support to indicate it's not currently talking about the 1.12/1.13 built in functionality? I can't be the only one that's gotten it all working on a single node only to discover the built swarm version isn't supported for dialing out to multiple nodes after.

**Comment by ddcamiu** [comment]
+1 for @Wildcarde . Before adapting the codes to 1.12/1.13, it is appreciated to at least clarify that in the documentation. It would better to attach the documentation of how to deploy the old but working version of Swarm.

**Comment by minrk** [comment]
I finally got around to testing JupyterHub with the latest docker swarm (17.03.0) using docker-machine. I can confirm the the current stable version of DockerSpawner does indeed work with swarm, as long as two criteria are met in the configuration:

1. the containers can connect to the Hub
2. the Hub can connect to the containers

If the Hub is itself in a container, then the best way to accomplish this is with an overlay network. If the Hub is outside the swarm, then only two lines of configuration are needed:

```python
c.DockerSpawner.container_ip = '0.0.0.0' # listen on all ips
c.JupyterHub.hub_ip = 'a.b.c.d'
```

where `a.b.c.d` is an ip address of the hub that the swarm nodes can connect to. This could be retrieved from `eth0` with `netifaces`, for instance, or specified manually.

My notes are [here](https://github.com/minrk/jupyterhub-swarm).

**Comment by manics** [comment]
@minrk
> I can confirm the the current stable version of DockerSpawner does indeed work with swarm, as long as two criteria are met in the configuration

Did you mean can work with a docker swarm overlay **network**? As far as I can tell the latest docker version let's you run containers on one node and connect to a swarm overlay network, but it doesn't automatically distribute the running of containers across multiple nodes in the network (which is what I originally thought https://github.com/docker/docker/pull/25962 was for).

Do you want me to revisit my attempt at getting JupyterHub to work as a docker service https://github.com/jupyterhub/dockerspawner/compare/master...manics:master with the aim of opening a PR here?

**Comment by minrk** [comment]
@manics I mean the current stable release of DockerSpawner, unmodified, works with docker swarm, distributing servers across nodes. A docker overlay network is used to ensure that the Hub and servers can talk to each other. I do not use services anywhere. I'm not quite sure what using services here would solve, since it works on swarm with containers just fine.

**Comment by manics** [comment]
@minrk Sorry for the delay in responding, been busy.

I've followed your instructions from https://github.com/minrk/jupyterhub-swarm and got it running with `hub-outside`. However it looks like `docker-machine` creates a [legacy swarm](https://docs.docker.com/swarm/provision-with-machine/) instead of the built-in swam. This is pretty unclear in the Docker Machine docs. After setting up JupyterHub with your instructions:

```
$ eval "$(docker-machine env rogue-leader)"
$ docker info |grep Swarm
Swarm: inactive
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
093f926905fd        swarm:latest        "/swarm join --adv..."   2 hours ago         Up 2 hours          2375/tcp                           swarm-agent
ffc9493fe2da        swarm:latest        "/swarm manage --t..."   2 hours ago         Up 2 hours          2375/tcp, 0.0.0.0:3376->3376/tcp   swarm-agent-master
```
```
$ eval "$(docker-machine env rogue-one)"
$ docker info |grep Swarm
Swarm: inactive
$ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                     NAMES
d5d09c084796        jupyterhub/singleuser   "tini -- sh /srv/s..."   15 minutes ago      Up 15 minutes       0.0.0.0:32768->8888/tcp   jupyter-test-1
3d89bb5243d7        swarm:latest            "/swarm join --adv..."   2 hours ago         Up 2 hours          2375/tcp                  swarm-agent
```
```
$ eval "$(docker-machine env rogue-two)"
$ docker info |grep Swarm
Swarm: inactive
$ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                     NAMES
44e25b56c96c        jupyterhub/singleuser   "tini -- sh /srv/s..."   15 minutes ago      Up 15 minutes       0.0.0.0:32768->8888/tcp   jupyter-test-2
56bb29e31815        swarm:latest            "/swarm join --adv..."   2 hours ago         Up 2 hours          2375/tcp                  swarm-agent
```

This is what I'd expect if the server was running with the built-in swarm:
```
$ docker info | grep Swarm
Swarm: inactive

$ docker swarm init
Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on different interfaces (10.0.2.15 on eth0 and 192.168.99.104 on eth1) - specify one with --advertise-addr

$ docker swarm init --advertise-addr 192.168.99.104
Swarm initialized: current node (ujnhuylozecn0tdq3d35tv4uo) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-3b28j1cfvixqlufmyyey5raax22vpcgwdiot45l51smopibjln-69juv7e9nk3cklrupdfi5tywd \
    192.168.99.104:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

$ docker info | grep Swarm
Swarm: active

$ docker service ls
ID  NAME  MODE  REPLICAS  IMAGE
```

**Comment by barrachri** [comment]
The api call (https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L428) is different from what you need with Docker Engine in Swarm Mode (https://docker-py.readthedocs.io/en/stable/api.html#docker.api.service.ServiceApiMixin.create_service).

**Comment by brianz3** [comment]
@manics @minrk I have been testing Jupyterhub in the new docker swarm mode. I can confirm Jupyterhub is always creating the new jupyter notebook containers on the same host/node where the Jupyterhub container is located. It has not placed them on any other node.

It appears that will will need something like @minrk's DockerServiceSpawner class.

I tried to use the draft docker server spawner in github.com/manics/dockerspawner. It appears to successfully create the service, but was unable to retrieve the services IP address. This is the error message: 

"JupyterHub dockerservicespawner:202] Failed to get IP for Service 'jupyter-username' after 120 s"

**Comment by barrachri** [comment]
@brianz3 have you tried https://github.com/cassinyio/SwarmSpawner?

**Comment by manics** [comment]
@brianz3 Did the notebook image already exist on the server? I've noticed some timeouts with `DockerServiceSpawner` when the image has to be pulled. After manually removing the service (`docker service rm jupyter-username`) and reconnecting to the jupyterhub web interface the service was correctly recreated, I haven't had time to investigate the cause.

@barrachri I wasn't aware of https://github.com/cassinyio/SwarmSpawner. Thanks for sharing it- have you used it heavily in production?

**Comment by barrachri** [comment]
Hi @manics, would be nice to use it heavily in production, for now is the spawner used by cassiny.
Feedback and PRs are welcome :)

**Comment by minrk** [comment]
I'm going to call this addressed, now that there's a SwarmSpawner in this repo
