### ISSUE TITLE
Pull images

### ISSUE THREAD

**Issue by mausch** [jupyterhub/dockerspawner#121]
While trying out jupyterhub + dockerspawner I found this rather surprising behaviour: it doesn't pull images automatically. Is there a reason for this or is it just something that's not implemented yet?
See https://github.com/jupyterhub/jupyterhub/issues/590 for some context.
Thanks!

**Comment by carolynvs** [comment]
I don't think that's been implemented. When I wrote the jupyterhub-carina plugin, I had to add that myself.

https://github.com/jupyterhub/jupyterhub-carina/blob/master/jupyterhub_carina/CarinaSpawner.py#L150

**Comment by rgbkrk** [comment]
PR certainly welcome for pulling images on the DockerSpawner. Some things to consider:

* Should it pull on every launch?
* How often should it pull if not on every launch?
* How much configuration do you want to have maintain vs. delegating to a subclassed spawner?

**Comment by barrachri** [comment]
Hello,

I was looking inside this.

The problem is when you have to pull images of x GB.

I think that the docker-py is a blocking api, so we should try to handle this in an async way.

There is also some logic to handle cause the way in which the Docker Engine works.

For example in case of pulling images that already exist.

**Comment by minrk** [comment]
@barrachri we already make docker 'async' by putting all docker calls into a background thread, so it doesn't block the main application. It would still block other *docker* operations, but not the whole application.

**Comment by CRegenschein** [comment]
In our setup, we are also using this great selection for images here: https://github.com/ryanlovett/imagespawner

Believe it or not, we also have R users :-)

I think it would be good if we could somehow anticipate that there might be more than one docker image to be pulled / updated.
