### ISSUE TITLE
Default folder recreates with root owner

### ISSUE THREAD

**Issue by egorlitvinenko** [jupyterhub/dockerspawner#127]
JupyterHub 0.6.1 is installing on Ubuntu 14.04, using DockerSpawner, custom Authenticator.
Authentication technic: Jupyter opens from another application with temporal code, LoginHandler get code from URL, connects to common application and check code, if success, user authorization is success, so no login form provides.

jupyterhub_configuration.py:

```
# Configuration file for jupyterhub.
c.JupyterHub.admin_access = True
c.JupyterHub.authenticator_class = 'MyAuthenticator'

c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
import os
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir
c.DockerSpawner.volumes = { '/home/me/volumes/{username}': notebook_dir }
c.DockerSpawner.extra_host_config = {'network_mode': 'host'}
c.DockerSpawner.http_timeout = 90
c.DockerSpawner.debug = True

from jupyter_client.localinterfaces import public_ips
print(public_ips())
first_ip = public_ips()[0]
c.JupyterHub.hub_ip = first_ip
c.DockerSpawner.hub_ip_connect = first_ip

```

A problem is '/home/jovyan/work' folder belongs to root when new Spawner server created.
If I setting another folder, for example, '/notebooks', then '/notebooks' folder will be under root owner, but '/home/jovyan/work' will owned by jovyan. So it looks like folder automatically recreates by root user.
As a result I can't create any notebooks or files because of insufficient privileges and result is 'permission denied' error.

**Comment by minrk** [comment]
I think docker volumes need to exist before mounting them to avoid having them owned by root. I'm not sure the best way to do that.

**Comment by egorlitvinenko** [comment]
Maybe, unfortunately vagrant doesn't up after I halt them, I will try this, when restore environment.

**Comment by myurasov** [comment]
+1

If you're using some external auth, you don't know what volumes need to exist.

**Comment by wwj718** [comment]
@myurasov +1

**Comment by wwj718** [comment]
@all I have a idea ，when the  folder create ，we use [watchdog](https://github.com/gorakhargosh/watchdog) to change the dir mode (chmod)

**Comment by myurasov** [comment]
I ended up with passing custom function to `format_volume_name` option and creating folder with correct permissions there. Which is not too elegant...

**Comment by pgeez** [comment]
@myurasov can you please post your code? thanks!

**Comment by myurasov** [comment]
@pgeez, something like that:

```python
import os
import shutil

def format_volume_name(label_template, spawner):
    path = label_template.format(username=spawner.escaped_name)

    # creates user notebooks dir
    if not os.path.isdir(path):
        os.makedirs(path)
        shutil.chown(path, user='ubuntu', group='ubuntu')
        os.chmod(path, 0o755)

    return path
```

then in `jupyterhub_config.py`:

```python
c.DockerSpawner.format_volume_name = format_volume_name
```
