### ISSUE TITLE
JupyterHub with Docker Spawner and Docker Swarm

### ISSUE THREAD

**Issue by henring** [jupyterhub/dockerspawner#129]
Hello,

So I'm trying to run JupyterHub using Docker Spawner and Docker Swarm and running it locally. I'm following your workshop tutorial here : [dockerspawner](https://github.com/jupyterhub/dockerspawner/pull/54). I want to run it locally without using carina, in order to deploy laterly to other cloud services using Docker Swarm. So I started my own Docker Swarm as it explained here : [dockerswarm](https://docs.docker.com/swarm/install-w-machine/).

Based own your explanation, I've got this configuration files:

- launch.sh
```
#!/bin/sh
set -euo pipefail

export DNSNAME=localhost
export JUPYTERHUB_USERS=myself
export JUPYTERHUB_ADMINS=myself

export OAUTH_CLIENT_ID=<my_oauth_client_id>
export OAUTH_CLIENT_SECRET=<my_oauth_client_secret>
#export OAUTH_CALLBACK_URL=http://localhost:8000/hub/oauth_callback

docker build -t myjupyterhub .
#docker pull jupyterhub/singleuser

docker run --detach \
  --name jupyterhub \
  -p 80:8000 \
  -p 8081:8081 \
  -e DOCKER_CERT_PATH=${DOCKER_CERT_PATH} \
  -e JUPYTERHUB_USERS=${JUPYTERHUB_USERS} \
  -e JUPYTERHUB_ADMINS=${JUPYTERHUB_USERS} \
  -e DOCKER_HOST=https://${DOCKER_HOST#tcp://} \
  -e HUB_IP_CONNECT=${DNSNAME} \
  -e OAUTH_CALLBACK_URL=http://${DNSNAME}/hub/oauth_callback \
  -e OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID} \
  -e OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET} \
  myjupyterhub

open http://$(docker port jupyterhub 8000)
```

- jupyter_config.py
```
import os
import re

c = get_config()

c.JupyterHub.hub_ip = "0.0.0.0"

c.JupyterHub.spawner_class = "dockerspawner.DockerSpawner"
c.DockerSpawner.tls_verify = True
c.DockerSpawner.tls_ca = "/etc/docker/ca.pem"
c.DockerSpawner.tls_cert = "/etc/docker/server-cert.pem"
c.DockerSpawner.tls_key = "/etc/docker/server-key.pem"
c.DockerSpawner.container_ip = "0.0.0.0"
c.DockerSpawner.hub_ip_connect = os.environ["HUB_IP_CONNECT"]

c.JupyterHub.authenticator_class = "oauthenticator.GoogleOAuthenticator"

c.JupyterHub.login_url = "/hub/oauth_login"

def userlist(varname):
    """
    Intercept an environment variable as a whitespace-separated list of GitHub
    usernames.
    """

    parts = re.split("\s*,\s*", os.environ[varname])
    return set([part for part in parts if len(part) > 0])

c.Authenticator.whitelist = userlist("JUPYTERHUB_USERS")
c.Authenticator.admin_users = userlist("JUPYTERHUB_ADMINS")

c.GitHubOAuthenticator.oauth_callback_url = os.environ["OAUTH_CALLBACK_URL"]
c.GitHubOAuthenticator.client_id = os.environ["OAUTH_CLIENT_ID"]
c.GitHubOAuthenticator.client_secret = os.environ["OAUTH_CLIENT_SECRET"]
```

- Dockerfile
```
FROM jupyterhub/jupyterhub

RUN pip install --upgrade pip
RUN pip install dockerspawner oauthenticator
```

The container with the JupyterHub and DockerSpawner is created in the swarm, it launches the JupyterHub login page but with the System User authentification, and not the Google authentification sign up as I thought. So here come my questions.

I made the changes to try to make it works locally (without carina) like here [jupyterhub-tutorial](https://github.com/getcarina/jupyterhub-tutorial/tree/gh-pages/jupyterhub-launch). I don't see when the jupyter_config.py is called by JupyterHub. Do I have to add this file to the Dockerfile (and in the same way, the certificate and server key) ? So the created image is the container that launches the JupyterHub with DockerSpawner. 

Where do I have to call the image with the notebook I want to spawn by Docker Spawner ? I have already created another docker image with Jupyter and my notebook (the singleuser image).

**Comment by gsayer** [comment]
Anybody ?  I want to spawn by Docker Spawner on swarm without Carina. thk

**Comment by henring** [comment]
So, after long week of search, I'm little disappointed to have no found any examples or tutorials explaining how to simply deploy jupyterhub with dockerspawner in a docker swarm locally, without using any cloud solution like [Carina by Rackspace](https://getcarina.com/) with [jupiterhub-carina](https://github.com/jupyterhub/jupyterhub-carina) or [OpenStack](https://www.openstack.org/) with [Zonca tutorial](https://zonca.github.io/2016/05/jupyterhub-docker-swarm.html). Nevertheless, I've learned so much about Docker and JupyterHub, thanks respectively to the teams developing such great tools.

So here a combined solution with all jupyterhub projects, posts and help found:
* [docker-stacks](https://github.com/jupyter/docker-stacks)
* [jupyterhub-deploy-docker](https://github.com/jupyterhub/jupyterhub-deploy-docker)
* [compmodels](https://github.com/compmodels/jupyterhub-deploy)
* [dockerspawner in swarm deployment](https://github.com/jupyterhub/dockerspawner/issues/92)
* [dockerspawner error 500](https://github.com/jupyterhub/jupyterhub/issues/291)
* etc

So, to sum up what I've done until now:
1. Set up a discovery service (like Consul), create a cluster swarm, create an overlay network in the swarm and deploy the swarm as explained here: [Docker overlay-networking](https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/overlay-networking-with-an-external-key-value-store). It's a good start to understand how [Docker Swarm](https://docs.docker.com/swarm/install-w-machine/) and [Docker Network](https://docs.docker.com/engine/userguide/networking/) with [Swarm networking](https://docs.docker.com/swarm/networking/) work.
2. Dockerize JupterHub like in [jupyterhub-deploy-docker](https://github.com/jupyterhub/jupyterhub-deploy-docker).
3. Customize and dockerize the SingleUser container that I want to deploy with the notebooks inside.
4. Run the JupterHub container in the Docker Swarm.

Do not mix up the standalone [Docker Swarm](https://docs.docker.com/swarm/overview/) and the [Docker Engine Swarm mode](https://docs.docker.com/engine/swarm/). Dockerspawner runs with Docker Swarm (for the moment).

Use [Docker Compose](https://docs.docker.com/compose/overview/) to ease the build, run and deploy process.

You can generate your own SSL certificate and key here: [certificates-and-security](https://help.ubuntu.com/12.04/serverguide/certificates-and-security.html) or [openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs](https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs)

Here is my configuration:

* jupyterhub_config.py
```
c.JupyterHub.config_file = '/srv/jupyterhub/jupyterhub_config.py'
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8080
c.JupyterHub.port = 443

c.JupyterHub.ssl_cert = os.environ['SSL_CERT']
c.JupyterHub.ssl_key = os.environ['SSL_KEY']
c.JupyterHub.confirm_no_ssl = True

c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.container_image = os.environ['DOCKER_NOTEBOOK_IMAGE']
c.DockerSpawner.remove_containers = True
c.DockerSpawner.extra_create_kwargs.update({ 'command': os.environ['DOCKER_SPAWN_CMD'] })

network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.network_name = network_name
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.extra_host_config = { 'network_mode': network_name }
# Decapricated since Docker version 1.10
#c.DockerSpawner.extra_start_kwargs = { 'network_mode': network_name }
c.DockerSpawner.notebook_dir = os.environ['DOCKER_NOTEBOOK_DIR']
c.DockerSpawner.hub_ip_connect = 'jupyterhub'
c.DockerSpawner.container_ip = "0.0.0.0"

c.JupyterHub.authenticator_class = 'oauthenticator.GoogleOAuthenticator'
c.GoogleOAuthenticator.client_id = os.environ['OAUTH_CLIENT_ID']
c.GoogleOAuthenticator.client_secret = os.environ['OAUTH_CLIENT_SECRET']
c.GoogleOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']
#c.GoogleOAuthenticator.hosted_domain = os.environ['HOSTED_DOMAIN']

c.Spawner.tls_assert_hostname = False
c.DockerSpawner.tls_verify = True
c.DockerSpawner.tls_ca = os.environ['DOCKER_TLS_CA']
c.DockerSpawner.tls_cert = os.environ['DOCKER_TLS_CERT']
c.DockerSpawner.tls_key = os.environ['DOCKER_TLS_KEY']

c.Authenticator.admin_users = whitelist = set()
c.Authenticator.whitelist = admin = set()

join = os.path.join
here = os.path.dirname(__file__)
with open(join(here, 'userList')) as f:
    for line in f:
        if not line:
            continue
        parts = line.split()
        name = parts[0]
        whitelist.add(name)
        if len(parts) > 1 and parts[1] == 'admin':
            admin.add(name)
```

* .env

```
# Google OAuth
OAUTH_CLIENT_ID=<my_oauth_client_id>
OAUTH_CLIENT_SECRET=<my_oauth_client_secret>
OAUTH_CALLBACK_URL=<my_oauth_callback_url>

# Name of Docker machine
DOCKER_MACHINE_NAME=jupyterhub

# Name of Docker network
DOCKER_NETWORK_NAME=jupyterhub-network

# Docker notebook image
DOCKER_NOTEBOOK_IMAGE=jupyterhub/singleuser

# Notebook directory for the single-user server
DOCKER_NOTEBOOK_DIR=/home/<user>/notebooks/

# Docker run command to use when spawning single-user containers
DOCKER_SPAWN_CMD=/srv/singleuser/singleuser.sh

# Notebook to run in for the single-user server
NOTEBOOK=<mynotebook>.ipynb

# Hosted Domain
HOSTED_DOMAIN=jupyterhub

# DNS Name or address IP
HUB_IP_CONNECT=jupyterhub

# Name of JupyterHub container data volume
DATA_VOLUME_HOST=jupyterhub-data

# Data volume container mount point
DATA_VOLUME_CONTAINER=/data
```

* Creating network and volume:
```
docker network create --driver overlay --subnet=172.10.0.0/24 jupyterhub-network

docker volume create --name jupyterhub-data
```


I'm now facing two problems. 

* Using Google OAuth for the authentification process, dockerspawner spawn the container with the email of the user for naming the container (by replacing special characters). It seems not working with an attached volume. dockerspawner failed to spawn with the associated volume data if it contains special characters. It seems like the {username} parameter in the jupyterhub_config.py does not escape characters like @.

* After deploying the swarm with virtual machines (VirtualBox under Mac OS X), one node as a swarm manager and another as a node, I run the JupyterHub container in the swarm manager, but the dockerspawner always spawn to the swarm manager node, and not to the agent node. The network is created and the dockerspawner is configured to be able to deploy to the configured network (see above).

**Comment by minrk** [comment]
I've been meaning to write up an example deployment with docker swarm, especially the new swarm stuff in 0.13, but I've been swamped with other things. Thanks @henring for the detailed examples!

**Comment by minrk** [comment]
The first thing missing in the original post appears to be a small typo: the config file should be `jupyterhub_config.py`, not `jupyter_config.py`. And it must be loaded by JupyterHub. If you want to do this automatically, you can use `FROM jupyterhub/jupyterhub-onbuild` instead of `FROM jupyterhub/jupyterhub`. Or, you can add the config file manually, with `ADD jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py` in your Dockerfile.

**Comment by millelog** [comment]
Is jupyterhub expected to work with Docker v1.12's swarm mode soon? And if it already does, is there an example of how that deployment would deviate from the example here?

**Comment by pjamason** [comment]
Is the docker overlay network required for DockerSpawner to work with Docker Swarm?  This issue suggests it is (https://github.com/jupyterhub/dockerspawner/issues/92) while this one suggests it isn't (https://github.com/jupyterhub/dockerspawner/pull/72)?  

I'm getting the same timeout error described in #72 :

`    TimeoutError: Server at http://172.31.35.113:32776/user/student2 didn't respond in 30 seconds
` 

I'm using the [Zonca](https://github.com/jupyterhub/dockerspawner/issues/92) tutorial mentioned above and launching jupyterhub from the command line.  System users have their home dirs available on the manager and worker nodes via an AWS EFS /home mount, so I've replaced the sqlite db with the [postgres db container](https://github.com/jupyterhub/jupyterhub/tree/master/examples/postgres) due to NFS issues with the former : 

`sudo /home/ubuntu/miniconda3/bin/jupyterhub --debug -f /home/ubuntu/jupyterhub_config.py --db=postgresql://jupyterhub:<pass>@localhost:5433/jupyterhub
`


I've confirmed that my swarm worker node notebook containers are launched without errors, and can see the hub address/port:

```
$ docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                     NAMES
1ff13b8a7ad5        zonca/jupyterhub-datascience-systemuser   "tini -- sh /srv/sing"   8 seconds ago       Up 7 seconds        0.0.0.0:32776->8888/tcp   jupyter-student2
1941e0a3dec3        swarm                                     "/swarm join --advert"   31 hours ago        Up 31 hours         2375/tcp                  lonely_hawking

$ docker logs 1ff13b8a7ad5
Creating user student2 (1002)
/opt/conda/lib/python3.5/site-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[I 2017-02-15 01:01:26.759 student2 notebookapp:1116] Serving notebooks from local directory: /home/student2
[I 2017-02-15 01:01:26.759 student2 notebookapp:1116] 0 active kernels 
[I 2017-02-15 01:01:26.759 student2 notebookapp:1116] The Jupyter Notebook is running at: http://0.0.0.0:8888/user/student2/
[I 2017-02-15 01:01:26.759 student2 notebookapp:1117] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

$ docker restart 1ff13b8a7ad5
$ docker exec -u student2 -it  1ff13b8a7ad5 bash
student2@1ff13b8a7ad5:~$ curl -v http://172.31.34.81:8081
* Rebuilt URL to: http://172.31.34.81:8081/
*   Trying 172.31.34.81...
* Connected to 172.31.34.81 (172.31.34.81) port 8081 (#0)
> GET / HTTP/1.1
> Host: 172.31.34.81:8081
> User-Agent: curl/7.45.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Content-Security-Policy: frame-ancestors 'self'; report-uri /hub/security/csp-report
< Content-Length: 0
< Server: TornadoServer/4.4.2
< Date: Wed, 15 Feb 2017 01:50:57 GMT
< Location: /hub
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host 172.31.34.81 left intact
```

However I don't see any traffic to the hub IP/port from the worker node in the docker log above (should there be?), nor if I monitor it with tcpdump.

Here's my jupyterhub_config.py: 
```

import os

c.JupyterHub.extra_log_file = '/var/log/jupyterhub.log'

# Point DockerSpawner to Swarm instead of the local DockerEngine
os.environ["DOCKER_HOST"] = ":4000"
                
# We use NGINX for SSL
c.JupyterHub.confirm_no_ssl = True

# The docker instances need access to the Hub, so the default loopback port doesn't work:
from IPython.utils.localinterfaces import public_ips
c.JupyterHub.hub_ip = public_ips()[0]

c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
# see https://hub.docker.com/r/zonca/jupyterhub-datascience-systemuser/builds/
c.DockerSpawner.container_image = 'zonca/jupyterhub-datascience-systemuser'
c.DockerSpawner.remove_containers = False
c.Spawner.debug = True

# https://github.com/jupyterhub/dockerspawner/pull/72
c.DockerSpawner.container_ip = '0.0.0.0'
c.DockerSpawner.hub_ip_connect = c.JupyterHub.hub_ip

# log all database transactions. This has A LOT of output
c.JupyterHub.debug_db = True

# show debug output in configurable-http-proxy
c.JupyterHub.debug_proxy = True
```


And my [nginx.conf](https://gist.github.com/zonca/08c413a37401bdc9d2a7f65a7af44462) reverse proxy with SSL:

```
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
  worker_connections 1024;
}

http {

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

    server {
        listen 80;
        server_name <hostname>;
            rewrite        ^ https://$host$request_uri? permanent;
}

    server {
        listen 443;
        client_max_body_size 50M;

        server_name <hostname>;

        ssl on;
        #ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate /etc/nginx/ssl/ssl-bundle.crt;
        #ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_certificate_key /etc/nginx/ssl/jupyterhub_ucsd_edu.key;

        ssl_ciphers "AES128+EECDH:AES128+EDH";
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
        add_header X-Content-Type-Options nosniff;
        ssl_stapling on; # Requires nginx >= 1.3.7
        ssl_stapling_verify on; # Requires nginx => 1.3.7
        resolver_timeout 5s;

        # Expose logs to "docker logs".
        # See https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile#L12-L14
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        #location ~ /(user-[a-zA-Z0-9]*)/static(.*) {
        #    alias /usr/local/lib/python3.4/dist-packages/notebook/static/$2;
        #}

        location / {
            #proxy_pass http://localhost:8000;
            proxy_pass http://127.0.0.1:8000;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-NginX-Proxy true;
        }

        location ~* /(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/? {
            #proxy_pass http://localhost:8000;
            proxy_pass http://127.0.0.1:8000;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-NginX-Proxy true;

            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;

        }
    }

}
```

Any help is appreciated.  Thanks for all your efforts on these excellent resources.

**Comment by barrachri** [comment]
Hello, which Swarm are you using ?

**Comment by pjamason** [comment]
I'm using the legacy swarm version from docker-engine=1.11.2, thanks. 

Also running a consul container as described in the [Zonca](https://zonca.github.io/2016/05/jupyterhub-docker-swarm.html) tutorial to store information about the nodes:

`sudo docker run --restart=always  -d -p 4000:4000 swarm manage -H :4000 --replication --advertise 172.31.34.81:4000 consul://172.31.34.81:8500`

Forgot to mention that tutorial is for ubuntu 14.04, I'm running 16.04, so I've made the necessary docker configuration changes for using systemd instead of upstart, e.g.:

```
ubuntu@jupyterhub:~$ more /etc/systemd/system/docker.service.d/custom.conf
[Service]
ExecStart=/usr/bin/docker daemon -H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock
```

**Comment by barrachri** [comment]
I can't help you with the Swarm < 1.12, sorry :(

**Comment by pjamason** [comment]
Thanks.  Came across your SwarmSpawner earlier today.  Wish I had seen that earlier, when I was trying to get that version of Swarm working.  ;-)

My 'fix' for now was to open up the ephemeral port range starting at 32768 to inbound traffic from the manager.

**Comment by nasedil** [comment]
> After deploying the swarm with virtual machines (VirtualBox under Mac OS X), one node as a swarm manager and another as a node, I run the JupyterHub container in the swarm manager, but the dockerspawner always spawn to the swarm manager node, and not to the agent node. The network is created and the dockerspawner is configured to be able to deploy to the configured network (see above).

@henring did you manage to cope with that issue?  I'm having now the same situation, but no success with solving it.

**Comment by willingc** [comment]
Closing this issue since it's scope is very broad and the issue has been inactive for several months. Please feel free to open a more specific new issue.

I'm also going to label this as Reference since there are some good tips in the list of responses. Thanks everyone! :sunflower:
