### ISSUE TITLE
Conda directory issue with dockerspawner

### ISSUE THREAD

**Issue by madiazp** [jupyterhub/dockerspawner#132]
Hi, I'm trying to use a local conda with my user.

I'm using ldap auth so I mount de users files from other server to the docker container. The path to home in the server is /mnt/users/home/my_user that is where the files are mounted. In the user directory i set my own conda dir witch is /mnt/user/home/my_user/Anaconda3 and the path of the binaries is /mnt/user/home/my_user/Anaconda3/bin.

When i opened a terminal in the notebook from the jupyterhub server and tried to use conda the command used the container's system conda so y put in the .bashrc of my_user the path to my conda.
.bashrc:

> 
> 
>
> if [ -f /etc/bashrc ]; then
>         . /etc/bashrc
> fi
> 
> 
> export CONDA_DIR=$HOME/anaconda3
> export PATH=$HOME/anaconda3/bin:$PATH

The $HOME variable in the container is /home/my_user, and conda in the container show this output:

> madiaz@3272e9e51b3e:~$ conda                                                                                                 
> bash: /home/madiaz/anaconda3/bin/conda: /mnt/users/home/madiaz/anaconda3/bin/python: bad interpreter: No such file or directory 

In the server conda works fine but in the container i don't know why it try to searh its files in /mnt/users/home. There is a way to specify to the spawner where will be all the conda files?

Here is the env output in the container         

> madiaz@3272e9e51b3e:~$ env                                                                                                                
> HOSTNAME=3272e9e51b3e                                                                                                                     
> NB_USER=jovyan                                                                                                                            
> TERM=xterm                                                                                                                                
> SHELL=/bin/bash                                                                                                                           
> JPY_USER=madiaz                                                                                                                           
> JPY_BASE_URL=/user/madiaz                                                                                                                 
> LC_ALL=en_US.UTF-8                                                                                                                        
> USER=madiaz                                                                                                                               
> SUDO_USER=root                                                                                                                            
> SUDO_UID=0                                                                                                                                
> JUPYTER_SERVER_URL=http://0.0.0.0:8888/user/madiaz/                                                                                       
> USERNAME=madiaz                                                                                                                           
> COLUMNS=138                                                                                                                               
> PATH=/home/madiaz/anaconda3/bin:/opt/conda/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                
> PWD=/home/madiaz                                                                                                                          
> JPY_HUB_PREFIX=/hub/                                                                                                                      
> USER_ID=1005                                                                                                                              
> JPY_HUB_API_URL=http://10.6.91.207:8081/hub/api                                                                                           
> LANG=en_US.UTF-8                                                                                                                          
> LINES=39                                                                                                                                  
> JPY_COOKIE_NAME=jupyter-hub-token-madiaz                                                                                                  
> SHLVL=1                                                                                                                                   
> HOME=/home/madiaz                                                                                                                         
> SUDO_COMMAND=/usr/local/bin/jupyterhub-singleuser --port=8888 --ip=0.0.0.0 --user=madiaz --cookie-name=jupyter-hub-token-madiaz --base-url
> =/user/madiaz --hub-prefix=/hub/ --hub-api-url=http://10.6.91.207:8081/hub/api                                                            
> LANGUAGE=en_US.UTF-8                                                                                                                      
> JUPYTER_SERVER_ROOT=/home/madiaz                                                                                                          
> XDG_CACHE_HOME=/home/jovyan/.cache/                                                                                                       
> LOGNAME=madiaz                                                                                                                            
> DEBIAN_FRONTEND=noninteractive                                                                                                            
> CONDA_DIR=/home/madiaz/anaconda3                                                                                                          
> SUDO_GID=0                                                                                                                                
> PYXTERM_DIMENSIONS=80x25                                                                                                                  
> NB_UID=1000                                                                                                                               
> _=/usr/bin/env 
> 

And this is the jupyterhub_config.py:

> c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
> c.LDAPAuthenticator.server_address = '#CENSORED'
> c.LDAPAuthenticator.bind_dn_template = '#CENSORED'
> c.LDAPAuthenticator.use_ssl = False
> c.JupyterHub.confirm_no_ssl = True
> c.LDAPAuthenticator.server_port = 389
> c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
> c.SystemUserSpawner.host_homedir_format_string = '/mnt/users/home/{username}'
> docker0 = netifaces.ifaddresses('docker0')
> docker0_ipv4 = docker0[netifaces.AF_INET][0]
> c.JupyterHub.hub_ip = docker0_ipv4['addr']
> c.PAMAuthenticator.open_sessions = False
>

**Comment by madiazp** [comment]
Solved.

I found an attribute in the DockerSpawner Class called "image_homedir_format_string" , I set this as my home direction in the server "/mnt/users/home/" and everything works fine now.

**Comment by mtekman** [comment]
Thanks for this, by setting the `host_homedir_format_string` and `image_homedir_format_string` variables to the user custom home directories, conda started working again.

```
class YourDockerSpawner(SystemUserSpawner):

    def options_from_form(self, formdata):
        options = {}

        ## host tells us where to look for "home" on the server
        ## image tells us where to set "home" in the image.
        ## - We set them to the same location, because this fixes an issue
        ##   where people cannot see their conda installs        
        options['host_homedir_format_string'] = self.host_homedir_format_string
        options['image_homedir_format_string'] = self.host_homedir_format_string

        return options
```
