### ISSUE TITLE
Delete or update jupyter/singleuser on docker hub

### ISSUE THREAD

**Issue by akhmerov** [jupyterhub/dockerspawner#135]
While [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) are extremely well maintained, often updated, and tagged, the `jupyter/singleuser` image on the [hub](https://hub.docker.com/r/jupyter/singleuser/tags/) has been last updated 9 months ago, wasn't tagged. This may be confusing to the users (at least it was for me): I built an image using `FROM jupyter/singleuser`, which is a terrible idea.

**Comment by barrachri** [comment]
Actually you should build your image and then _**patch it**_ with the single-user things.

But adding more info is always a great idea :)

**Comment by akhmerov** [comment]
I understand what one needs to do, I'm just saying that probably the image in its current state shouldn't be on the hub...

**Comment by barrachri** [comment]
What I was trying to say is that adding more info inside the hub or here would be a great idea.

Actually the image grab directly from jupyter/scipy-notebook so I think there is not really a lot to do about maintaining the image.

But for people that don't have experience with Dockerfile I suppose is a good way to start.

**Comment by minrk** [comment]
`jupyter/singleuser` moved to `jupyterhub/singleuser`, at which point the old one stopped updating. I've updated the description to indicate that. I don't think removing out of date images is the right thing to do, though.

All of the docker-stacks have the singleuser entrypoint installed, so you can [set the command](https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook#start-singleusersh) to start-singleuser.sh.

**Comment by akhmerov** [comment]
Thanks, I think this resolves the issue.
