### ISSUE TITLE
specify destination node when using swarm

### ISSUE THREAD

**Issue by ddavidebor** [jupyterhub/dockerspawner#138]
Hi,

I'm interested in the possibility of specifying the destination node when using dockerspawner with docker swarm.

example: https://forums.docker.com/t/docker-1-12-0-swarm-run-on-specific-node/19865

Does, to your knowledge, any such feature exist in Jupyterhub?

Davide

**Comment by barrachri** [comment]
Currently DockerSpawner doesn't work with Docker Engine in Swarm Mode.

**Comment by ddavidebor** [comment]
Cool :-)
