### ISSUE TITLE
JupyterHub with GitLab OAuth Example

### ISSUE THREAD

**Issue by westurner** [jupyterhub/dockerspawner#141]
- [ ] DOC: https://github.com/jupyterhub/dockerspawner/tree/master/examples/oauth
  - [ ] https://github.com/jupyterhub/oauthenticator#github-setup
  - [ ] https://github.com/jupyterhub/oauthenticator#gitlab-setup .
    - [ ] https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/gitlab.py  
  - [ ] https://github.com/jupyterhub/oauthenticator#google-setup
  - [ ] https://github.com/jupyterhub/oauthenticator#openshift-setup
- [ ] ENH,SEC,DOC: stacked auth: GitLab OAuth and/or Google OAuth and/or {Local,}

References

- jupyterhub_config.py, {source .env, os.environ}
  - https://github.com/jupyterhub/dockerspawner/issues/129#issuecomment-265771311 GoogleAuthenticator
    - jupyterhub_config.py
    - .env
  - https://github.com/jupyterhub/jupyterhub-deploy-docker
    - https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/.env
    - https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/jupyterhub_config.py < .env
    - https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/docker-compose.yml < .env
    - https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/Dockerfile.jupyterhub
      - FROM jupyterhub/jupyterhub-onbuild:0.7.0
        - https://github.com/jupyterhub/jupyterhub/blob/master/onbuild/Dockerfile
          - FROM jupyterhub/jupyterhub
            https://github.com/jupyterhub/jupyterhub/blob/master/Dockerfile
            - FROM debian:jessie
              - https://hub.docker.com/_/debian/
              - https://github.com/docker-library/official-images/blob/master/library/debian
              - https://github.com/tianon/docker-brew-debian/blob/dist-stable/jessie/backports/Dockerfile
              - https://github.com/tianon/docker-brew-debian/blob/dist-stable/jessie/slim/Dockerfile
                - FROM scratch
                  https://docs.docker.com/engine/userguide/eng-image/baseimages/#/creating-a-simple-base-image-using-scratch
          - ``ONBUILD ADD jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py``
          - ``CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]``

**Comment by minrk** [comment]
What is this Issue asking for? A bunch of bullets doesn't make it clear.

**Comment by westurner** [comment]
> What is this Issue asking for? A bunch of bullets doesn't make it clear.

+DOC: JupyterHub with GitLab OAuth Example

**Comment by westurner** [comment]
> What is this Issue asking for? A bunch of bullets doesn't make it clear.

ENH,SEC,DOC: stacked auth: GitLab OAuth and/or Google OAuth and/or {Local,}

This maybe should be another issue:

oauthenticator: ENH,REQ,SEC: stacked auth: {A,B,local}

**Comment by minrk** [comment]
It would be very helpful to use full sentences describing issues and feature requests.

**Comment by willingc** [comment]
Closing as the [recent merge of documentation updates for oauthenticator](https://github.com/jupyterhub/oauthenticator/pull/87) covers GitLab.

**Comment by westurner** [comment]
On Sunday, July 16, 2017, Carol Willing <notifications@github.com> wrote:

> Closing as the recent merge of documentation updates for oauthenticator
> <https://github.com/jupyterhub/oauthenticator/pull/87> covers GitLab.
>
Thanks!

**Comment by westurner** [comment]
On Sunday, July 16, 2017, Wes Turner <wes.turner@gmail.com> wrote:

>
>
> On Sunday, July 16, 2017, Carol Willing <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Closing as the recent merge of documentation updates for oauthenticator
>> <https://github.com/jupyterhub/oauthenticator/pull/87> covers GitLab.
>>
> Thanks!
>

What about GitLab?

**Comment by willingc** [comment]
@westurner Here's a link to the GitLab section of README: https://github.com/jupyterhub/oauthenticator#gitlab-setup
