### ISSUE TITLE
use  _escaped_name when doing username substitution in volume names

### ISSUE THREAD

**Issue by jdavidheiser** [jupyterhub/dockerspawner#142]
I ran into this while running an instance authenticated against Google Oauth - a config of the form 

`c.DockerSpawner.volumes = {'jupyterhub-user-{username}': home_dir}`

fails because the `{username}` substitution gets `user@domain.com` instead of `user_40domain_2Ecom`

**Comment by jdavidheiser** [comment]
Was able to fix this by using volumenamingstrategy.  This was only obvious after reading the tests, so it might be a good idea to add to docs.


```
c.DockerSpawner.format_volume_name = dockerspawner.volumenamingstrategy.escaped_format_volume_name
c.DockerSpawner.volumes = {"jupyterhub-user-{username}": "/home/jovyan"}
```

**Comment by willingc** [comment]
Hi @jdavidheiser,

Thanks for sharing your solution.  :cake:

I've labeled this issue as reference so others can find this when troubleshooting.
