### ISSUE TITLE
handle more than one docker image with jupyterhub

### ISSUE THREAD

**Issue by updiversity** [jupyterhub/dockerspawner#144]
Is it possible at the moment to handle several docker images ?

I mean for example I have two docker images (image1 & image2) that represent two different jupyter notebook stacks and I'd like some users to use image1 and the other users to use image2.

**Comment by minrk** [comment]
Not with the base DockerSpawner, but a subclass could use the options form to provide a dropdown selecting the image from a list.

**Comment by gsayer** [comment]
You can use this example:
```python
from dockerspawner import DockerSpawner

class DemoFormSpawner(DockerSpawner):
    def _options_form_default(self):
        default_stack = "jupyter/minimal-notebook"
        return """
        <label for="stack">Select your desired stack</label>
        <select name="stack" size="1">
        <option value="jupyter/r-notebook">R: </option>
        <option value="jupyter/tensorflow-notebook">Tensorflow: </option>
        <option value="jupyter/datascience-notebook">Datascience: </option>
        <option value="jupyter/all-spark-notebook">Spark: </option>
        </select>
        """.format(stack=default_stack)

    def options_from_form(self, formdata):
        options = {}
        options['stack'] = formdata['stack']
        container_image = ''.join(formdata['stack'])
        print("SPAWN: " + container_image + " IMAGE" )
        self.container_image = container_image
        return options

c.JupyterHub.spawner_class = DemoFormSpawner
```
And I am interested in improvements in the code you could make :)

@minrk minrk Currently I work on a module to automatically know the containers on the host with the *docker  2.1.0* python library but it conflicts with the *docker-py 1.10.6* python library (same library but different version), why dockerspawner use the old library *docker-py 1.10.6* and not *docker 2.1.0* ? Thk

**Comment by minrk** [comment]
>  why dockerspawner use the old library docker-py 1.10.6 and not docker 2.1.0 ?

Because the package was renamed quite recently and we hadn't noticed until now. I'll update it now, thanks!

**Comment by gsayer** [comment]
Great ! Thks

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!

**Comment by mirestrepo** [comment]
@minrk Can this be used in the Kubernetes/helm set up? Thanks

**Comment by mirestrepo** [comment]
Awesome news! What version of the helm chart could I try? How unstable is the helm? I've often used unstable versions with no major problems in the past, so I'm happy to try unless you strongly discourage. Thanks @minrk!

**Comment by mirestrepo** [comment]
Thank you! I'll give it a try and stay tuned!

**Comment by mathematicalmichael** [comment]
> You can use this example:
> 
> ```python
> from dockerspawner import DockerSpawner
> 
> class DemoFormSpawner(DockerSpawner):
>     def _options_form_default(self):
>         default_stack = "jupyter/minimal-notebook"
>         return """
>         <label for="stack">Select your desired stack</label>
>         <select name="stack" size="1">
>         <option value="jupyter/r-notebook">R: </option>
>         <option value="jupyter/tensorflow-notebook">Tensorflow: </option>
>         <option value="jupyter/datascience-notebook">Datascience: </option>
>         <option value="jupyter/all-spark-notebook">Spark: </option>
>         </select>
>         """.format(stack=default_stack)
> 
>     def options_from_form(self, formdata):
>         options = {}
>         options['stack'] = formdata['stack']
>         container_image = ''.join(formdata['stack'])
>         print("SPAWN: " + container_image + " IMAGE" )
>         self.container_image = container_image
>         return options
> 
> c.JupyterHub.spawner_class = DemoFormSpawner
> ```
> 
> And I am interested in improvements in the code you could make :)
> 
> @minrk minrk Currently I work on a module to automatically know the containers on the host with the _docker 2.1.0_ python library but it conflicts with the _docker-py 1.10.6_ python library (same library but different version), why dockerspawner use the old library _docker-py 1.10.6_ and not _docker 2.1.0_ ? Thk

@minrk I ended up using this snippet because the `image_whitelist` and `allowed_images` stopped working. Was the intent that this should just be customized each time?

<img width="1259" alt="Screen Shot 2020-08-12 at 12 09 21 PM" src="https://user-images.githubusercontent.com/40366263/90051264-a8979b80-dc94-11ea-994e-4d6eeb922c50.png">
<img width="770" alt="Screen Shot 2020-08-12 at 12 10 06 PM" src="https://user-images.githubusercontent.com/40366263/90051332-c533d380-dc94-11ea-9c7d-3c8bced848bb.png">

the code I ended up writing looks a lot like what I imagine an implementation of the whitelist/allowed_images would be.
