### ISSUE TITLE
multiple dockspawner volumes

### ISSUE THREAD

**Issue by sergesvr** [jupyterhub/dockerspawner#145]
Hi,

I'd like to specify several "persistent" volumes.

My understandings is that it should be specified at this line:

`c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }
`
I have done it in that way

`c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir , 'jupyterhub-user-{username}-conda': os.environ['CONDA_DIR']}`

but after instanciating my jupyterhub docker instance, i have checked if the new volume was created, and it hasn't.

Could you tell me what am i doing wrong ?

Thanks

**Comment by willingc** [comment]
Hi @sergesvr,

Closing this issue as it's been inactive for several months. If you are still having this issue or others, please open a new issue or request that we reopen this issue. Thanks! :sunflower:
