### ISSUE TITLE
Container cannot connect to hub API

### ISSUE THREAD

**Issue by yhtang** [jupyterhub/dockerspawner#156]
Hello,

I got the following error when spawning single-user servers:
```
Failed to connect to Hub API at 'http://127.0.0.1:8081/jupyter/hub/api'.
Is the Hub accessible at this URL (from host: d53de1001a4f)?
Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the Hub.
```
I guess this means that the ip 127.0.0.1 means localhost to the docker containers, rather than my host OS. However after applying
```
c.JupyterHub.hub_ip = '172.17.42.1'
```
The error message still persists. Why would the singleuser server still try to connect to 127.0.0.1 in this case?

**Comment by yhtang** [comment]
I figured out --- need to delete the container and respawn.

**Comment by yuanzhou** [comment]
I got the same error message after logging into JupyterHub. I'm using DockerSpawner with PAM authentication. And I'm running the hub on AWS EC2. 

Can you share your solution? Thanks!

**Comment by minrk** [comment]
> What did you do to "delete the container and respawn"? 

This would generally be `docker rm jupyter-{username}` then trigger creation of a new server via JupyterHub.
