### ISSUE TITLE
Question: singleuser write permission error

### ISSUE THREAD

**Issue by Spritekin** [jupyterhub/dockerspawner#157]
Hi,
This is more a Docker question but affects the singleuser notebook I think.

I have Jupyterhub with the DockerSpawner launch a new notebook using Swarm. I have an NFS folder mounted on the host like:
```
/appdata/jupyter-notebooks
```
So when a user logs in the notebook is launched and the folder for the user is created by docker like:
```
/appdata/jupyter-notebooks/grodriguez
```

So this folder is mounted as  /appdata/jupyter-notebooks/grodriguez:/home/jovyan/work:rw so all ok up now.
But then when I try to write a file, the notebook says it doesn't have enough permissions to write!

Then I check the /appdata/jupyter-notebooks/grodriguez folder
```
drwxr-xr-x  2 root root 4096 May  5 16:49 grodriguez
```

So this folder is restricted and will only allow root to write in there so the container can't write to that folder. If I change the permissions like:
```
chown 777 /appdata/jupyter-notebooks/grodriguez
```

Then the notebook can write just fine.

So then I decided to test this, I went into the host and manually run my notebook image and write a file just to test the permissions:
```
docker run -v /home/core/test:/test --entrypoint /bin/bash docker-registry.aws.cmcrc.com:5000/cmcrc/uptick-notebook -c "echo 123 > /test/test.log"
> /bin/bash: /test/test.log: Permission denied
```
Again, the test folder was created with rwxr-xr-x permissions.

If I change and run as root, all goes ok:
```
docker run -v /home/core/test:/test --user root --entrypoint /bin/bash docker-registry.aws.cmcrc.com:5000/cmcrc/uptick-notebook -c "echo 123 > /test/test.log"
echo test.log
123
```

So I guess is the jovyan user not able to write to the folder created by docker. But I don't want to use the root user as this image will be used in a public server.

Any ideas how to solve this?

Thanks!

**Comment by minrk** [comment]
Yeah, if docker mounts a volume that doesn't exist, it will be created with as owned by root with 755 permissions. I'm not sure if there's a way to change this. What you'll need to do is make sure the directory is created with the right owner and/or permissions prior to the container mounting it.

**Comment by Spritekin** [comment]
I see... well... I will have to add a 'USER root' line at the end while we find a way to solve this.
