### ISSUE TITLE
Question: How to increase the timeout?

### ISSUE THREAD

**Issue by Spritekin** [jupyterhub/dockerspawner#158]
Hi!
I have set my timeouts to something over 30s, like:
            --Spawner.http_timeout=300
            --Spawner.start_timeout=300

However my server keeps timing out at 30 seconds. Sometimes I have to wait for my Swarm server to return me some offers as it is quite busy.

Which parameter should I use to increase the timeout?

Thanks

**Comment by minrk** [comment]
Those should indeed work. What version of JupyterHub? What do you see in the logs with `--debug`?

**Comment by Spritekin** [comment]
Hi minrk,

We are using 0.7.2 for all. We had version compatibilities problems between hub and notebook servers while using the latest images so we decided to stick to the latest valid one.

Maybe you should release a 0.7.3 already?

**Comment by minrk** [comment]
We will release 0.8 as soon as we finish up a few things. There probably won't be an 0.7.3

**Comment by willingc** [comment]
Hi all,

I'm closing this since there is no action on this repo. You can track the JupyterHub 0.8 release milestone [here](https://github.com/jupyterhub/jupyterhub/milestone/5).
