### ISSUE TITLE
404 error trying to load user notebook

### ISSUE THREAD

**Issue by epifanio** [jupyterhub/dockerspawner#159]
Trying to load the notebook server, after the prompt *start server* I got a 404 error: 

```
Jupyter Notebook
404 : Not Found

You are requesting a page that does not exist!
```

Which is lacking css style etc, and  the following log is printed in the shell

https://gist.github.com/50859fabf211ebea31ecb25bfa19fb8c

I start the notebook as root with: 

```
jupyterhub --port 9999 --config=/etc/jupyterhub/jupyterhub_config.py
```

this is my `jupyter_config.py` : 

```
c.Authenticator.whitelist = {'epinux'}
c.Authenticator.admin_users = {'epinux'}
from jupyter_client.localinterfaces import public_ips
c.JupyterHub.hub_ip = public_ips()[0]
c.JupyterHub.proxy_api_ip = '0.0.0.0'
#import os
#notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
#c.DockerSpawner.notebook_dir = notebook_dir
#c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }
c.JupyterHub.ssl_cert = '/etc/letsencrypt/live/geohab-tools.org/cert.pem'
c.JupyterHub.ssl_key = '/etc/letsencrypt/live/geohab-tools.org/privkey.pem'
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
```

Have you any clue on what I'm missing? I'm using the unix user as authentication (no github).

**Comment by minrk** [comment]
With the docker stacks, you need to set the start command to single-user as described [here](https://github.com/jupyter/docker-stacks/tree/master/base-notebook#start-singleusersh):

```python
# Have the Spawner override the Docker run command
c.DockerSpawner.extra_create_kwargs.update({
	'command': '/usr/local/bin/start-singleuser.sh'
})
```

That shouldn't be necessary when using the default images in the [next release](https://github.com/jupyterhub/dockerspawner/pull/153) of dockerspawner, but that isn't out yet.

**Comment by epifanio** [comment]
Thanks @minrk, I applied the changes in my config and pulled a clean docker image. Now the 404 error is gone, the container is started on the remote server but when I try to load an user notebook I got a 302 error. this the shell log: https://gist.github.com/epifanio/494ed368bc6f4b000510efd2fcfd1f20

**Comment by willingc** [comment]
Hi @epifanio,

I'm closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or request that we reopen this issue. Thanks! :sunflower:
