### ISSUE TITLE
Permission Denied for new user volumes with custom path

### ISSUE THREAD

**Issue by grez72** [jupyterhub/dockerspawner#160]
I'm authenticating users with github, and using DockerSpawner to spawn individual notebooks.

When I set the DockerSpawner volume to anything other than "jupyterhub-user-{username}", I receive a "permission denied" error when trying to create and save a notebook.

e.g., if I set the volume this way
c.DockerSpawner.volumes = { '/path/to/notebooks/jupyterhub-user-{username}': notebook_dir }

...then the container is spawned, but I can't create / save files.

The error occurs because the folder "/path/to/notebooks/jupyterhub-user-{username}" is created when the notebook is spawned, but when it is created it has the user and group "root". If I change the folder's user / group to myusername / users, then I can create and save notebooks. (myusername = my user name on the host computer).

I would like to avoid this step so that my setup will work even when user names aren't known in advance.

My question is, where/when is the folder jupyterhub-user-{username} created, and is it possible to set the user and group when these folders are created? I've looked through the source code, but can't figure out at which point folders are created for new users.

**Comment by Ajay-Changulani** [comment]
I have the exact same issue.

**Comment by gsn-wtorla** [comment]
Ditto

**Comment by minrk** [comment]
This is a general Docker issue that host directories that don't exist at mount time are owned by the docker user (~always root) when they are created for the mount. It's a longstanding frustration with docker. It's not an issue when using internal docker volumes (note no leading slash), which is part of why that's preferred.

You can work around this by preparing the notebooks directory ahead of time with default permissions:

```bash
# create the notebook directory
NBDIR=/path/to/notebooks
mkdir "$NBDIR"
# make it owned by the GID of the notebook containers.
# This is 100 in the jupyter docker-stacks,
# but should be whatever GID your containers run as
chown :100 "$NBDIR"
# make it group-setgid-writable
chmod g+rws "$NBDIR"
# set the default permissions for new files to group-writable
setfacl -d -m g::rwx "$NBDIR"
```

- The `s` in `chmod` means that any new files created in that directory, by any user (including root), will be owned by the same group as the parent, which we set to 100.
- The `setfacl` makes it so that any new files have default permissions including full group access.

The result should be that when docker creates a directory in there for the volume mount (as root), it will be owned and writable by the group 100. If your docker container runs with that GID, then it will be able to create files in there:

```bash
docker run --rm -it -v $NBDIR:/mounted jupyter/base-notebook /bin/bash
jovyan@988878f490a8:~$ touch /mounted/file
jovyan@988878f490a8:~$ mkdir /mounted/dir
jovyan@988878f490a8:~$ ls -la /mounted
total 12
drwxrwsr-x+ 3 root   users 4096 Sep 18 08:54 .
drwxr-xr-x  1 root   root  4096 Sep 18 08:54 ..
drwxrwsr-x+ 2 jovyan users 4096 Sep 18 08:54 dir
-rw-rw-r--  1 jovyan users    0 Sep 18 08:54 file
```

This strategy works in general for creating a directory in which docker volumes can be created and isn't specific to the Jupyter images, but what GID to use will depend on how you run the containers.

**Comment by sangramga** [comment]
@minrk I am facing the same issue. Above solution does not work when we create new users and notebook directory  folders are created and mounted for new users. 

my configuration looks like these:
```
import os
notebook_dir = os.environ.get('NBDIR') or '/home/jovyan/jupyter'
c.DockerSpawner.notebook_dir = notebook_dir
c.DockerSpawner.volumes = { '/home/ubuntu/jupyterhub_volumes/jupyterhub-user-{username}': notebook_dir }
```
I tried setting permissions as above to the PARENT directory, which holds the notebook mount directories `jupyterhub-user-{username}` for each user. They are created with `root` group and not `users` group as shown above. 

Although if I mount static directory (same as you did above) it gets mounted with proper permissions. 
```
c.DockerSpawner.volumes = { '/home/ubuntu/mynotebooks/':notebook_dir }
```
I don't want all  users(all container) to mount the same directory. I want each user to have his own mounted directory.

**Comment by sangramga** [comment]
Found the solution in using `pre_spawn_hook` in Spawner and a bootstrap script to create a folder for each non-exixting user.
Refer to: [https://github.com/jupyterhub/jupyterhub/tree/master/examples/bootstrap-script](https://github.com/jupyterhub/jupyterhub/tree/master/examples/bootstrap-script)

**Comment by acelere** [comment]
Just an adder to this last post by sangramga.
Change the permissions in the [link](https://github.com/jupyterhub/jupyterhub/tree/master/examples/bootstrap-script) to 765 instead of 755. This allows the users in group "users" write permission to that directory.

**Comment by nils-werner** [comment]
I have found another way to fix this problem on Ubuntu by running

```bash
sudo mkhomedir_helper username
```

upon first login. Add the following to `jupyterhub_config.py`:

```python
def create_dir_hook(spawner):
    if not os.path.exists(os.path.join('/home/', spawner.user.name)):
        subprocess.call(["sudo", "/sbin/mkhomedir_helper", spawner.user.name])

c.Spawner.pre_spawn_hook = create_dir_hook
```

and create a file `/etc/sudoers.d/jupyterhub` containing

```
jupyterhub ALL = (root) NOPASSWD: /sbin/mkhomedir_helper
```

If you are using a subdirectory in your user homedirs, e.g. `/home/user/jupyterhub`, make sure that directory exists in `/etc/skel` too:

```bash
mkdir /etc/skel/jupyterhub
```

**Comment by DeoLeung** [comment]
https://github.com/jupyterhub/jupyterhub/tree/master/examples/bootstrap-script

the example in the script works on my mac but not my centos server

I need to change
```python
# origin
os.mkdir(...)
# change to
os.chown(path, 1000, 100)
```

which works on my server

**Comment by ferari02** [comment]
The below configuration worked for me

`
import os
import shutil
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir

c.DockerSpawner.remove_containers = True

c.DockerSpawner.extra_create_kwargs = {'user': 'root'}
def create_dir_hook(spawner):
    username = spawner.user.name # get the username
    volume_path = os.path.join('/home/ubuntu/notebook_volumes/', username) #path on the jupytherhub host, create a folder based on username if not exists
    if not os.path.exists(volume_path):
        os.mkdir(volume_path)
        shutil.chown(volume_path, user=username, group='users')

c.Spawner.pre_spawn_hook = create_dir_hook

c.DockerSpawner.volumes = { ''/home/ubuntu/notebook_volumes/{username}': notebook_dir}`

**Comment by minrk** [comment]
Closing this issue as sufficiently addressed by examples in the comments.

Feel free to open new discussion topics on [the Jupyter forum](http://discourse.jupyter.org) if you have other 'how to' questions.
