### ISSUE TITLE
Display the username instead of "jovyan" in terminal

### ISSUE THREAD

**Issue by yuanzhou** [jupyterhub/dockerspawner#161]
I managed to set up the host-based data persistence with DockerSpawner for each user. But when a user fires up the terminal via jupyterhub, the terminal still says 

![capture](https://cloud.githubusercontent.com/assets/195873/26159173/dbe06baa-3aeb-11e7-9513-692c90002419.PNG)

And `docker inspect jupyter-demo` shows me:

````
 "Mounts": [
            {
                "Name": "jupyterhub-user-demo",
                "Source": "/var/lib/docker/volumes/jupyterhub-user-demo/_data",
                "Destination": "/home/jovyan/work",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],

````

Is there a way that we can show the username instead of "jovyan"? Thanks!

**Comment by minrk** [comment]
This could be done if you set PS1 env in the container and pass the username as an environment variable, e.g.

```python
class MyDockerSpawner(DockerSpawner):
    def get_env(self):
        env = super().get_env()
        env['JUPYTERHUB_USER'] = self.user.name
        env['PS1'] = '$JUPYTERHUB_USER \w $ '
        return env

c.JupyterHub.spawner_class = MyDockerSpawner
```

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
