### ISSUE TITLE
Allow users to specify their own notebook docker image

### ISSUE THREAD

**Issue by yuanzhou** [jupyterhub/dockerspawner#162]
I wanted to allow jupyterhub users to install their own packages, but it requires root privilege and they don't have the root password. I was thinking can I just use my docker image that is built based on `jupyter/scipy-notebook` with all the extra packages pre-installed? Then in `dockerspawner` I can specify to use my container image instead of the default `jupyterhub/singleuser`.

**Comment by minrk** [comment]
Do you want to specify the image, or do you want users to be able to pick from a list?

You can specify the image users use by setting:

```python
c.DockerSpawner.container_image = 'me/my-image:tag'
```

If you want users to be able to pick from a list, you can do this with a bit more configuration, as seen [in this example](https://github.com/jupyterhub/dockerspawner/issues/144#issuecomment-286189384).

**Comment by yuanzhou** [comment]
Thanks, I also found the answer here: https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook#start-singleusersh


````
c.DockerSpawner.container_image = 'me/my-image:tag'
# Have the Spawner override the Docker run command
c.DockerSpawner.extra_create_kwargs.update({
	'command': '/usr/local/bin/start-singleuser.sh'
})
````

It worked very well.
