### ISSUE TITLE
example configuration missing parts

### ISSUE THREAD

**Issue by brianray** [jupyterhub/dockerspawner#163]
I would add more. I can submit a Pull request if that helps?

https://github.com/jupyterhub/dockerspawner/blob/master/examples/oauth/jupyterhub_config.py#L32

```python
c.GitHubOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']
c.GitHubOAuthenticator.client_id = os.environ['GITHUB_CLIENT_ID']
c.GitHubOAuthenticator.client_secret = os.environ['GITHUB_CLIENT_SECRET']

```

**Comment by minrk** [comment]
That's duplicating the default behavior, which is to already read those environment variables. Adding those lines would suggest that they are required, when they are not.

**Comment by willingc** [comment]
Closing.
