### ISSUE TITLE
Shared team volumes for certain users

### ISSUE THREAD

**Issue by TiemenSch** [jupyterhub/dockerspawner#172]
I'm trying to setup a Jupyterhub server on Ubuntu 16.04, much along the lines of https://github.com/minrk/jupyterhub-demo. 

I changed the jupyterhub_config.py to support persistent storage using the tips given here https://github.com/jupyterhub/dockerspawner#data-persistence-and-dockerspawner: 

    notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
    c.DockerSpawner.notebook_dir = notebook_dir
    c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }

However, I would like to add a shared "team" volume for teams of users. I have a dictionary with usernames (keys) and teamnames (values) to map users to teams. 

Ideally I would state something like:

    c.DockerSpawner.volumes = { 
        'jupyterhub-user-{username}': notebook_dir, 
        'jupyterhub-team-{teamname}': os.path.join(notebook_dir, 'shared' 
    }

But I have no clue as to how to pass another {name} mapping to dockerspawner. 

I tried fiddling with these, but so far to no avail:

    c.DockerSpawner. ...
    extra_create_kwargs = Dict(config=True, help="Additional args to pass for container create")
    extra_start_kwargs = Dict(config=True, help="Additional args to pass for container start")
    extra_host_config = Dict(config=True, help="Additional args to create_host_config for container create")

Any help would be greatly appreciated!

P.S. I have also posted this question on [StackOverflow](https://stackoverflow.com/questions/44986021/jupyterhub-singleuser-shared-volume)

**Comment by minrk** [comment]
For more advanced logic not exposed in the default config objects, you can also subclass DockerSpawner in your config file:

```python
from dockerspawner import DockerSpawner
class MyDockerSpawner(DockerSpawner):
    def start(self):
        # username is self.user.name
        team = 'myteam'
        # add team volume to volumes
        self.volumes['jupyterhub-team-{}'.format(team) = '/home/shared'
        return super().start()

c.JupyterHub.spawner_class = MyDockerSpawner
```

**Comment by TiemenSch** [comment]
Many thanks for this solution and explanation

**Comment by cmseal** [comment]
Hi @TiemenSch, @minrk,

I'm looking to do something similar, but mount a shared volume as rw for a few users, but ro for everyone else.

Would this be possible with the subclass example you suggested above?  Those few for rw is pretty static, so usernames can be hard-coded into the config file.

Any help greatly appreciated! I know this is over a year old now...

I currently have this in the config:
```
c.DockerSpawner.volumes = { 
'jupyterhub-user-{username}':'/home/jovyan',
'jupyterhub-shared': {"bind": '/home/jovyan/shared', "mode": "ro"}
}
```

**Comment by minrk** [comment]
Yes, it would be possible via the same approach. Based on the value in `self.user` you can modify `self.volumes` as appropriate.

**Comment by cmseal** [comment]
Thanks for coming back to me, @minrk.

If you've a few minutes spare, would you be able to provide some example code please?  My Python isn't great, and I'm picking it up as I go when editing things, as needed.

I'm just not sure how to alter the provided subclass example to change a specific volume mount for specific usernames.

Any further assistance is greatly appreciated, thanks.

```
from dockerspawner import DockerSpawner
class MyDockerSpawner(DockerSpawner):
    def start(self):
        # username is self.user.name
        team = 'myteam'
        # add team volume to volumes
        self.volumes['jupyterhub-team-{}'.format(team) = '/home/shared'
        return super().start()

c.JupyterHub.spawner_class = MyDockerSpawner
```

**Comment by cmseal** [comment]
@minrk thanks for this... you've been very helpful!

**Comment by mirestrepo** [comment]
@minrk What would be the appropriate to apply this configuration change to JupyterHub in running in GKE? Thank you in advance!

**Comment by nuraym** [comment]
I am trying to achieve a shared directory for all users. I created a shared-file folder in my Jupyterhub.
Added this to my jupyterhub_config.py

notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/jupyter' c.DockerSpawner.notebook_dir = notebook_dir c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir, 'shared-data/volumes': '/home/jovyan/shared' }
I am launching JupyterHub from my terminal locally using jupyterhub -f jupyterhub_config.py
What am I missing?

**Comment by minrk** [comment]
I'm going to close this one as the original question is answered. 

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/shared-writable-folder-for-each-group/13498/3
