### ISSUE TITLE
Jupyterhub on Azure Container Service

### ISSUE THREAD

**Issue by puneetjindal** [jupyterhub/dockerspawner#178]
I am stuck with configuration of JupyterHub and auto-spawning of single user notebook servers over Azure Container Service with orchestration as Swarm
Can anybody provide me pointers to similar type of work done

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.
