### ISSUE TITLE
host_ip Setting for Windows Containers

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/dockerspawner#191]
Unfortunately Windows doesn't support NAT IP binding for containers:
moby/moby#26980

I found a workaround which was to set  `c.DockerSpawner.container_ip = ""` and everything Just Worked!

If I update the setting to  `c.DockerSpawner.host_ip = ""` I get the original docker error:
```
docker.errors.APIError: 500 Server Error: Internal Server Error
("failed to create endpoint jupyter-dhirschf on network nat: Windows does not support host IP addresses in NAT settings")
```

Keeping the original setting, even though deprecated, still works though.

So it appears there's some difference in the behaviour of the two settings which break my workaround for the lack of IP binding support on Windows.

**Comment by dhirschfeld** [comment]
This is mostly just a note to myself to investigate further any differences in behaviour though I opened this issue in case it's useful/interesting for anyone else.

Some useful refs:
  * https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/
  * https://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/

**Comment by minrk** [comment]
Hm. I thought I only renamed this config, not changed what it does. I'll have to look through what I did. It may be mishandling the empty case.

**Comment by dhirschfeld** [comment]
Not urgent - the old config works well enough for now and unless it's obvious it might be hard for you to repro to debug further!

**Comment by dhirschfeld** [comment]
With `container_ip = ''` the `create_kwargs` passed to the [docker start command](https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L580) include the below `host_config`:

![image](https://user-images.githubusercontent.com/881019/30840520-1d88eb7c-a2bb-11e7-9e0a-491152d9bc77.png)
i.e.
```python
create_kwargs['host_config']['PortBindings']['8888/tcp'] == [{'HostIp': '', 'HostPort': ''}]
```

Whereas with `host_ip = ''` the `host_config` section looks like:

![image](https://user-images.githubusercontent.com/881019/30839906-d9a8f7a6-a2b7-11e7-9011-54854bf67845.png)

i.e.
```python
create_kwargs['host_config']['PortBindings']['8888/tcp'] == [{'HostIp': '127.0.0.1', 'HostPort': ''}]
```

Just dumping some debug data here - will continue to investigate...

**Comment by minrk** [comment]
@dhirschfeld have you set `c.DockerSpawner.use_internal_ip = False` ?

**Comment by dhirschfeld** [comment]
In my config `c.DockerSpawner.use_internal_ip` is `False` - that's correct isn't it?

<details>
<summary><b>JupyterHub config:</b></summary>

```python
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_port = 8081
c.JupyterHub.hub_connect_ip = public_ips()[0]

c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = "ldap.stanwell.com"
c.LDAPAuthenticator.admin_users = set(['dhirschf'])


c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.Spawner.default_url = '/lab'


c.DockerSpawner.volumes = {
    'C:/Miniconda3': 'C:/Miniconda3',
    'C:/Jupyter/{username}': 'C:/jupyter',
}
c.DockerSpawner.host_ip = ""
c.DockerSpawner.port = 8888
c.DockerSpawner.use_internal_ip = False
c.DockerSpawner.image = 'jupyterlab'
c.DockerSpawner.remove_containers = True
c.DockerSpawner.debug = True
c.DockerSpawner.extra_create_kwargs = dict()
c.DockerSpawner.extra_start_kwargs = {
    '--notebook-dir': 'C:/jupyter',
    '--MultiKernelManager.default_kernel_name': "python-dev",
    '--KernelSpecManager.ensure_native_kernel': False,
    '--NotebookApp.allow_origin': '*',
}
network_name = 'nat'
c.DockerSpawner.network_name = network_name
c.DockerSpawner.extra_host_config = {
    'network_mode': network_name,
}
```
</details>

**Comment by dhirschfeld** [comment]
Circling back to this, it seems the `c.DockerSpawner.host_ip` config setting is being ignored?

In the debugger, at line 537 below:
https://github.com/jupyterhub/dockerspawner/blob/19e26f3d1f5fd196b2a750f9e9c525bcfa0c95fb/dockerspawner/dockerspawner.py#L536-L539
...I observe that the config value I set `192.168.1.1` is in the config dict but hasn't been applied - the `self.host_ip` is the default `127.0.0.1`:
```python
>>> self
<dockerspawner.dockerspawner.DockerSpawner object at 0x0000018DCB091CC0>
>>> self.host_ip
'127.0.0.1'
>>> self.config['DockerSpawner']['host_ip']
'192.168.1.1'
```
