### ISSUE TITLE
Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.

### ISSUE THREAD

**Issue by burdickjp** [jupyterhub/dockerspawner#198]
```
Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.  Is the Hub accessible at this URL (from host: 4c2b34c60046)?  Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the Hub.
```

I cannot, for the life of me, get jupyterhub working with dockerspawner. I've seen other posts with a similar error and have tried their solutions, and none of them are working.
I'm running this on a Fedora 26 VM. 
I'm thinking it may be a docker configuration problem. What could be getting in the way?

**Comment by minrk** [comment]
You want to set the following configuration:

```python
c.JupyterHub.hub_ip = 'a.b.c.d'
```

where `a.b.c.d` is an ip-address of the Hub machine that is accessible from your docker containers. Are you running the Hub itself with docker, or on the host? If it's on the host, one way to do this is to get the ip address of the `docker0` interface.

**Comment by burdickjp** [comment]
I have passed this project to a coworker who appears to have remedied the issue.

**Comment by AcademicAdmin** [comment]
I would also like to know the solution. I am currently experiencing the same issue (and have already set c.JupyterHub.hub_ip)

**Comment by nils-werner** [comment]
We have solved it with a `jupyterhub_config.py` like

```python
from jupyter_client.localinterfaces import public_ips
import dockerspawner

ip = public_ips()[0]

c.JupyterHub.hub_ip = ip
c.JupyterHub.spawner_class = SystemUserSpawner

c.DockerSpawner.image = 'jupyter/scipy-notebook:0f73f7488fa0'
c.DockerSpawner.host_homedir_format_string = "/home/{username}/jupyterhub"

c.DockerSpawner.remove_containers = True
c.DockerSpawner.remove = True
```

and then punching a hole in the firewall by adding

```
-A ufw-user-input -s 172.16.0.0/12 -j ACCEPT
```

in `/etc/ufw/user.rules` (`172.16.0.0/12` is the Docker IP range)

**Comment by remram44** [comment]
Whatever I do, the spawned container connects to `127.0.0.1:8081`. Is there a separate config file for the spawned container?

**Comment by remram44** [comment]
Seems like there is `c.DockerSpawner.hub_connect_ip`?

Also don't forget to `rm -f` the container(s) before trying again...
