### ISSUE TITLE
README confusing about using docker-stacks images

### ISSUE THREAD

**Issue by takluyver** [jupyterhub/dockerspawner#199]
The *Picking or building a Docker image* section of the README seems to contradict itself. First it says:

> Any of the existing Jupyter docker stacks can be used with JupyterHub, provided that the version of JupyterHub in the image matches, and are encouraged as the image of choice. Make sure to pick a tag!
>
> `c.DockerSpawner.image = 'jupyter/scipy-notebook:8f56e3c47fec'`

Then later:

> For instance, from the docker-stacks, pin your JupyterHub version and you are done:
>
> ```
> FROM jupyter/scipy-notebook:8f56e3c47fec
> ARG JUPYTERHUB_VERSION=0.8.0
> RUN pip3 install --no-cache \
>    jupyterhub==$JUPYTERHUB_VERSION
> ```

I'd guess from this that the latest version can use the docker-stacks images directly, whereas older versions needed the extra steps on top of that?

This is also not entirely clear to me:

> 4. CMD launches jupyterhub-singleuser OR the c.Spawner.cmd configuration is used to do this.

The docker-stacks don't launch `jupyterhub-singleuser` by default; does this mean that `c.Spawner.cmd` needs to be set as well when using these? Or is that handled some other way?

**Comment by minrk** [comment]
> I'd guess from this that the latest version can use the docker-stacks images directly, whereas older versions needed the extra steps on top of that?

Exactly right. This extra build step is only necessary if the version in the image is not the same as what's in your Hub. So this bit of the docs should be specifying "if the version in your chosen tag is not the same as your Hub, you may need to upgrade or downgrade JupyterHub in the image to match"...

> The docker-stacks don't launch jupyterhub-singleuser

They detect if they are being launched by JupyterHub [from the environment](https://github.com/jupyter/docker-stacks/blob/281505737f8a24cb19fb5e335738dff9736fb591/base-notebook/start-notebook.sh#L9), and pick notebook or singleuser based on that.

**Comment by takluyver** [comment]
Thanks, that's useful. :-)

**Comment by minrk** [comment]
I think the docs are clearer on this now
