### ISSUE TITLE
Docker layout

### ISSUE THREAD

**Issue by rgbkrk** [jupyterhub/dockerspawner#2]
This kind of belongs across several repositories, but I'll post it here since it's very Docker centric.

Earlier @minrk and I talked about how we would layout containers for JupyterHub. While talking with Min over chat, we laid them out as diagrams.

These may be wrong from the current state, so I'll update these to show where we were at and where we're going.

### OAuthenticator example

Spawns single user servers, independent of each other

![screen shot 2014-09-27 at 4 03 30 pm](https://cloud.githubusercontent.com/assets/836375/4432186/cc17433c-4689-11e4-9e06-16de5c15e8a9.png)

### JupyterHub Dockerfile

Just JupyterHub basics: no special packages everyone operates on the same file system in the container

![screen shot 2014-09-27 at 4 03 35 pm](https://cloud.githubusercontent.com/assets/836375/4432184/cc1228ca-4689-11e4-93be-5bd1a9414894.png)

### JupyterHub

*Note: This doesn't exist, is an illustration of what @rgbkrk is leaning towards for a shared environment*

Run on Host or Docker using the base jupyter/jupyterhub image, allow for configuration with OAuth, allow users to choose what image they're grouped.

This needs access to the Docker Unix socket or API access to Docker.

![screen shot 2014-09-27 at 4 03 40 pm](https://cloud.githubusercontent.com/assets/836375/4432185/cc1544a6-4689-11e4-868d-0ddb97cfda52.png)

**Comment by willingc** [comment]
@rgbkrk @minrk I'm going to label this issue as `reference` and close it. I'm using `reference` to identify closed issues that contain content that may have images/text that may have future value in planning.

**Comment by rgbkrk** [comment]
Thanks @willingc

**Comment by minrk** [comment]
Thanks!
