### ISSUE TITLE
where is JPY_USER, JPY_COOKIE_NAME, JPY_BASE_URL,  JPY_HUB_PREFIX, JPY_HUB_API_URL

### ISSUE THREAD

**Issue by rydeng** [jupyterhub/dockerspawner#202]
JPY_USER, JPY_COOKIE_NAME, JPY_BASE_URL,  JPY_HUB_PREFIX, JPY_HUB_API_URL are deleted, now how to spawn a docker, before I do like this:

```
exec python3 /srv/singleuser/singleuserapp.py \
  --port=8888 \
  --ip=0.0.0.0 \
  --user=$JPY_USER \
  --cookie-name=$JPY_COOKIE_NAME \
  --base-url=$JPY_BASE_URL \
  --hub-prefix=$JPY_HUB_PREFIX \
  --hub-api-url=$JPY_HUB_API_URL \
  --NotebookApp.base_url=/user/$JPY_USER \
  ${notebook_arg} \
  $@

**Comment by minrk** [comment]
DockerSpawner no longer custom environment variables that make assumptions about the image's launch command. Instead, it uses standard env/cli args supported by `jupyterhub-singleuser`, so you don't need to build CLI args from env variables. You should be able to use just:

    exec python3 /srv/singleuser/singleuserapp.py $@

and the right env/cli args will be passed.

What exactly is `singleuserapp.py`?

**Comment by rydeng** [comment]
@minrk  thanks, so where can I set these standard env/cli args? I am confused

**Comment by minrk** [comment]
DockerSpawner takes care of it by building the command to launch and passing environment variables that `jupyterhub-singleuser` itself understands. You no longer have to add special code to relay arguments from DockerSpawner to the container. If you want to specify additional arguments, you can use the `c.DockerSpawner.environment` and `c.DockerSpawner.cmd` configurables to specify extra environment variables and command-line flags, beyond what will be passed by default.

**Comment by rydeng** [comment]
@minrk  thanks a lot
