### ISSUE TITLE
IP changes on jupyterhub server - Update spawned servers

### ISSUE THREAD

**Issue by beardbig** [jupyterhub/dockerspawner#204]
Hello
I have jupyterhub with dockerspawner and different containers already spawned. 
The IP of the jupyterhub server is changed but i'm not able to propagate this changes to the existing containers.

> Failed to connect to Hub API at 'http://192.168.1.98:8081/hub/api'.  Is the Hub accessible at this URL (from host: e659f6fafba4)?

The answer to the above question is No, the hub now is  accessible at "192.168.1.94".
New containers created after Ip changes works.
Existing containers continue to use the old IP also after a restart.

I tried to specify the IP as follow without success
> c.JupyterHub.hub_ip = '192.168.1.94'
> c.DockerSpawner.hub_ip_connect = '192.168.1.94'

If i check the log i can observe that the executed command continue to use the old Ip
> Execute the command: jupyterhub-singleuser --user="damiano" --cookie-name="jupyter-hub-token-damiano" --base-url="/user/damiano" --hub-host="" --hub-prefix="/hub/" --hub-api-url="http://192.168.1.98:8081/hub/api" --ip="0.0.0.0" --port=8888 --user="meeo" --cookie-name="jupyter-hub-token-meeo" --base-url="/user/meeo" --hub-host="" --hub-prefix="/hub/" --hub-api-url="http://192.168.1.98:8081/hub/api" --ip="0.0.0.0" --port=8888 --user="meeo" --cookie-name="jupyter-hub-token-meeo" --base-url="/user/meeo" --hub-host="" --hub-prefix="/hub/" --hub-api-url="http://192.168.1.98:8081/hub/api" --ip="0.0.0.0" --port=8888

Is it possible to fix this problem without removing and respawning the containers?

**Comment by minrk** [comment]
> Is it possible to fix this problem without removing and respawning the containers?

No, these values are set when the container is created. They cannot be changed without recreating the container. I think you have the right config now, but you you need to delete any containers that were started with the wrong values.

**Comment by beardbig** [comment]
OK, thanks
