### ISSUE TITLE
What if my Jupyter Notebook server is in a docker?

### ISSUE THREAD

**Issue by dclong** [jupyterhub/dockerspawner#210]
Does it mean that I'll have dockers in a docker? Will the performance be bad?

**Comment by davidbath** [comment]
Hi @dclong - you don't need to have docker-in-docker. I run it this way, but you do have to find a way to let the code in your `jupyterhub` container access the `dockerd` api on the host.

There are two main ways of doing that: either mount the `/var/run/docker.sock' from the host into the `jupyterhub` container, e.g.:

`docker run -d --name [jupyterhub-name] --network [network shared by jupyterhub and single-user containers] -v /var/run/docker.sock:/var/run/docker.sock [jupyterhub-image-name]`

Or you can enable the TCP (and/or TLS) API on the hosts `dockerd`, and then configure the parameters of DockerSpawner. You can read about enabling `dockerd` to listen to TCP over on the [dockerd documentation](https://docs.docker.com/engine/reference/commandline/dockerd/#examples).

Hope that helps - happy to share more of my config/dockerfile if you'd like.

**Comment by Hao6** [comment]
@davidbath Can you share your jupyterhub_config.py file?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

You can see a complete example of the hub running in docker as a sibling to single-user containers in the `examples/simple` directory  of this repo.
