### ISSUE TITLE
singleuser image broken with kubespawner 

### ISSUE THREAD

**Issue by brockpalen** [jupyterhub/dockerspawner#213]
I am using jupyterhub with kubespawner. (https://github.com/brockpalen/tf-jupyterhub/) On January 1 using juptyerhub/singleruser:0.8 everything worked  on the 5th it stopped working.  Looking on docker hub that container image was updated, but the version was not bumped.

The error is `sudo: jupyterhub-singleuser: command not found`

I am not setting `c.KubeSpawner.cmd`

Going into the container manually I am able to verify the following behavior is related to a change in `/usr/local/bin/start.sh`  where it changed from using su to sudo  (https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh).

Eg changing start.sh slightly to see what happens.  shell.sh is just echo $PATH

```
sudo -E -H -u jovyan PATH=$PATH /tmp/shell.sh 
/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

sudo -E -H -u jovyan PATH=$PATH jupyterhub-singleuser
sudo: jupyterhub-singleuser: command not found

ls -l /opt/conda/bin/jupyterhub-singleuser 
-rwxr-xr-x 1 jovyan users 104 Jan  3 17:41 /opt/conda/bin/jupyterhub-singleuser
```

It appears secure_path with sudo is getting in the way.  I have not verified this.

If you pull `jupyterhub/singleuser:0.9`  which has not been updated in a few months everything still works.

**Comment by brockpalen** [comment]
This appears related to https://github.com/jupyter/docker-stacks/pull/509  which introduced issues with `sudo` being passed.  The fix is to add to your config

`c.KubeSpawner.singleuser_uid=1000`

Which is the uid of the `jovyan`  user which is in the container by default, but `kubespawner`  appears to default to root.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

It looks like this issue is resolved and specific to how kubespawner starts containers. I believe it defaults to 1000 now as well. Feel free to open a new Issue on jupyterhub/kubespawner if you are still having this trouble.
