### ISSUE TITLE
how to config user's group id in docker 

### ISSUE THREAD

**Issue by forbxy** [jupyterhub/dockerspawner#218]
the default group id is 100,how config it ?

**Comment by forbxy** [comment]
I think i found，environment NB_GID set it

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

Yes, NB_GID is one way to set it if you are using the docker stacks, or for any container pass `group_add` to [host_config](https://docker-py.readthedocs.io/en/stable/api.html?highlight=gid#docker.api.container.ContainerApiMixin.create_host_config):

```python
c.DockerSpawner.extra_host_config = {"group_add": [100]}
```
