### ISSUE TITLE
ERR_NETWORK_CHANGED Chrome Error 

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/dockerspawner#223]
## Problem

Chrome shows `ERR_NETWORK_CHANGED` after login.

## How to reproduce:

* Versions: Use JupyterHub (**version 0.9.0dev** or 0.8.1) behind Proxy (nginx), as well **dockerspawner** in either version `0.9.1` or `0.8.0` (those were tested).
* It is important to use the hub behind proxy, as the error does not produce with clean jupyterhub and dockerspawner only.
* Proxy configuration is 1:1 to the one in `readthedocs` official documentation: (http://jupyterhub.readthedocs.io/en/latest/reference/config-examples.html?highlight=nginx)

## What else was tested

* tried with various docker images --> no change in error behaviour
* minimalistic jhub config: only Spawner class was changed
* deactivating http2 in nginx
* tested removing the header fields: `X-Forwarded-For`, `Upgrade`, `Connection`

### JupyterHub config:

```
# tell jupyterhub where the spawner class is, which it will use to spawn notebook servers
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'

# locations of certificates
c.JupyterHub.ssl_key = '/jh1.key'
c.JupyterHub.ssl_cert = '/jh1.cert'
c.JupyterHub.hub_port = os.getenv('JUPYTERHUB_PORT', 8080)
```

_The issue was also posted in the jupyterhub repo_: https://github.com/jupyterhub/jupyterhub/issues/1495

**Comment by katsar0v** [comment]
Any updates on the issue? Still there seems to be no solution

**Comment by sabuhish** [comment]
I am still facing the same issue almost 2 weeks, pages are stopping refreshings itself. I get an error saying.

Your connection was interrupted A network change was detected. ERR_NETWORK_CHANGEDYour connection was interrupted A network change was detected.

Before I used run docker containers, I feel like messed up with images and containers.. i am not able to fix this issue.. anyone has solved so far? Can you help me out?

**Comment by katsar0v** [comment]
What I noticed: whenever there is a docker network change it is being noticed by chrome and there is "ERR_NETWORK_CHANGED". This does not happen in Firefox though.

**Comment by sabuhish** [comment]
![Screenshot from 2019-05-16 12-06-35](https://user-images.githubusercontent.com/46589585/57837085-183d8300-77d3-11e9-9dae-3cb10bee5991.png)

and mainly i cant stop docker network as well it keeps giving me an error. I am not able to handle with these problme, Choreme stucks sometimes, I cant trust it anymore.

**Comment by katsar0v** [comment]
Disabling ipv6 in Linux works for now

**Comment by minrk** [comment]
Closing according to duplicate discussion on jupyterhub: https://github.com/jupyterhub/jupyterhub/issues/1495#issuecomment-502633790

**Comment by ctrlcctrlv** [comment]
I cannot just disable IPv6. I need IPv6.
