### ISSUE TITLE
How to mount directory from host

### ISSUE THREAD

**Issue by Gr1N** [jupyterhub/dockerspawner#226]
Hi,

I'm stuck with mounting... I would like to mount a directory from JupyterHub server to all notebooks servers spawned using Docker. Here is my code:
```
class MySpawner(dockerspawner.DockerSpawner):

    @property
    def volume_mount_points(self):
        mount_points = super().volume_mount_points
        mount_points.append('/envs')
        return mount_points

    @property
    def volume_binds(self):
        volumes = super().volume_binds
        volumes['/envs'] = {
            'bind': '/home/jovyan/envs',
            'mode': 'ro',
        }
        return volumes
```

I got only empty directory at `/home/jovyan/envs`.

Best regards.

**Comment by Gr1N** [comment]
Oh... Found my issue, need to specify mount point from host machine, not from JupyterHub container...

**Comment by sglyon** [comment]
Hey @Gr1N  Can you elaborate and perhaps post a working code snippet? Thanks!

**Comment by Gr1N** [comment]
@sglyon enjoy, just add following in your `jupyterhub_config.py`:
```
c.DockerSpawner.volumes = {
    '/path/on/host': '/path/in/container'
}
```
Just remember, you need to define full path for the host machine.

**Comment by FukoH** [comment]
where is the directory in such deployment,say` jupyterhub-user-{username}`

`
notebook_dir ='/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }
`
@Gr1N
