### ISSUE TITLE
ENH,DOC: How to use with gVisor?

### ISSUE THREAD

**Issue by westurner** [jupyterhub/dockerspawner#237]
Is there a configuration setting to add the appropriate docker CLI args to use gVisor for additional container isolation?

https://github.com/google/gvisor
https://github.com/google/gvisor#why-does-gvisor-exist

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

The equivalent of `docker run --runtime=runsc` from [here](https://gvisor.dev/docs/user_guide/quick_start/docker/) in DockerSpawner is to pass `runtime` to [create_container](https://docker-py.readthedocs.io/en/stable/api.html?highlight=runtime#docker.api.container.ContainerApiMixin.create_container) via `extra_create_kwargs`:

```python
c.DockerSpawner.extra_create_kwargs = {"runtime": "runsc"}
```

In general, `c.DockerSpawner.extra_create_kwargs` and `c.DockerSpawner.extra_host_config` passthrough anything to docker's own [create_container](https://docker-py.readthedocs.io/en/stable/api.html?highlight=runtime#docker.api.container.ContainerApiMixin.create_container) and [create_host_config](https://docker-py.readthedocs.io/en/stable/api.html?highlight=runtime#docker.api.container.ContainerApiMixin.create_host_config) functions.

**Comment by westurner** [comment]
https://gvisor.dev/docs/user_guide/quick_start/docker/
