### ISSUE TITLE
Mount different volumes based on userlist/group

### ISSUE THREAD

**Issue by xmatthias** [jupyterhub/dockerspawner#239]
Is it possible to mount different images based on the username/group (provided by ldapauthenticator in my case).

I currently have a config as follows, but would need a 4th (shared) volume for a selected group of users.

``` python
c.DockerSpawner.volumes = {
                       'jupyterhub-userhome-{username}': { 'bind': notebook_dir , 'mode': 'rw'},
                       'jupyterhub-user-{username}': { 'bind': notebook_dir + 'work/' , 'mode': 'rw'},
                       'juypterhub-shared-data': { 'bind': '/home/jovyan/work/shared-ro', 'mode': 'ro'},
}
```

I wouldn't mind to hardcode these users in the config as they almost never change.

I tried using a dict using templating to select the correct value - but it seems that templating does not apply here and jupyterhub fails to start.

``` python
volumedict = {'superuser': {
                        'jupyterhub-userhome-{username}': { 'bind': notebook_dir , 'mode': 'rw'},
                        'jupyterhub-user-{username}': { 'bind': notebook_dir + 'work/' , 'mode': 'rw'},
                        'juypterhub-shared-data': { 'bind': '/home/jovyan/work/shared-ro', 'mode': 'ro'},
                        'jupyterhub_test_mount': { 'bind': '/home/jovyan/test', 'mode': 'rw'},

                },
              'other': {
                        'jupyterhub-userhome-{username}': { 'bind': notebook_dir , 'mode': 'rw'},
                        'jupyterhub-user-{username}': { 'bind': notebook_dir + 'work/' , 'mode': 'rw'},
                        'juypterhub-shared-data': { 'bind': '/home/jovyan/work/shared-ro', 'mode': 'ro'},
                        }
                }
c.DockerSpawner.volumes = volumedict['{% "superuser" if username == "xmatthias" else "other"%}']
```

**Comment by cmseal** [comment]
Hi @xmatthias - did you get anywhere with this? I want to do something similar for our 'admins' in the jupyterhub_config.py, so that the 'juypterhub-shared-data' is rw, but for others is ro.

Cheers!

**Comment by xmatthias** [comment]
no, unfortunately not - all i got on this is in this page. 
I also didn't follow this very closely - but would still require this.

one very dirty workaround might be to run a 2nd instance of jupyterhub on a separate port for admins using the same volumes - but that's a very hacky approach...

**Comment by cmseal** [comment]
@xmatthias take a look at this... #172 

My python isn't great, but it might assist you.  I'm hoping one of users on that post may be able to clarify to assist me too.

**Comment by cmseal** [comment]
@xmatthias this now works for me.  Hope it helps you!

```
from dockerspawner import DockerSpawner
class MyDockerSpawner(DockerSpawner):
    team_map = {
        'username1': 'team-a',
        'username2': 'team-b',
        'username3': 'team-a',
    }

    def start(self):
        if self.user.name in self.team_map:
            team = self.team_map[self.user.name]
            # add team volume to volumes
            self.volumes['/directory/jupyterhub-team-{}'.format(team)] = {
                'bind': '/home/jovyan/teamfolder',
                'mode': 'rw',  # or ro for read-only
            }
        return super().start()

c.JupyterHub.spawner_class = MyDockerSpawner
```

**Comment by jameholme** [comment]
@cmseal how do I use your above config without using groups/teams? I want a shared folder for all users to muck around in

**Comment by xmatthias** [comment]
well you can always add `self.volumes['/sampleshareddir] = {'bind': '/home/jovyan/shareddir', 'mode': 'rw', }` above the `if` statement, so every team get's "it's" own folder - + one shared folder for everyone

**Comment by cmseal** [comment]
@jameholme If you just want a single shared folder that all users have read/write access to, you could add this to your ```jupyterhub_config.py```:
```
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}':'/home/jovyan/work', 'jupyterhub-shared':'/home/jovyan/shared', }
```
This assumes you already have ```'jupyterhub-user-{username}':'/home/jovyan/work',``` as a docker volume per user... if not, just omit that bit.

Note: depending on your setup, you may have to create the ```jupyterhub-shared``` volume from the docker cli before it can be used, and I've also previously had to manually set file permissions inside the volume before users could actually write to it.  Again, this may depend on your setup and configuration. Hope this helps!

**Comment by jameholme** [comment]
> Note: depending on your setup, you may have to create the jupyterhub-shared volume from the docker cli before it can be used, and I've also previously had to manually set file permissions inside the volume before users could actually write to it. Again, this may depend on your setup and configuration. Hope this helps!

How do I ensure this is done properly? I have added the line you suggested, but I'm only seeing 'Work' still

I've created the docker volume, 'jupyterhub-shared', how do I manually set the file permissions like you had to?

**Comment by cmseal** [comment]
@jameholme if you're not seeing it, it's probably because it's an existing container.  I've seen this in dev environments. I'd suggest seeing if a new user who first logs in sees the new folder and if they can write to it before proceeding.

If they can, you may need to delete your container and let it be recreated from your chosen image when you attempt to login again.  Ensure you've got a copy of all your data separately before doing this to be sure!

**Comment by jameholme** [comment]
@cmseal thanks! good call, i logged in as a different user and noticed i saw a work and shared in the terminal (but not in the panel). i tried create a test file using touch and it was permission denied.

**Comment by nuraym** [comment]
I am trying to achieve a shared directory for all users. I created a shared-file folder in my Jupyterhub. 
Added this to my jupyterhub_config.py 
I am launching JupyterHub from myt erminal locally using `jupyterhub -f jupyterhub_config.py` 
What am I missing?

`notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/jupyter'
c.DockerSpawner.notebook_dir = notebook_dir
c.DockerSpawner.volumes = {
   'jupyterhub-user-{username}': notebook_dir,
   'shared-data/volumes': '/home/jovyan/shared'
`}

**Comment by cmseal** [comment]
If the user's docker containers already exist, I don't believe they'll see the additional volume, and only newly created user containers will see it. Try accessing JupyterHub as a brand new user that hasn't accessed it before.

Likewise, I'm not sure if you can have the ```/``` in the volume name ```'shared-data/volumes'```, and if docker does allow it, whether or not it will cause issues with JupyterHub.  You will also need to create the shared volume manually using docker, likely before restarting JupyterHub.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/dockerspawner-mounting-shared-folder-files-missing-after-host-updated/7688/1

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

It looks like this issue is resolved. Thank you all for great examples and discussion!
