### ISSUE TITLE
What authenticator to use when JupyterHub is running in Docker with SystemUserSpawner?

### ISSUE THREAD

**Issue by zoltan-fedor** [jupyterhub/dockerspawner#240]
I am trying to setup JupyterHub in Docker with `SystemUserSpawner` so it uses the authentication of the host linux.
Basically I have normal linux users define on the host and I would like to authenticate them into JupyterHub running in the Docker container (and then it would spawn in Docker).
I can't figure out what authenticator to use.

I assume it would be `jupyterhub.auth.LocalAuthenticator`, but how to use that with `SystemUserSpawner`?

**Comment by zoltan-fedor** [comment]
I have managed to solve this.

1. The `LocalAuthenticator` does not work, but the `PAMAuthenticator` does (see https://stackoverflow.com/questions/48071985/jupyterhub-localauthenticator-does-not-work
2. I need to mount (or copy) the` /etc/passwd` `/etc/shadow` and `/etc/group` from the host to the JupyterHub container (see https://github.com/jupyterhub/jupyterhub/issues/535)

After this JupyterHub in a Docker container can use the system users of the linux host.

**Comment by ridwanoabdulazeez** [comment]
@zoltan-fedor  I  am trying to setup  the kind of your environment. Users of the host system were able to authenticate using PAM but they get error 500 after a successful login. I thing the problem is spawner error.  Could you give any insight on how you configured your  SystemUserSpawner

**Comment by zoltan-fedor** [comment]
@ridwanoabdulazeez You will need to look into the logs to see what is the actual issue. Trying to solve a 500 error without looking at the error log behind it is pretty much hopeless.

**Comment by ridwanoabdulazeez** [comment]
@zoltan-fedor  Thanks for your prompt response. I checked the log and noticed the users home directory  permissions and ownership changes inside the docker container after bind-mounting. do you encounter this problem? if yes, how did you solve it?

**Comment by zoltan-fedor** [comment]
@ridwanoabdulazeez No, I didn't run into that problem. If you have mounted or copied the /etc/passwd /etc/shadow and /etc/group files into the docker container, then the user id inside it should match the one on the host, so that should not change the ownership.
You will need to investigate what is changing the home directory permissions.

**Comment by ridwanoabdulazeez** [comment]
Thanks @zoltan-fedor  the permissions are changing because Users are not added to the docker group on the host system

**Comment by zoltan-fedor** [comment]
I don't quite see why would that see the directory permissions of the user's home, but I am sure you have tested it.
I don't have my users added to the docker group and I don't have this problem.
