### ISSUE TITLE
Example image from documentation fails with 'Running as root is not recommended'

### ISSUE THREAD

**Issue by zoltan-fedor** [jupyterhub/dockerspawner#241]
When using the "minimal JupyterHub user image" from the README (see Dockerfile below), then it fails to start with `Running as root is not recommended. Use --allow-root to bypass.` error.

I have tried to create a custom image based on the documentation:
```
FROM python:3.6
RUN pip3 install \
    jupyterhub==0.7.2 \
    'notebook>=5.0,<=6.0'

# create a user, since we don't want to run as root
RUN useradd -m jovyan
ENV HOME=/home/jovyan
WORKDIR $HOME
USER jovyan

CMD ["jupyterhub-singleuser"]
```

**Comment by zoltan-fedor** [comment]
It seems the documentation is wrong, as the custom image also requires an entrypoint to avoid the `Running as root is not recommended. Use --allow-root to bypass.` error:

```
...
WORKDIR $HOME
USER jovyan

ENTRYPOINT ["tini", "-g", "--"]
CMD ["jupyterhub-singleuser"]
```

Once the ENTRYPOINT is added, the above error goes way, but now there is a new error:
`Error: Failed to get port info for ccaee...`

It seems now it cannot pick up the port of the container for some reason, while the network settings seems to be identical to other, working containers.

**Comment by zoltan-fedor** [comment]
I have realized why that example custom image does not work for me - because I am using the `SystemUserSpawner` and not the `DockerSpawner`.

Are there any working example for building custom images for the `SystemUserSpawner`?

**Comment by Energy23** [comment]
I'm using SystenUserSpawner too.
My Dockerfile looks like

```
## Created by andyg
FROM jupyter/scipy-notebook:latest

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN cd /srv && \
    mkdir nbgrader && \
    cd nbgrader && \
    mkdir exchange && \
    chmod ugo+rw /srv/nbgrader/exchange
USER $NB_UID
# Update conda
RUN conda update -n base conda
# Install NBPresent
RUN conda install -c conda-forge nbpresent
# Install Tensorflow
RUN conda install --quiet --yes \
    'tensorflow=1.5*' \
    'keras=2.1*' && \
    conda clean -tipsy && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
RUN npm cache clean --force && \
    rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
    rm -rf /home/$NB_USER/.cache/yarn && \
    rm -rf /home/$NB_USER/.node-gyp && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

```
Maybe you have to add something like
```
USER $NB_UID

# Setup work directory for backward-compatibility
RUN mkdir /home/$NB_USER/work && \
    fix-permissions /home/$NB_USER

```
Maybe fix-permissions should do the job

**Comment by zoltan-fedor** [comment]
Thanks, yes I ended up replicating everything what is done by the base notebook of the docker-stacks
https://github.com/jupyter/docker-stacks/tree/master/base-notebook, including the fix-permissions.

I was doing all this on a CentOS-based docker image, so I had to make a few modifications to it to work.
