### ISSUE TITLE
 Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

### ISSUE THREAD

**Issue by bhagyashreek24** [jupyterhub/dockerspawner#243]
Hi @minrk  I was trying to install jupyterhub using docker container on EC2 instance but came across the following error:

[I 2018-07-12 13:25:40.772 JupyterHub app:1667] Using Authenticator: oauthenticator.github.GitHubOAuthenticator-0.7.3
[I 2018-07-12 13:25:40.772 JupyterHub app:1667] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-0.9.1
[I 2018-07-12 13:25:40.776 JupyterHub app:1053] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2018-07-12 13:25:40.798 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-07-12 13:25:40.799 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-07-12 13:25:40.808 alembic.runtime.migration migration:327] Running stamp_revision  -> 896818069c98
[I 2018-07-12 13:25:40.884 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2018-07-12 13:25:40.939 JupyterHub app:1849] Hub API listening on http://*:8081/hub/
[I 2018-07-12 13:25:40.939 JupyterHub app:1851] Private Hub API connect url http://691ec25ba271:8081/hub/
[I 2018-07-12 13:25:40.941 JupyterHub proxy:554] Starting proxy @ http://:8000
13:25:41.373 - info: [ConfigProxy] Proxying https://*:8000 to (no default)
13:25:41.376 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2018-07-12 13:25:41.869 JupyterHub proxy:301] Checking routes
[I 2018-07-12 13:25:41.870 JupyterHub proxy:370] Adding default route for Hub: / => http://691ec25ba271:8081
13:25:41.871 - info: [ConfigProxy] 200 GET /api/routes 
13:25:41.874 - info: [ConfigProxy] Adding route / -> http://691ec25ba271:8081
[I 2018-07-12 13:25:41.876 JupyterHub app:1906] JupyterHub is now running at http://:8000
13:25:41.876 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-07-12 13:25:48.916 JupyterHub log:158] 302 GET / -> /hub (@::ffff:125.21.166.181) 1.35ms
[W 2018-07-12 13:25:50.087 JupyterHub base:242] Invalid or expired cookie token
[I 2018-07-12 13:25:50.088 JupyterHub log:158] 302 GET /hub -> /hub/ (@::ffff:125.21.166.181) 0.67ms
[W 2018-07-12 13:25:53.480 JupyterHub base:242] Invalid or expired cookie token
[I 2018-07-12 13:25:53.481 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@::ffff:125.21.166.181) 1.40ms
[I 2018-07-12 13:25:54.430 JupyterHub log:158] 200 GET /hub/login (@::ffff:125.21.166.181) 34.31ms
[I 2018-07-12 13:26:08.685 JupyterHub oauth2:82] OAuth redirect: 'https://54.199.151.52:8000/hub/oauth_callback'
[I 2018-07-12 13:26:08.688 JupyterHub log:158] 302 GET /hub/oauth_login?next= -> https://github.com/login/oauth/authorize?redirect_uri=https%3A%2F%2F54.199.151.52%3A8000%2Fhub%2Foauth_callback&client_id=058666ef2ea4330db55c&response_type=code&state=[secret] (@::ffff:125.21.166.181) 2.42ms
[I 2018-07-12 13:26:19.306 JupyterHub base:499] User logged in: bhagyashreek24
[I 2018-07-12 13:26:19.308 JupyterHub log:158] 302 GET /hub/oauth_callback?code=[secret]&state=[secret] -> /user/bhagyashreek24/ (@::ffff:125.21.166.181) 1191.31ms
[I 2018-07-12 13:26:20.735 JupyterHub log:158] 302 GET /user/bhagyashreek24/ -> /hub/user/bhagyashreek24/ (@::ffff:125.21.166.181) 1.24ms
[E 2018-07-12 13:26:21.861 JupyterHub user:474] Unhandled error starting bhagyashreek24's server: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[E 2018-07-12 13:26:21.869 JupyterHub user:483] Failed to cleanup bhagyashreek24's server that failed to start
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 479, in spawn
        await self.stop()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 546, in stop
        status = await spawner.poll()
      File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 421, in poll
        container = yield self.get_container()
      File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 447, in get_container
        'inspect_container', self.container_name
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 408, in _docker
        m = getattr(self.client, method)
      File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 62, in client
        client = docker.APIClient(**kwargs)
      File "/opt/conda/lib/python3.6/site-packages/docker/api/client.py", line 158, in __init__
        self._version = self._retrieve_server_version()
      File "/opt/conda/lib/python3.6/site-packages/docker/api/client.py", line 183, in _retrieve_server_version
        'Error while fetching server API version: {0}'.format(e)
    docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

I have created a derivate image of dockerfile from docker hub
My dockerfile looks like this:

FROM jupyterhub/jupyterhub

COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
COPY jupyterhub.key /srv/jupyterhub/jupyterhub.key
COPY jupyterhub.crt /srv/jupyterhub/jupyterhub.crt

RUN pip install oauthenticator
RUN pip install dockerspawner

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]

My jupyterhub_config.py file looks like this:

# Configuration file for jupyterhub.

c.JupyterHub.port=8000
c.JupyterHub.authenticator_class = 'oauthenticator.GitHubOAuthenticator'
c.GitHubOAuthenticator.oauth_callback_url = 'https://54.199.151.52:8000/hub/oauth_callback'
c.GitHubOAuthenticator.client_id = '058666ef2ea4330db55c'
c.GitHubOAuthenticator.client_secret = '93a9b6243bf7d2fd5253044f544eb12229be5276'

# This is an application.

# create system users that don't exist yet
c.LocalAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'bhagyashreek24'}
c.Authenticator.admin_users = {'bhagyashreek24'}
c.JupyterHub.ssl_cert = 'jupyterhub.crt'
c.JupyterHub.ssl_key = 'jupyterhub.key'
#c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub_cookie_secret'
#c.JupyterHub.proxy_cmd = ['/usr/local/bin/configurable-http-proxy']
c.JupyterHub.hub_ip = ''

# Let the Systemctl aware of all the environment path

from dockerspawner import DockerSpawner
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
#DockerSpawner.container_image = 'jupyterhub/singleuser'

#------------------------------------------------------------
# Application(SingletonConfigurable) configuration
#------------------------------------------------------------------------------

## This is an application.

Please help me..

**Comment by sangramga** [comment]
@bhagyashreek24 have you installed Docker in your system. Please mention its version.

**Comment by bhagyashreek24** [comment]
@sangramga  also if u can enlighten on launching jupyterhub in distributed mode, it will be a great help for me.

**Comment by sangramga** [comment]
@bhagyashreek24 I think your are not launching jupyterhub conatiner properly. You should mount the docker.sock file from host VM to container. So, that the jupyterhub container can Spawn single user Notebook containers on the host.

``docker run -v /var/run/docker.sock:/var/run/docker.sock -p 8000:8000 my_jupyterhub``

**Comment by bhagyashreek24** [comment]
@sangramga this has helped to move forward from where i was stucked. But the again i got stucked to the below error:
[I 2018-07-18 12:26:36.087 JupyterHub dockerspawner:557] Starting container 'jupyter-bhagyashreek24' (id: eb4bc7e)
[W 2018-07-18 12:26:45.994 JupyterHub base:699] User bhagyashreek24 is slow to become responsive (timeout=10)
It would be helpful if you can guide me

**Comment by sangramga** [comment]
@bhagyashreek24 ``User bhagyashreek24 is slow to become responsive (timeout=10)``
is a totally different issue. Please search for the solutions on stackoverflow, and close this issue if you are satisfied (with my earlier response to the issue of  ``FileNotFoundError(2, 'No such file or directory')``)

**Comment by kerbrose** [comment]
well, I have to mention this answer
https://stackoverflow.com/a/64953813/7045119

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

It looks like this issue is resolved. Feel free to open a new Issue if you are still having this trouble.

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.
