### ISSUE TITLE
SwarmSpawner Persistence of user notebook directories error

### ISSUE THREAD

**Issue by ivanjz93** [jupyterhub/dockerspawner#248]
I use add the lines below in jupyterhub_config.py:

`notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }`

It is use to persist user notebook directories. And got an error:

> Incompatible options have been provided for the bind

**Comment by sangramga** [comment]
Try providing absolute path of local directory to persist notebooks.
Eg.
``c.DockerSpawner.volumes = { '/etc/jupyterhub_volumes/jupyterhub-user-{username}': notebook_dir}``

**Comment by belfhi** [comment]
@sangramga the guide by zonca uses the deprecated version of SwarmSpawner, so maybe not applicable here... Do you have any experience with NFS & SwarmSpawner or even just persistent storage? I also don't quite understand which source "/etc.jupyterhub_volumes" should be present. Any help would be appreciated. Cheers

**Comment by ivanjz93** [comment]
@belfhi You can use dockerspawner.SwarmSpawner and 'docker-volume-netshare' as nfs volume driver. Please refer https://github.com/ContainX/docker-volume-netshare

**Comment by zi-dan** [comment]
I spend a lot of time to resolve issue with not working volumes with SwamSpawner. Finally I resolved it by: 
- mounting NFS storage on each node,
- bind NFS volume to JupyterHub container
- create user volume on NFS storage by Spawner.pre_spawn_hook by following code snippets:

`def create_dir_hook(spawner):
    username = spawner.user.name  # get the username
    volume_path = os.path.join('/nfs/path/dir', username)
    if not os.path.exists(volume_path):
        os.mkdir(volume_path, 0o755)
    mounts_user = [
                   {'type': 'bind',
                    'source': '/nfs/path/dir/' + username,
                    'target': '/home/jovyan/work', }
                   ]
    spawner.extra_container_spec = {
        'mounts': mounts_user
    }

# attach the hook function to the spawner
c.Spawner.pre_spawn_hook = create_dir_hook`

I know it is workaround but is only way to attach user directory in SwarmSpawner mode.

**Comment by belfhi** [comment]
@ivanjz93 did you manage to get SwarmSpawner to work with the netshare plugin?
@zi-dan thanks for the info, will try that!

**Comment by ivanjz93** [comment]
> @ivanjz93 did you manage to get SwarmSpawner to work with the netshare plugin?
> @zi-dan thanks for the info, will try that!

The main steps of my code is familiar to @zi-dan's. The only differnece is I used netshare plugin.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/ip-error-while-trying-to-add-volume/6355/2

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

It looks like this issue is resolved. I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.
