### ISSUE TITLE
jupyterhub/singleuser:0.9.x

### ISSUE THREAD

**Issue by Spritekin** [jupyterhub/dockerspawner#254]
Hi,
We are trying to upgrade from Jupyterhub 0.8. We found JupyterHub 0.9.1 and 0.9.2 is available but no singleuser notebook.
In fact, we only can find DockerSpawner 0.9.1.
We've had problems trying to mix components together so is there any official singleuser notebook available for those versions?

Thanks!

**Comment by minrk** [comment]
There was a glitch in the auto-tagging of singleuser images for a bit. It should be fixed now, and there's a 0.9.2 and 0.9.1 image for `jupyterhub/singleuser`

But in general, any image from https://jupyter/docker-stacks should work fine with JupyterHub.
