### ISSUE TITLE
single user multiple containers?

### ISSUE THREAD

**Issue by Data-drone** [jupyterhub/dockerspawner#257]
can a single user get multiple containers?

I have a requirement for users to have access to multiple environments with sometimes clashing library versions to run comparisons

**Comment by minrk** [comment]
You can use the options_form to allow users to pick from a collection of docker images

**Comment by zeehio** [comment]
This feature (allowing a single user simultaneously have servers with multiple containers) requires multiple pieces:

- The jupyterhub part has been implemented at https://github.com/jupyterhub/jupyterhub/issues/766 and it can enabled with `c.JupyterHub.allow_named_servers=True`.
- When that setting is enabled, `/hub/home` allows you to create new servers with different spawner options (different images).
- However I guess dockerspawner does not implement its part yet. Only one container is created and a 404 error is obtained when I try to access other servers.

**Comment by zeehio** [comment]
It works!

```
c.JupyterHub.allow_named_servers=True
c.SystemUserSpawner.name_template = '{prefix}-{username}-{servername}'
```

The default `name_template` is bad for a multiple named servers configuration.
