### ISSUE TITLE
docker spawner to access hub on local machine

### ISSUE THREAD

**Issue by farzadz** [jupyterhub/dockerspawner#261]
According to [Min's workshop](https://www.youtube.com/watch?v=gSVvxOchT8Y) I thought it might be good to install jupyterhub on my local machine and use docker spawner for single user servers. The problem is that the singleuser server cannot access hub as it is inside the container and returns 500 error code:
```Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.  Is the Hub accessible at this URL (from host: 629e66de64a1)?  Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the Hub.```
Any suggestions for making it work without swarm/compose?

**Comment by dtaniwaki** [comment]
I think this PR will help.
https://github.com/jupyterhub/jupyterhub/pull/3326

**Comment by minrk** [comment]
The Hub listens on localhost by default. this isn't available to containers, so you need to make sure the hub is listening and connectable from the containers.

My preferred way to do this is to tell the Hub to listen on the docker virtual network, chosen by its device name:

```python
import netifaces
device = 'docker0'
c.JupyterHub.hub_ip = netifaces.ifaddresses(device)[netifaces.AF_INET][0]['addr']
```

The device name can vary. For my linux machine it is `docker0`, for my mac it is `en0`. You can check the output of `ip -4 addr` or `ifconfig` for available network devices.

The other option is to listen on all interfaces and set `hub_connect_url` to something that the containers can see (e.g. using the same ip found with netifaces above, or a hostname that will resolve inside the containers). I like the "just on the docker vnet" version best, though.
