### ISSUE TITLE
Sharing an additional port from user container to hub

### ISSUE THREAD

**Issue by TiemenSch** [jupyterhub/dockerspawner#275]
Is it possible to open up more ports between the hub and the user-container? I'm confused by the different (deprecated) commands/config options that all sound applicable.

My singleuser image has another port exposed in the Dockerfile (9999) and I would like to share that similar to the default 8888 one.

Edit: 
This question concerns a jupyterhub-deploy-docker deployment! Forgot to add that after a day of trial and error.

**Comment by TiemenSch** [comment]
In the end I solved it using:

```python
import dockerspawner

c = get_config()

class DockerSpawner(dockerspawner.DockerSpawner):
    def create_object(self):
        self.extra_create_kwargs["ports"] = {
            "%i/tcp" % self.port: None,
            "%i/tcp" % 9999: None,
        }
        self.extra_host_config["port_bindings"] = {
            self.port: (self.host_ip,),
            9999: (self.host_ip,),
        }
        return super().create_object()

c.JupyterHub.spawner_class = DockerSpawner
```

**Comment by TiemenSch** [comment]
I ended up using this plugin: https://github.com/jupyterhub/nbserverproxy !

**Comment by datachannel** [comment]
Thanks @TiemenSch.

**Comment by anderoonies** [comment]
hey @TiemenSch — wondering if you can give any further advice on how you got this running.
i'm running ServerProxy, with this config:
```py
c.ServerProxy.servers = {
    'graphics': {
        'command': ['websockify', '1234', ':5900'],
        'absolute_url': False
    }
}
```

and i've subclassed the DockerSpawner like this, to bind ports:
```py
class MyDockerSpawner(DockerSpawner):
    def create_object(self):
        self.extra_create_kwargs["ports"] = {
            "%i/tcp" % self.port: None,
            "%i/tcp" % 1234: None,
        }
        self.extra_host_config["port_bindings"] = {
            self.port: (self.host_ip,),
            1234: (self.host_ip,),
        }
        return super().create_object()

    def get_args(self):
        # runs the node user server as process 0 in the container
        return ['/app/start.sh', self.user.name]
```

however, i'm unable to proxy to the server using `hub.com/user/<user_id>/graphics`.
any advice? thanks for hopping back in here :)

**Comment by nmvega** [comment]
> I ended up using this plugin: https://github.com/jupyterhub/nbserverproxy !

Hi @TiemenSch 

Did you use this second approach (i.e. `nbserverproxy`) to replace the method in your first response? (Meaning, did you stop using that code-snippet and start using `nbserverproxy` instead)?

**If yes, I have follow-up question**:

I have the same need as you did, to expose additional port(s) in the `user-container`. Where does one actually install and implement `nbserverproxy`? Inside the `Dockerfile` of the `user-container` or on the `Hub` or `both`? 

I'm reading the documentation now and it's a bit unclear so far. Thank you for your help!
