### ISSUE TITLE
Swarmspawner : spawn different size container

### ISSUE THREAD

**Issue by TeddyH** [jupyterhub/dockerspawner#277]
Hi, I made Swarm mode cluster.
I want to know if I can spawn different sized container for some user.

for example,
- usergroup A(user a, user b, user c) :  1 core 1G mem 
- usergroup B(user d, user e, user f) : 4 core 8G mem

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

It's possible, but not quite with pure configuration. You will need to subclass SwarmSpawner to make mem_limit, mem_guarantee functions of the username. For example:

```python

# usergroup A(user a, user b, user c) : 1 core 1G mem
# usergroup B(user d, user e, user f) : 4 core 8G mem

# group_overrides are dicts of any attributes that should be overridden from the default config
group_overrides = {
    "A": {
        "mem_limit": "1G",
        "mem_guarantee": "1G",
        "cpu_limit": 1,
        "cpu_guarantee": 1,
    },
    "B": {
        "mem_limit": "8G",
        "mem_guarantee": "8G",
        "cpu_limit": 4,
        "cpu_guarantee": 4,
    },
}

# put users in groups
groups = {
    "A": ["a", "b", "c"],
    "B": ["d", "e", "f"],
}

# reverse groups, so keys are users values are groups
user_groups = {}
for group, users in groups.items():
    for user in users:
        user_groups[user] = group

from dockerspawner.swarmspawner import SwarmSpawner

class MySpawner(SwarmSpawner):
    def start(self):
        group = user_groups.get(self.user.name)
        overrides = group_overrides.get(group, {})
        for attr, value in overrides.items():
            setattr(self, attr, value)
        return super().start()

c.JupyterHub.spawner_class = MySpawner
```

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.
