### ISSUE TITLE
Specify user in image

### ISSUE THREAD

**Issue by NonaryR** [jupyterhub/dockerspawner#281]
I'm using [this image](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile) and replace [user](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L10) on my name, then build this image and pass it into `c.DockerSpawner.image` in `jupyterhub_config.py`. After building hub and run it, I can log but then errors occur without any specific logs 
```
500 GET /hub/user/name/tree (::ffff:10.99.70.68): Spawner failed to start [status=ExitCode=1, Error='', FinishedAt=2018-12-08T12:02:15.388989416Z]. The logs for name may contain details.
```
But `/var/logs/jupyter.log` is the same
Q: How can I specify a user for running his own image with all grants?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

> /var/logs/jupyter.log is the same

It's asking for logs from the container:

    docker logs jupyter-name

which should hopefully provide a more useful error.

> How can I specify a user for running his own image with all grants?

I'm not quite sure what "all grants" means, but perhaps SystemUserSpawner is what you want? This maps users in containers to users on the host system and mounts home directories, etc.
