### ISSUE TITLE
Minimal custom image does not spawn

### ISSUE THREAD

**Issue by marketneutral** [jupyterhub/dockerspawner#283]
I am trying to create a custom image to use with `SystemUserSpawner`. I am trying the minimal example from [here](https://github.com/jupyterhub/dockerspawner/#picking-or-building-a-docker-image):

```
FROM python:3.6
RUN pip3 install \
    jupyterhub==0.7.2 \
    'notebook>=5.0,<=6.0'

# create a user, since we don't want to run as root
RUN useradd -m jovyan
ENV HOME=/home/jovyan
WORKDIR $HOME
USER jovyan

CMD ["jupyterhub-singleuser"]
```

when I try to spawn this image, I get:
```
[I 2019-01-14 13:38:01.223 JupyterHub dockerspawner:829] Starting container jupyter-jlarkin (id: 9180675)
[I 2019-01-14 13:38:02.242 JupyterHub log:158] 200 GET /hub/api (@172.17.0.2) 0.53ms
[E 2019-01-14 13:38:11.145 JupyterHub pages:148] Failed to spawn single-user server with form
    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.7/site-packages/jupyterhub/handlers/pages.py", line 146, in post
        await self.spawn_single_user(user, options=options)
      File "/opt/anaconda/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 727, in spawn_single_user
        status, spawner._log_name))
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=ExitCode=1, Error='', FinishedAt=2019-01-14T18:38:02.331161355Z]. The logs for jlarkin may contain details.)
```

Do you have any advice on this? Where are the logs for this so I can investigate?

I can confirm that the absolute minimal Dockerfile `FROM jupyterhub/singleuser` does spawn.

I am trying to take an existing Dockerfile and add the absolute minimum to get it to work as a spawned image.

**Comment by minrk** [comment]
What are the logs from the container `jupyter-jlarkin`?

SystemUserSpawner relies on the image handling `$NB_USER` and `$NB_UID` environment variables during startup. The jupyter docker stacks does that (and more) [here](https://github.com/jupyter/docker-stacks/blob/87210526f381543ed76c2fba2857b1483e46bc12/base-notebook/start.sh#L42-L90).

The image is started as root, then the launch script is responsible to ensuring the $NB_USER account exists with uid $NB_UID, and then setting uid to $NB_UID and launching jupyterhub-singleuser.

**Comment by marketneutral** [comment]
`docker logs jupyter-jlarkin` gives

```
[I 2019-01-28 13:29:47.856 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
[C 2019-01-28 13:29:47.860 SingleUserNotebookApp notebookapp:1767] Running as root is not recommended. Use --allow-root to bypass.
```

Thanks for the comments on the $NB_UID. I'll work with that and see if I can get it to run.

**Comment by marketneutral** [comment]
My issue seems to be a duplicate of [268](https://github.com/jupyterhub/dockerspawner/issues/268) which is closed. I don't follow though the resolution there. Simply running `usermod -u $NB_UID $NB_USER` inside the Dockerfile does not fix the issue.

This issue also seems echoed in [240](https://github.com/jupyterhub/dockerspawner/issues/240). 

Is there a step-by step example of taking an existing Dockerfile and adding to it to make it run under SystemUserSpawner?

**Comment by marketneutral** [comment]
I wrote up the following in hopes of explaining my problem and question better:

I have some requirements for my JupyterHub setup that do not seem to be handled by [The Littlest JupyterHub]() or [Zero to JupyterHub with Kubernetes](), namely:

- The target number of users is 8-15 
- Runs on a single server (Linux insstance on AWS)
- The kernels need to spwan from Docker containers
- I will use PAM authentication against the users on the server
- User notebooks need to be persisted in the `/home/<username>` directory

I have everything working except the last point.

# The Current Working Setup

### 1. Install Anaconda
`root` installs anaconda3` in `/opt/anaconda`

### 2. Install JupyterHub
Install `jupyterhub` and `netifaces` via `conda`

### 3. Install Docker
Install Docker and makes `docker.service` run at startup.

### 4. Install dockerspawner
`pip install` the developement version of `dockerspawner`; `pip install git+https://github.com/jupyterhub/dockerspawner.git`

### 5. Configure JupyterHub
Make a `jupyterhub_config.py` and put it in `/srv/jupyterhub`

```python
# Configuration file for jupyterhub.

c.Authenticator.admin_users = {'jlarkin'}
c.PAMAuthenticator.open_sessions = False
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.remove_containers = True
c.DockerSpawner.image_whitelist = {
    'My Awesome Kernel': 'myawesomekernel',
    'My Awesome Kernel (dev)': 'myawesomekerneldev',
}
c.DockerSpawner.volumes = {
    '/srv/jupyterhub/home/{username}': '/home/jovyan/notebooks',
    '/srv/jupyterhub/home/shared': '/home/jovyan/shared'
}

# the Hub's API listens on localhost by default,
# but docker containers can't see that.
# Tell the Hub to listen on its docker network:
import netifaces
docker0 = netifaces.ifaddresses('docker0')
docker0_ipv4 = docker0[netifaces.AF_INET][0]
c.JupyterHub.hub_ip = docker0_ipv4['addr']
```


### 6. Make User Directories
Make user directories in `/srv/jupyterhub/home/<username>`; `chmod 777` on those directories. I also make a ``/srv/jupyterhub/home/shared` directory so that the users can share data, templates, etc.

### 7. Make Dockerfiles and Images
Make a Dockerfile(s) for my kernel image. For instance, I use the awesome core Kaggle-Python Dockerfile as my base data science image.

```
FROM gcr.io/kaggle-images/python

RUN pip3 install \
    jupyterhub==0.9.4 \
        'notebook>=5.0,<=6.0'

# create a user, since we don't want to run as root
RUN useradd -m jovyan
ENV HOME=/home/jovyan
WORKDIR $HOME
USER jovyan

CMD ["jupyterhub-singleuser"]
```

I make image with `docker build -t myawesomekernel .`


### 8. Run it!

`jupyterhub -f /srv/jupyterhub/jupyterhub_config.py --no-ssl --ip=<my.ip.add.ress>`.
I am running on a private VPN so I have not configured security. **This works!** I can login to JupyterHub; I can see a drop down with my kernels; I can spawn a server and get access to the kernel; the nb's are saved and persisted; the shared folder works.



# The Problem

That all works, however it's not ideal becuase the user notebooks are persisted in `/srv/jupyterhub/<username>` and not in the actual Linux user directories. When JupyterHub runs, the `user` is `jovyan`. If I launch a Terminal and do `id` I get:

```
uid=1000(jovyan) gid=1000(jovyan) groups=1000(jovyan)
```

When I `ssh` into the AWS instance and look in the user home directories (e.g., `/srv/jupytyerhub/home/jlarkin`) I see that the notebooks are created and owned by `ec2-user`, which is the AWS name for the root user; e.g., `ls -la` gives something like

```
-rw-r--r-- 1 ec2-user ec2-user  37206 Jan 18 10:10 pandas-multiindex.ipynb
```


I don't want this. I need the user to be able to `ssh` into the instance and work at the command line in their home directory and see the same files they see when accessing the JupyterHub notebook. 


# The Attemp to Fix

The above install uses `c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'`. The [`dockerspawner.SystemUserSpawner`](https://github.com/jupyterhub/dockerspawner#systemuserspawner) is specifically for the use case of using the actual Linux user directories. As such, I change my `jupyterhub_config.py` file to

```
--  c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
++  c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
```

Now I restart the JupyterHub server and login. All good. I go to spawn my server and I get an error in the GUI:

```
Error: HTTP 500: Internal Server Error (Spawner failed to start [status=ExitCode=1, Error='', FinishedAt=2019-01-30T17:45:20.503795982Z]. The logs for jlarkin may contain details.)
```

The error at the command line is

```
[E 2019-01-30 12:46:39.736 JupyterHub pages:148] Failed to spawn single-user server with form
    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.7/site-packages/jupyterhub/handlers/pages.py", line 146, in post
        await self.spawn_single_user(user, options=options)
      File "/opt/anaconda/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 727, in spawn_single_user
        status, spawner._log_name))
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=ExitCode=1, Error='', FinishedAt=2019-01-30T17:46:30.90390108Z]. The logs for jlarkin may contain details.)
```

I check the logs with `docker logs jupyter-jlarkin` and I see:

```
[I 2019-01-30 17:46:30.767 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
[C 2019-01-30 17:46:30.772 SingleUserNotebookApp notebookapp:1614] Running as root is not recommended. Use --allow-root to bypass.
```

This is where I am at a loss. It appears the issue is with user permissioning. For example, the `base-notebook` in the Jupyter `docker-stacks` runs an elaborate user permissioning [script](https://github.com/jupyter/docker-stacks/blob/6fa9a4a1f0e5c8b00825ed43dbefaf445118d650/base-notebook/start.sh) at startup. I've tried to replicate this in my Dockerfile with no luck. 

# The Question

My question is: *what are the absolute minimal additions I need to make to my Dockerfile above in **7** to get it to work with SystemUserSpawner`?*

Thanks for reading!

**Comment by minrk** [comment]
#412 makes the run-as-root requirement optional, and a bare image like this one should work.
