### ISSUE TITLE
Minimal Single-User Spawn Built on Nvidia / Tensorflow Container

### ISSUE THREAD

**Issue by ColinConwell** [jupyterhub/dockerspawner#284]
I am attempting to create as minimal a single-user spawner script as possible, making reference to 
 the minimal script provided as an example:
```
FROM python:3.6
RUN pip3 install \
    jupyterhub==0.7.2 \
    'notebook>=5.0,<=6.0'

RUN useradd -m jovyan
ENV HOME=/home/jovyan
WORKDIR $HOME
USER jovyan

CMD ["jupyterhub-singleuser"]
```

All I wish to change is the FROM statement, either using:

`FROM tensorflow/tensor:latest-gpu-jupyter 
`

or

`FROM ncvr.io/nvidia/tensorflow:18.12-py3. 
`

Both of these should have python3 installed.

Is this possible or do I need additional code?

**Comment by juultje123** [comment]
I just build the container by replacing python:3.6 with tensorflow/tensorflow:latest-gpu-py3.
The next step is building the docker container with: docker build . -t mytestcontainer
Then replace c.DockerSpawner.image = 'mytestcontainer'  in jupyterhub_config.py
And you should be good to go :)
