### ISSUE TITLE
Get Jupyterhub username in spawned container

### ISSUE THREAD

**Issue by MaxRichter** [jupyterhub/dockerspawner#286]
Hi,

I am using a Jupyterhub deployment with [DockerSpawner][1].
When I enter a spawned container, I have the following URL pattern: 

    https://<hostname>/user/<user-name>/lab?

  [1]: https://github.com/jupyterhub/dockerspawner
I would like to get the value of `<user-name>` within the spawned notebook container.
Is there any possibility to either access it or forward it from Jupyterhub into the container?

Thank you,
Max

**Comment by KeyboardWarriorTeddy** [comment]
user-name is stored at environment variable.
echo $JUPYTERHUB_USER
