### ISSUE TITLE
Run command post spawn / Provision second docker network

### ISSUE THREAD

**Issue by Blizzke** [jupyterhub/dockerspawner#292]
Our notebooks need a public IP but I also want to keep the connection to the docker network so that the hub functionality works. The solution we found is to spawn the container normally, but use `docker network connect` to provision a secondary interface. Currently this is done manually, but it would be nice if this could be automated. Is there a way to trigger a command/script after a new container has been spawned?

**Comment by minrk** [comment]
There is not a hook to do this via configuration, but you can always subclass and override `Spawner.start`, e.g.

```python
from dockerspawner import DockerSpawner

class MySpawner(DockerSpawner):
    async def start(self):
        result = await super().start()
        await self.docker("connect_container_to_network", self.container_id, "network_id")
        return result

c.JupyterHub.spawner_class = MySpawner
```

(this is calling [this docker api method](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.network.NetworkApiMixin.connect_container_to_network)
