### ISSUE TITLE
Centos7 Docker Image Fails to connect 

### ISSUE THREAD

**Issue by MikeMester** [jupyterhub/dockerspawner#303]
Hi Guys,
Trying to use a Centos7  image source as my jupyter notebook container and not having any luck.  I've followed all the documentation.  It appears the jupyterhub-single is starting but the hub isnt connecting.   

FROM centos:7

USER root
RUN yum install wget epel-release -y && yum install java-1.8.0-openjdk-headless python36-pip bzip2 ping net-tools vi -y
RUN python36 -m pip install --upgrade pip
RUN python36 -m pip install spark-sklearn
RUN python36 -m pip install pyspark
RUN python36 -m pip install notebook==5.7.0
RUN python36 -m pip install jupyterhub==1.0.0
COPY ./Anaconda3-2019.03-Linux-x86_64.sh /tmp/Anaconda.sh
RUN sh /tmp/Anaconda.sh -b -p /opt/anaconda
RUN rm /tmp/Anaconda.sh
EXPOSE 8888
RUN mkdir /work
WORKDIR /work
COPY ./hdp-select /usr/bin/hdp-select
COPY ./start_user.sh /sbin/start_user.sh
CMD ["/bin/bash","/sbin/start_user.sh"] 

relevant logs:
I 2019-05-07 16:52:06.998 SingleUserNotebookApp notebookapp:1712] The Jupyter Notebook is running at:
[I 2019-05-07 16:52:06.998 SingleUserNotebookApp notebookapp:1712] http://127.0.0.1:8888/user/mike/
[I 2019-05-07 16:52:06.998 SingleUserNotebookApp notebookapp:1713] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2019-05-07 16:52:06.999 SingleUserNotebookApp singleuser:542] Updating Hub with 
activity every 300 seconds

host:
Message: "mike's server never showed up at http://127.0.0.1:32796/user/mike/ after 30 seconds. Giving up"

been at this awhile now.  any help is appreciated.

start_user.sh
#/bin/bash
`/usr/sbin/useradd $JUPYTERHUB_USER -m -k -D`
mkdir /work_dir
chown -R $JUPYTERHUB_USER /work_dir
cd /work_dir
`runuser -u $JUPYTERHUB_USER jupyterhub-singleuser`

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time! I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant. The most important piece of missing information from this report is logs from the `jupyter-$username` container.
