### ISSUE TITLE
SwarmSpawner unable to reach containers with escaped characters

### ISSUE THREAD

**Issue by tmtabor** [jupyterhub/dockerspawner#305]
I am attempting to get a JupyterHub deploy set up and working with SwarmSpawner. It works... except for users who have a special character in their username.

I believe this is an issue in how SwarmSpawner is handling special characters.

When it encounters special characters it escapes them using an underscore. For example `tabor@cloud.ucsd.edu` becomes `tabor_40cloud_2Eucsd_2Eedu`. This is used in the name of the Docker service, which in turn is used in the hostname.

I have verified that the Docker service is being started. But then when JupyterHub tries to contact the single-user server at `http://jupyter-tabor_40cloud_2Eucsd_2Eedu:8888/user/tabor@cloud.ucsd.edu/` (or whatever the username with special characters may be), it times out with a `socket.gaierror: [Errno -2] "Name or service not known"` error.

I suspect that this is because underscores aren't a valid hostname character.

**Comment by minrk** [comment]
This will be fixed by #414
