### ISSUE TITLE
Is there a docker image to spawn a JupyterHub with a DockerSpawner ?

### ISSUE THREAD

**Issue by mdamien** [jupyterhub/dockerspawner#306]
To run JupyterHub, I use `docker run -d -p 8000:8000 --name jupyterhub jupyterhub/jupyterhub jupyterhub`, it would make sense for me to have a `jupyterhub/dockerspawner` image to have a basic JupyterHub+DockerSpawner version to try out. I'm on it but in case it doesn't exist yet, would love to know where :+1:

**Comment by minrk** [comment]
This does not exist, a custom image must be used currently.
