### ISSUE TITLE
Can't change UID and GID in spawning containers

### ISSUE THREAD

**Issue by m-alekseev** [jupyterhub/dockerspawner#312]
I am using SwarmSpawner and I can pass `NB_USER, NB_UID and NB_GID` via `spawner.environment = {}` into spawned containers but I can't then change container's parameters with those environment variables on spawn.

I've tried to pass those parameters in `.extra_container_spec, .extra_create_kwargs, .client_kwargs, .args and in .cmd` after specifying script to run. None of these helped. Maybe someone had this kind of problem?

Thank you

**Comment by IslamAlam** [comment]
did you find a solution for this?

**Comment by m-alekseev** [comment]
> did you find a solution for this?

Yes, to change those parameters you would need to add in a pre spawn function extra_container_spec parameter with value `'user': 0`, like this

```python
spawner.extra_container_spec = {
	'mounts': mounts,
	'user': '0',
}
```

Then you'll be able to change env parameters as you want, e.g.
```python
spawner.environment = {
	'JUPYTER_ENABLE_LAB': 'yes',
	'NB_USER': f'{username}',
	'NB_UID': int(uid),
	'NB_GID': int(gid),
}
```

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

It looks like this issue is resolved, thanks for posting your solution!
