### ISSUE TITLE
Using _user_set_cmd to override cmd in custom spawner

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/dockerspawner#317]
When defining a custom spawner that inherits from `DockerSpawner`, it looks like the `_user_set_cmd` flag needs to be set manually so `cmd` can be picked up. For example:

```python
class CustomSpawner(DockerSpawner):
    _user_set_cmd = True
    cmd = ['jupyterhub-singleuser']

...

c.JupyterHub.spawner_class = CustomSpawner
```

Without setting `_user_set_cmd` manually the `cmd` would default to the `CMD` from the Docker image.

Maybe there is a better way to make sure the custom command is picked up without using `_user_set_cmd`?

**Comment by minrk** [comment]
This should be fixed by #415
