### ISSUE TITLE
Default CMD parameters to a docker container

### ISSUE THREAD

**Issue by yakutovicha** [jupyterhub/dockerspawner#319]
For service that we provide we use [phusion base image](https://github.com/phusion/baseimage-docker) that requires CMD to be `CMD ["/sbin/my_init"]` (see [this link](https://github.com/phusion/baseimage-docker#getting-started)).

DockerSpawner that launches the container adds two default parameters to the CMD: `'--ip="0.0.0.0"', '--port=8888'`. Those parameters are not understood by `/sbin/my_init` script which causes image to fail starting. Can they be somehow removed?

I figured out that adding the following line to `jupyterhub_config.py`:
```
c.DockerSpawner.ip = '' # should be a string
```
removes `--ip` from the CMD args.

Similar trick with the port did NOT work:
```
c.DockerSpawner.port = 0 # should be an integer
```
The following exception was raised:
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("driver failed programming external
connectivity on endpoint ******************
(2568d4735ef1cd76e0200fdda04f7ce566e17a6c19537628fe8e4d2cb8e84b78):  (iptables failed:
iptables --wait -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 32975 -j DNAT --to-destination
172.17.0.2:0 ! -i docker0: iptables v1.6.0: Port `0' not valid
```

At the end I just added `args = []` right after [this line](https://github.com/jupyterhub/dockerspawner/blob/522a63fcc5706e9fce5ff759b6cccb9ae1afe312/dockerspawner/dockerspawner.py#L725) to temporary fix the problem.

* Is there a proper way to remove those parameters from the CMD?
* If not, should I make a PR that makes this as an option?

**Comment by yakutovicha** [comment]
The issue https://github.com/jupyterhub/dockerspawner/issues/317 seem to be related to that one.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

Overriding `get_args()` to return an empty list should be fine at this point because the `JUPYTERHUB_SERVICE_URL` env is enough for the subprocess already.

Passing `--ip` should be deprecated in JupyterHub: https://github.com/jupyterhub/jupyterhub/pull/3381

**Comment by minrk** [comment]
Removing these args causes more problems than I realized. So I think I'm going to say that it's part of DockerSpawner's spec that the entrypoint of an image must accept and relay command-line flags to the underlying notebook server (i.e. `jupyterhub-singleuser`).

Custom entrypoints should usually look like:

```bash
#!/bin/bash -l

export SETUP_ENV=1
exec jupyterhub-singleuser "$@"
```
