### ISSUE TITLE
Named servers in jupyterhub

### ISSUE THREAD

**Issue by mathematicalmichael** [jupyterhub/dockerspawner#320]
https://github.com/jupyterhub/jupyterhub/issues/2572

I have been unable to leverage named servers with dockerspawner due to naming conflicts with the container images. The hub tries to spawn multiple containers with the same name. Is there a way to reference the named server in expanding the name of the container (the way that username and hub currently can be).

**Comment by Redhappy** [comment]
I fixed this issue by setting the c.DockerSpawner.name_template inside the jupyterhub_config.py.

`c.DockerSpawner.name_template =  "{prefix}-{username}-{imagename}-{servername}"`.

The issue I am having now is that the Spawner is now creating a new container for each server/image combination, but when I delete the server, it won't delete the containers associated to the server.

**Comment by dmpe** [comment]
Should be included in the documentation....

**Comment by zeehio** [comment]
Fortunately, this is already under discussion. See: https://github.com/jupyterhub/dockerspawner/pull/315

Also, to remove containers when servers are deleted:

```
c.DockerSpawner.remove = True
```

**Comment by mathematicalmichael** [comment]
> I fixed this issue by setting the c.DockerSpawner.name_template inside the jupyterhub_config.py.
> 
> `c.DockerSpawner.name_template = "{prefix}-{username}-{imagename}-{servername}"`
> 
> The issue I am having now is that the Spawner is now creating a new container for each server/image combination, but when I delete the server, it won't delete the containers associated to the server.

this did it
