### ISSUE TITLE
Unstable startup time

### ISSUE THREAD

**Issue by fsksf** [jupyterhub/dockerspawner#325]
HI，
I'm using the official docker images `jupyterhub/singleuser`(Start  whit jupyterlab) and `jupyterhub/jupyterhub`, but the container startup time is unstable. I tried to find a relationship between container startup and CPU \men resource usage, but it didn't seem to matter much。

### Time start distribution
![20190722164306](https://user-images.githubusercontent.com/28781481/61619508-9a4d9a80-aca1-11e9-92a6-e80d77428dfc.jpg)
### start_time and cpu used
![time-cpu](https://user-images.githubusercontent.com/28781481/61619595-be10e080-aca1-11e9-8e0f-31a7079dac85.png)

Does anyone know how to optimize startup time？

thanks

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

There are lots of factors in startup time, from image pulls to poll intervals, to load in different areas. It can be hard to narrow it down without more precise timings of where the slow spawns are spending their time (could be queuing requests, for instance).
