### ISSUE TITLE
Workspace metadata ID mismatch

### ISSUE THREAD

**Issue by anmtan** [jupyterhub/dockerspawner#327]
After upgrading from 0.10.0 to 0.11.1. if username containers invalid characters (comma, spaces etc), the docker container logs will have workspace metadata ID mismatch. 

My goal is to use AzureAdOAuthenticator, and be able to mount container to host volume in order to persist data.

This is what I use in jupyterhub_config.py

from oauthenticator.azuread import AzureAdOAuthenticator
c.JupyterHub.authenticator_class = AzureAdOAuthenticator
c.Application.log_level = 'DEBUG'
c.AzureAdOAuthenticator.tenant_id = os.environ.get('AAD_TENANT_ID')
c.AzureAdOAuthenticator.oauth_callback_url = 'http://{your-domain}/hub/oauth_callback'
c.AzureAdOAuthenticator.client_id = '{AAD-APP-CLIENT-ID}'
c.AzureAdOAuthenticator.client_secret = '{AAD-APP-CLIENT-SECRET}'

notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir

c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }

When I use DummyAuthenticator, with username without comma or spaces, everything works fine. If I use Azure AD login, the username will be "lastname, firstname". Comma and space are invalid characters. In 0.10.0, it raises an exception on the comma and space in the username. Container would not be able to start. See logs below.

Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]: [E 2019-08-06 14:08:38.390 JupyterHub web:1670] Uncaught exception GET /hub/user/lastname%2C%20firstname/ (::ffff:10.7.2.171)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:     HTTPServerRequest(protocol='http', host='nonprod.gazelle.nielsen.com', method='GET', uri='/hub/user/lastname%2C%20firstname/', vers
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:     Traceback (most recent call last):
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         result = yield result
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 1052, in get
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         await self.spawn_single_user(user)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         await spawn_future
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         raise e
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 691, in sta
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         obj = yield self.create_object()
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 635, in cre
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         obj = yield self.docker("create_container", **create_kwargs)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/concurrent/futures/_base.py", line 425, in result
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         return self.__get_result()
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         raise self._exception
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         result = self.fn(*self.args, **self.kwargs)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 523, in _do
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         return m(*args, **kwargs)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/docker/api/container.py", line 411, in create_con
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         return self.create_container_from_config(config, name)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/docker/api/container.py", line 422, in create_con
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         return self._result(res, True)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/docker/api/client.py", line 235, in _result
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         self._raise_for_status(response)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_st
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         raise create_api_error_from_http_exception(e)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:       File "/srv/jupyterhub/jupyterhub/conda_env/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_f
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:         raise cls(e, response=response, explanation=explanation)
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:     docker.errors.APIError: 400 Client Error: Bad Request ("create jupyterhub-user-lastname, firstname: "jupyterhub-user-lastname, firstname" in
Aug 06 14:08:38 ip-10-254-96-80 jupyterhub[19717]:     

After upgrading to 0.11.1, it has a different error show below. I am suspecting because of the username mismatch between URL encoded username (lastname%2C%20firstname) by normalization and original username sent by Azure AD (lastname, firstname). 

Here is the docker container log. The docker container was able to start and running fine. Except seeing this error in the logs.

[W 2019-08-05 16:35:41.724 SingleUserNotebookApp web:1667] 400 PUT /user/lastname%2C%20firstname/lab/api/workspaces/user/lastname%2C%20firstname/lab?1565022941464 (::ffff:10.7.2.173): Workspace metadata ID mismatch: expected 'user/lastname, firstname/lab' got '/user/lastname%2C%20firstname/lab'
[W 2019-08-05 16:35:41.725 SingleUserNotebookApp handlers:568] Workspace metadata ID mismatch: expected 'user/lastname, firstname/lab' got '/user/lastname%%2C%%20firstname/lab'

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

I don't think this is a DockerSpawner issue. Rather, it should be a configuration issue for AzureAd - I think you want to change the username claim to be e.g. 

```python
c.AzureAdOAuthenticator.username_claim = 'oid'
```
