### ISSUE TITLE
feat / Show container image name on the main page

### ISSUE THREAD

**Issue by zeehio** [jupyterhub/dockerspawner#328]
Once a notebook is spawned, it is not easy to know which image it uses.

Since https://github.com/jupyterhub/dockerspawner/pull/316, the `JUPYTER_IMAGE_SPEC` environment variable contains the name of the docker image. It would be great to show it somewhere in the nav menu (e.g. next to the "Control Panel").

*Since not all spawners use docker images, I guess this feature request belongs here and not in https://github.com/jupyterhub/jupyterhub, but I don't know how to implement it*

**Comment by minrk** [comment]
I'm going to close this one in favor of your issue on https://github.com/danielballan/jupyter-expose-image-spec

While I think it's in-scope to pass the image from the spawner, adding it to UI is more appropriately done in an extension than in the Spawner.
