### ISSUE TITLE
swarm cluster stopped deploying single-user containers after hitting resource limit on a small node

### ISSUE THREAD

**Issue by zhiyuli** [jupyterhub/dockerspawner#346]
We have a 3-node swarm cluster where the 2 dedicated worker nodes have better specifications  (more RAM and CPU cores) than the manager node.  Manager node is also used as a worker in our case.

We called Hub rest api to fire up around 80 single-user notebook containers one by one as a load-test. We found SwarmSpawner was able to create all the 80 Services (user_1 to user_80), but Containers of user_61-80 didn't get started.  

Swarm evenly distributed the 60 running containers over the 3 nodes (around 20 for each). It seems it has hit the resource limit on the manager node as 20 * mem_guarantee is roughly equal to the total RAM on that small VM.

But why did not swarm deploy container 61-80 on the other 2 bigger worker nodes? They still have much more unused RAM.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

I doubt this is specific to SwarmSpawner, and rather a general swarm scheduling question. You might check all allocated resources on all nodes to see if perhaps another limit is being exhausted, not just memory. Presumably the failed-to-schedule services should have a state annotation that indicates *why* they can't be assigned to a node (sorry, I'm more familiar with kubernetes scheduling than docker swarm).
