### ISSUE TITLE
image chooser depending on url

### ISSUE THREAD

**Issue by Energy23** [jupyterhub/dockerspawner#347]
Hello community,
the new image whitelist funktions works great, but is there a possibility to choose an image automatic by accessing the jupyterhub server with a certain link.
For example https://jupyter.mydomain.com/image1 spawns docker container from image1

I need a solution like this, becuase I want to provide several images with TmpAuthenticator and depending on the link I provide an image is chosen.
If there is a possibility to catch a request from url would also help.

My Setup is:
Jupyterhub 1.0
Dockerspawner 0.12
TmpAuthenticator
Nginx Proxy

Or maybe there's a way to get the chosen image insinde the jupyterhub-config.py, such as c.DockerSpawner.getChosenImageName() 
This would also fit in my use-case

**Comment by zhiyuli** [comment]
+1  
I am having a similar request on this. In my case we offer multiple images for users to choose from if they come to the main login page. 

Another entry point is through GitPuller to pull and open shared notebooks from GitHub directly. We want a URL that can open the specific notebook (GitPuller already does this) with a specific image (feature requested here).
Thanks

**Comment by minrk** [comment]
`allowed_images` can be  a callable, with the spawner given as its only argument. You can use `spawner.user.name` or `spawner.user.groups`, etc. to decide what images to return.  The [request handler](https://www.tornadoweb.org/en/stable/web.html#request-handlers), *if available* (it may not be, depending on how spawn was requested) is available as `spawner.handler`, which gives you access to everything about the request:

```python
def custom_allow_images(spawner):
    if spawner.handler:
        uri = spawner.handler.request.uri
        if uri ...:
            return ['image1', 'image2']
    return ['image3', 'image4']

c.DockerSpawner.allowed_images = custom_allow_images
```
