### ISSUE TITLE
Redirect loop detected. Notebook has jupyterhub version 1.0.1dev, but the Hub expects 1.0.0.

### ISSUE THREAD

**Issue by chaoyangfan-lgi** [jupyterhub/dockerspawner#351]
Help! 
I deployed Jupyterhub as a container. After the following setting, when I start the single user server I got the error. I check the version.
In the image jupyterhub/jupyterhub 1.0.0
```./jupyterhub --version
1.0.0```
In the image it generates: jupyterhub/singleuser:1.0
 ./jupyterhub --version 
1.0.1dev
I can not access the single use server.

Here is my setting:
# This is the address on which the proxy will bind. Sets protocol, ip, base_url
`c.JupyterHub.bind_url = 'http://$IP'`
# use LDAP as the authenticator
`c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'`
`c.LDAPAuthenticator.server_address = '@URL'`
`c.LDAPAuthenticator.server_port = 636`
`c.LDAPAuthenticator.bind_dn_template = 'uid={username},ou=People,dc=**,dc=**'`
`c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'`

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

When JupyterHub is in a container, it must be connectable from the user pods. This often means setting `c.JupyterHub.hub_connect_ip = 'jupyterhub'` as in [our example](https://github.com/jupyterhub/dockerspawner/blob/c3b5b487cef4989e98136354794f1f89bfca71a2/examples/simple/jupyterhub_config.py#L13), and usually creating a docker network.

In the future, for debugging it’s really important to include logs output, ideally of both the hub and the user container (`jupyter-username`).
