### ISSUE TITLE
Setting environment variables in spawner via API

### ISSUE THREAD

**Issue by vincentschen** [jupyterhub/dockerspawner#352]
Is there a way to set environment variables _within the notebook container_ programmatically when using the jupyterhub API?

According to Jupyterhub docs, calling `POST /users/{name}/server}` with a payload like `{"env": { ... }}` will set `spawner.user_options.env` — is there a quickfix to propagate this to environment variables?

**Comment by synchronizing** [comment]
Wondering the same.

**Comment by minrk** [comment]
Unfortunately, this is not possible with just JupyterHub. A single-user server extension could be developed to accept API requests and update the server's environment, though. This wouldn't typically affect any running processes, but it would affect *new* kernels launched after the API call.

Closing here as this is a request for new server-extension development, not anything in DockerSpawner. Feel free to post about the idea on [the Jupyter forum](http://discourse.jupyter.org)!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/setting-environment-variables-dynamically/9982/1
