### ISSUE TITLE
Limit/disable swap?

### ISSUE THREAD

**Issue by chiel2603** [jupyterhub/dockerspawner#354]
In our docker SwarmSpawner setup we have limit the memory(ram) and CPU usage.
Via jupyterhub_config.py:
c.DockerSpawner.mem_limit = '1G'
c.DockerSpawner.cpu_limit = 0.5

But when a singeluser notebook asks all the memory (like a Fork bomb) it will use swap space.
(even with vm.swappiness = 0 and vm.overcommit_memory = 1)

Docker has an option to set --memory-swap if you enable (in /etc/default/grub):
GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"

Is it possible to use --memory-swap like solution in SwarmSpawner?

https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details

**Comment by minrk** [comment]
You can pass any/all docker arguments to [create_host_config](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.create_host_config) via `c.DockerSpawner.extra_host_config`. I believe what you want is to set `memswap_limit`.

I'd recommend checking the docker-py docs for how to set most configuration, as DockerSpawner mostly passes things through unmodified.
