### ISSUE TITLE
Resources intensive process affecting entire node

### ISSUE THREAD

**Issue by gautambak** [jupyterhub/dockerspawner#357]
Hi There,

Wondering if you can help. We have a few people using notebooks on a shared node using dockerspawner. So far so good but we noticed that if someone runs a process that is very resource-intensive it crashes the node and everyone on the same node loses their work.

A simple example is most recently me. I ran a command that generated sample data that exceeded the memory on the server, it didn't' warn me or crash..it just kept running until no one else's notebooks(including mine) were responsive. 

There is a way to limit usage on dockerspawner to ensure our server can never be taken down?

Thank you!

**Comment by manics** [comment]
Have you tried setting `Spawner.mem_limit`? https://github.com/jupyterhub/dockerspawner/tree/0.11.1#memory-limits

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. It looks like this issue is resolved.
