### ISSUE TITLE
500 server error: Failed to connect to Hub API at '<hostIP:8081>/hub/api'.  Is the Hub accessible at this URL (from host: 610895540bb5)?

### ISSUE THREAD

**Issue by nwong44** [jupyterhub/dockerspawner#358]
Hi, I've been having this error. When I go to the URL, it displays the version of Jupyterhub. 

I have tried using this command "sudo ufw allow in on docker0 to any port 8081"
Also, here are my configs:
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'

c.DockerSpawner.image = 'jupyter/scipy-notebook'
c.DockerSpawner.hub_ip_connect = '<hostIP>'
c.JupyterHub.hub_ip = '<hostIP>'
#c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.port = 8000

I have also configured proxy in the docker http.conf file as well. 

Thanks!

**Comment by lbiemans** [comment]
Can you run the 'jupyter/scipy-notebook' image manually? If so do a docker system prune -af and make sure the image is on the system. You could check the logs via docker service logs -f SERVICENAME or docker container logs by using docker container logs -f containerID

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

In the future, for debugging it’s really important to include logs output, ideally of both the hub and the user container (`jupyter-username`), and whether the hub is itself in a container.
