### ISSUE TITLE
Any interest in PodmanSpawner ?

### ISSUE THREAD

**Issue by sudhaker** [jupyterhub/dockerspawner#360]
Podman has great potential, especially with the daemonless & rootless support.

Do we have any plan to support Podman with this module? Or possibly with a separate dedicated module.

Cheers,
Sudhaker

**Comment by manics** [comment]
There are no plans at the moment. There are a few ways to interface with Podman:
- Command line `podman` executable
- Varlink protocol https://github.com/containers/python-podman/blob/1.6.0/README.md
- New Docker-compatible API https://podman.io/blogs/2020/01/17/podman-new-api.html

The Docker-compatible API is still in development, but if it's similar enough it's probably reasonable to include support in this spawner. If it turns out to be quite different, or you want to use one of the other interfaces, a separate spawner makes more sense.

Though I've just noticed a post on https://github.com/containers/python-podman/issues/16#issuecomment-605439792 from @gatoniel. It looks like this is the repo https://github.com/gatoniel/podmanspawner

**Comment by gatoniel** [comment]
Hi there,

I already saw this post and wanted to answer, when I could present a minimal working example. But I am not yet there. Right now I am facing the problem, that podman containers can not easily send queries to the host, which is needed for the API calls. So I will use the `--net host` option. Another option would be, that the JupyterHub itself is also run in a container and they all share the same Pod. But this is a big restriction...

Sadly, my VPN is down now and I cant connect to the server to test stuff... Hopefully I have a working Spawner tomorrow.

**Comment by gatoniel** [comment]
I got it working, BUT there are some issues to be resolved. Next, I will look deeper into the new API and try to use it, based on your usage of the docker API in dockerspawner.

**Comment by gatoniel** [comment]
Hi, I needed to work out some PAM issues with jupyterhub, since Podman seems to rely on the existence of /usr/run/$UID, which can easily be created with pam_systemd via pam_open_session. Now the podmanspawner works somewhat stable.

**Comment by manics** [comment]
That's great! I've been meaning to give it a go but unfortunately I haven't had time so far.

**Comment by minrk** [comment]
@manics @gatoniel what do you folks think now after some more experience? On a cursory read, it seems like maybe there's not that much overlap, and a separate PodmanSpawner is the right way to go.

**Comment by gatoniel** [comment]
Hi,

my JupyterHub instance with podmanspawner runs somewhat stable. There is an occasional bug that requires a restart of the whole JupyterHub. I also had to make changes to JupyterHub itself to get everything working (the mentioned PAM issues above). If there is a lot of interest into a stable and tested podmanspawner, I will try to create PRs into the current version of JupyterHub and update my current podmanspawner. I also think a separate podmanspawner is the right way to go.

From the top of my head there were two problems to overcome:
1. Get JupyterHub to correctly login a user with the underlying system using PAM. This has the side effect of creation of user temporary folders that are required by podman.
2. The official jupyter docker images all use the user jovyan. With podmans user-id-mapping the jovyan user has no rights on the host system and therefore users cannot interact with it to write persistent data.

**Comment by manics** [comment]
Podman 3.0 was recently released, it's API is now compatible enough with docker to work with docker-compose:
https://podman.io/releases/2021/02/11/podman-release-v3.0.0.html

This might mean we DockerSpawner could work with Podman with no or very minimal changes, I'll add it to my (ever growing) todo list to investigate :smile: 

There's definitely still room for a separate PodmanSpawner though. For Docker compatibility you need to run Podman as a daemon (not sure if it has to be a system/root daemon), but one of the big benefits of Podman is that a daemon isn't required, and that it can be used without root privileges. Podman also has several features that aren't in Docker a dedicated spawner could support.

How about if we aim to support using Podman in daemon mode via the Docker API in this repo _providing the changes are minimal_, and for everything else use PodmanSpawner, and link to it in the docs?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/improving-and-testing-pam-authentication-for-podmanspawner/8327/1

**Comment by manics** [comment]
I was able to get Podman 3 in user (rootless) mode working with DockerSpawner. No changes were required to the sapwner, the main steps are setting up Podman as a usermode service and setting `DOCKER_HOST=/path/to/podman.sock`.
This is how I configured it all: https://gist.github.com/manics/1de8aa610c319d5c24b07ea73f84f891

**Comment by minrk** [comment]
@manics that's awesome! Want to maybe add that as an example to the docs, and call this resolved?

**Comment by mfalt** [comment]
> I was able to get Podman 3 in user (rootless) mode working with DockerSpawner. No changes were required to the spawner, the main steps are setting up Podman as a usermode service and setting `DOCKER_HOST=/path/to/podman.sock`.
> This is how I configured it all: https://gist.github.com/manics/1de8aa610c319d5c24b07ea73f84f891

I can verify that this seems to work well. However, you will be restricted to the docker compatible podman API. This means that you are not able to set "UIDMap" and "GIDMap" for example. It would be much easier to get directory mounts and permissions correctly if it was possible to set them (for example using a podmanspawner library).

As far as I know, with the dockerspawner we are restricted to rely on that the containers are stated with `--user root` and hoping that the container will create the correct user and chown all the correct files.

**Comment by minrk** [comment]
> As far as I know, with dockerspawner, we are restricted to rely on that the containers are stated with 

I don't believe this is the case. I usually do not run with user=root with DockerSpawner. DockerSpawner can start as any user. However, some _images_ may assume user=root, if you want to rely on e.g. the `$NB_UID` functionality in jupyter/docker-stacks which can use root privileges to 'become' a given user at startup. This is not DockerSpawner, though, it's in the images themselves and totally optional.
