### ISSUE TITLE
Stop containers after logout

### ISSUE THREAD

**Issue by z3ky** [jupyterhub/dockerspawner#364]
Hi,
can spawned containers be stoped after users logged out or after a defined idle period?

**Comment by devnull-mr** [comment]
Yes, you can have have user containers stopped on [logout](https://jupyterhub.readthedocs.io/en/stable/api/app.html#jupyterhub.app.JupyterHub.shutdown_on_logout).

I am not aware you can do the same based on idle time.

**Comment by minrk** [comment]
Yes! You can use [jupyterhub-idle-culler](https://github.com/jupyterhub/jupyterhub-idle-culler) to cull idle notebooks.
