### ISSUE TITLE
Run container with option --group-add users

### ISSUE THREAD

**Issue by bgoutorbe** [jupyterhub/dockerspawner#365]
Hello,

I would like that the containers spawned by Jupyter Hub run with the options `--user <uid> --group-add users`, as recommended here:
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html

I know that `--user <uid>` is achieved with `c.DockerSpawner.extra_create_kwargs = { 'user': '<uid>'}`.

But how should I pass `--group-add users`?

Thanks

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!
 
I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org).

You can pass any/all docker arguments to [create_host_config](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.create_host_config) via `c.DockerSpawner.extra_host_config`. For group_add:

```python
c.DockerSpawner.extra_host_config = {"group_add": ["group1", "group2"]}
```
