### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by akhmerov** [jupyterhub/dockerspawner#366]
The last release was 12 months ago, with some bugfixes landing on master in the meantime (in particular #334 affects my deployment). Is there a plan to make a new (possibly bugfix) release?

**Comment by minrk** [comment]
I'm going through and catching up this repo, hoping to make a new release shortly

**Comment by minrk** [comment]
Tasks for releasing dockerspawner 12:

- [ ] merge outstanding pull requests
- [ ] changelog
- [ ] tag release

**Comment by minrk** [comment]
dockerspawner 12.0 is [out](https://jupyterhub-dockerspawner.readthedocs.io/en/stable/changelog.html)!
