### ISSUE TITLE
404 Client Error: "manifest for jupyterhub/singleuser:1.1 not found

### ISSUE THREAD

**Issue by jimmy-zx** [jupyterhub/dockerspawner#370]
### Bug description
The default configuration requires an non-existent docker image.

#### Expected behaviour
The jupyter notebook interface, without a configure file jupyterhub works normally.

#### Actual behaviour
The server is not started, showing

> Spawn failed: 404 Client Error: Not Found ("manifest for jupyterhub/singleuser:1.1 not found: manifest unknown: manifest unknown")

### How to reproduce

I followed the instructions [here](https://github.com/jupyterhub/jupyterhub/blob/master/README.md) and [here](https://github.com/jupyterhub/dockerspawner/blob/master/README.md)

1. Install npm packages ```npm install -g configurable-http-proxy```
1. Install jupyterhub and dockerspawner ```python3 -m pip install jupyterhub notebook dockerspawner```
1. Setup the configuration file
1. Run ```jupyterhub```
1. Login with any user

### Cause
This is the error reported in the console

> docker.errors.NotFound: 404 Client Error: Not Found ("manifest for jupyterhub/singleuser:1.1 not found: manifest unknown: manifest unknown")

Possibly raised from

> [(time) JupyterHub dockerspawner:930] pulling image jupyterhub/singleuser:1.1

I tried to run ```docker pull jupyterhub/singleuser:1.1```, resulted in

> Error response from daemon: manifest for jupyterhub/singleuser:1.1 not found: manifest unknown: manifest unknown

And there are no tag 1.1 in the [dockerhub](https://hub.docker.com/r/jupyterhub/singleuser/tags)

The [source code](https://github.com/jupyterhub/dockerspawner/blob/6f7e04ce9f989e98cf99bb2a6dfa1cff96466135/dockerspawner/dockerspawner.py#L168) shows that the script is trying to pull an docker image with the same version as the dockerhub. However, there is no image for version 1.1

### Personal set up

 - OS:
 Debian 10 buster

- Kernel:
4.19.0-8-amd64

 - Version:
Python 3.7.3
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
node v12.16.2
npm 6.14.4
Docker version 19.03.8, build afacb8b7f0
jupyterhub 1.1.0
dockerspawner 0.11.1

 - Configuration:
jupyterhub_config.py
```
c = get_config()

# spawn with Docker
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
```

**Comment by z3ky** [comment]
Try to use
c.DockerSpawner.image = 'jupyterhub/singleuser:latest'

**Comment by charrismatic** [comment]
I just ran into this same issue. 

I should have tested these steps separately, but I was able to get this working by 

pulling the docker image without the version number 

```
docker pull jupyterhub/singleuser
```

and addding the above line to the `jupter_config.py` file

```
c.DockerSpawner.image = 'jupyterhub/singleuser:latest'
```

**Comment by minrk** [comment]
The jupyterhub image tagging has been fixed
