### ISSUE TITLE
An underscore in username adds unexpected characters (during the escaping)

### ISSUE THREAD

**Issue by merretbuurman** [jupyterhub/dockerspawner#371]
Actually, this is a bug in the dependency **escapism**. I filed a bug there: https://github.com/minrk/escapism/issues/3

But possibly this can also be fixed here.

### Bug description

If the username contains an underscore, the characters `5F` will be added to it. This happens in the `escape` Method (https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L20). So the **container name** of the spawned container has unexpected characters in it, and if I **bind-mount volumes** that contain the username, their names will also have unexpected characters.

In my case, If the username is `foo_bar`. It is expanded to `foo_5Fbar` by the dockerspawner.

#### Expected behaviour

I expect the (escaped) username not to contain the `5F`, so that I can safely use it in my jupyterhub_config.py.

#### Actual behaviour

I log in with username `foo_bar`.

A container is spawned, which is called: `jupyter-foo_5Fbar`.

The container should bind-mount this directory: `/foo/foo_bar/files`.
Instead it mounts: `/foo/foo_5Fbar/files`.
This is a problem of course if the directory `/foo/foo_bar/files` is already existing and should be mounted.

This is caused by using `{username}` in my jupyterhub_config.py:

```
c.DockerSpawner.volumes = {'/foo/{username}/files/': '/workspace' }
```

See this excerpt from `docker inspect <container>`: 

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/foo/foo_5Fbar/files",
                "Destination": "/workspace",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
```

#### Workaround

I used `{raw_username}` instead of `{username}` in `jupyterhub_config.py`. It works in my case, as the usernames are ASCII characters (except for the underscore) and no further escaping is needed.

For the bind-mount:

```
c.DockerSpawner.volumes = {'/foo/{raw_username}/files/': '/workspace' }
```

For the container name, I specify a `name_template`. It works in my case, as the usernames are ASCII characters (except for the underscore) and no further escaping is needed:

```
c.DockerSpawner.name_template = 'jupyter-{raw_username}'
```

### How to reproduce

1. Run a JupyterHub instance with Dockerspawner
2. Add a bind-mount in `jupyterhub_config.py` containing the `{username}`.
3. Login with a username containing an underscore.
4. Check the container name (`docker ps -a`)
5. Check the mounted directory (`docker inspect <containername>`

### Your personal set up

I tried this with JuypterHub 1.1 and 1.2 (and with 1.0.1 I think, but I'm not sure right now). I wrote my own custom authenticator, using python3, in which I call `pre_spawn_start`, but I do not call any dockerspawner methods there.

 - OS: Linux
 
 - Version: JupyterHub 1.1, 1.2
 
 - Configuration:
 

If you cannot reproduce, I am happy to provide more detailed information.

**Comment by minrk** [comment]
as mentioned in https://github.com/minrk/escapism/issues/3, the escape character cannot be a safe character unless a guarantee is made that inputs strings can never include valid escapes. Otherwise collisions such as users `foo-bar` and `foo_2Dbar` resolving to the same volume or pod can occur.
