### ISSUE TITLE
Config option `post_start_cmd` not recognized by `DockerSpawner`.

### ISSUE THREAD

**Issue by sateeshnalla** [jupyterhub/dockerspawner#383]
### Bug description
need to execute some command after singleuserserver got started 

 c.DockerSpawner.post_start_cmd = 'jupyter trust < path  notebook_*.ipynb>'

i am getting this error in jupyterhub **Config option `post_start_cmd` not recognized by `DockerSpawner`.**

#### Expected behaviour

At least it execute the command, if any mistake in the cmd, let it through error

#### Actual behaviour
 am getting this error in jupyterhub **Config option `post_start_cmd` not recognized by `DockerSpawner`.**

### How to reproduce
i am using DockerSpawner to Spawn a single user server in hupyterhub , i have set the in the jupyterhub_conf.py file
 c.DockerSpawner.post_start_cmd = '<cmd>'

after i start the single user server i am seeing the error

 

 - OS:
 centos 

 - Version:
 jupyterhub --version 1.1.0
 - Configuration:
 c.JupyterHub.authenticator_class = 'jupyterhub.auth.PAMAuthenticator'
c.JupyterHub.bind_url = 'http://0.0.0.0:8071'
c.Authenticator.admin_users = {'jovyan'}
c.PAMAuthenticator.create_system_users=True
c.JupyterHub.admin_access = True
c.PAMAuthenticator.open_sessions = False
c.PamAuthenticator.check_account = False
c.Spawner.mem_limit = '2G'
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'

c.DockerSpawner.post_start_cmd= '<cmd>'

**Comment by GeorgianaElena** [comment]
Hey @sateeshnalla :wave: Thanks for opening this issue.

>am getting this error in jupyterhub Config option post_start_cmd not recognized by DockerSpawner.

The `post_start_cmd` is not recogonzied because a version containing this change hasn't been released yet.

Until a new release is made, maybe installing from maser is an option?
```
pip install git+https://github.com/jupyterhub/dockerspawner.git@master
```

**Comment by sateeshnalla** [comment]
Thank you

**Comment by minrk** [comment]
Thanks @GeorgianaElena! Looks like this issue is resolved.
