### ISSUE TITLE
[500 : Internal Server Error] Permission failure checking authorization, I may need a new token

### ISSUE THREAD

**Issue by TuSKan** [jupyterhub/dockerspawner#388]
[500 : Internal Server Error] Permission failure checking authorization, I may need a new token

 - OS:
Centos8
 - Version:
jupyterhub 1.1.0
 - Configuration:
DockerSpawner.SystemSpawner

**Comment by manics** [comment]
I see you've posted on the community forum https://discourse.jupyter.org/t/500-internal-server-error-permission-failure-checking-authorization-i-may-need-a-new-token/5324/2
so I'll close this

**Comment by TuSKan** [comment]
No answers until now. Some one could help there?

**Comment by TuSKan** [comment]
> I see you've posted on the community forum https://discourse.jupyter.org/t/500-internal-server-error-permission-failure-checking-authorization-i-may-need-a-new-token/5324
> so I'll close this

no answer there
