### ISSUE TITLE
Cpu Limit/Quota

### ISSUE THREAD

**Issue by ogrisel** [jupyterhub/dockerspawner#428]
This is a follow-up to #136 which was closed because not solution was found. In the mean time a working solution has been proposed in:

https://github.com/jupyterhub/dockerspawner/issues/136#issuecomment-466579224

Furthermore this was also implemented in the swarmspawner:

https://github.com/jupyterhub/dockerspawner/blob/3cdde642054887dc4c342f374a34c9cbdd843f2e/dockerspawner/swarmspawner.py#L203

**Comment by minrk** [comment]
Swarm and regular containers have weirdly different specs for specifying cpu limits, but #435 should do it
