### ISSUE TITLE
Set env XDG_CACHE_HOME

### ISSUE THREAD

**Issue by l-spiecker** [jupyterhub/dockerspawner#429]
We may have to set the XDG_CACHE_HOME variable too.

env['XDG_CACHE_HOME'] = os.path.join(self.homedir,'.cache/')

https://github.com/jupyterhub/dockerspawner/blob/3cdde642054887dc4c342f374a34c9cbdd843f2e/dockerspawner/systemuserspawner.py#L147

Workaround:
- Overriding get_env()
- Set:
c.DockerSpawner.environment = {
        'XDG_CACHE_HOME': lambda spawner: os.path.join(spawner.homedir, '.cache')
}

This env is set at:
https://github.com/jupyter/docker-stacks/search?q=XDG_CACHE_HOME

**Comment by minrk** [comment]
Is there any action to take on this repo? DockerSpawner shouldn't set this env itself, and setting it via config is the right thing to do. Seems like everything is as it should be.

**Comment by manics** [comment]
I agree, this should be managed outside DockerSpawner as it's specific to the contents of the Docker image.
