### ISSUE TITLE
User define docker image

### ISSUE THREAD

**Issue by jeandet** [jupyterhub/dockerspawner#431]
### Proposed change
Allow users to write image name so they can easily run custom images without changing jupyterhub config.
For example in the drop down menu, there could be "custom" field enabling a text box where the user could fill a docker image name. 

### Who would use this feature?
That could be handy in a small lab were users are "trustable" and know how to build docker images and you don't want too many entries in the image selector.

**Comment by minrk** [comment]
I'm not sure what you mean by "without changing jupyterhub config". It needs to be opt-in via config somehow.

This behavior is [one of our examples](https://github.com/jupyterhub/dockerspawner/tree/12.0.0/examples/image_form). Can you be more specific about what should be different beyond providing an explanation of how to accomplish this that we already have?

**Comment by jeandet** [comment]
@minrk I just missed this example, it mostly does what I want, thank you :).
