### ISSUE TITLE
Why .bashrc is ignore

### ISSUE THREAD

**Issue by maShimizu** [jupyterhub/dockerspawner#439]
I try to use openvino image in jupyterhub with dockerspawner.
This image read some python environment in setup script and 
this script is called like "source setup.sh" in .bashrc.

But, docker container launched by dockerspawner dose NOT set these 
environment.
And also, I've try to set "/bin/bash -c "jupyterhub-singleuser"" or
"/bin/bash -c "source $HOME/.bashrc && jupyterhub-singleuser"" as command.
but, Both dosen't work well.

How to do "source $HOME/.bashrc" ?

I don't know how to edit label. I'm sorry for attaching wrong label.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Please include full details of how you deployed JupyterHub, including your configuration. Thanks!

**Comment by maShimizu** [comment]
@manics 
@support

Thank you for your kindly support.

I found that
"/bin/bash -c "source $HOME/.bashrc && jupyterhub-singleuser"" doesn't work and 
"/bin/bash -c "source setup.sh && jupyterhub-singleuser" work well.

Directly launching setup script is OK. 
I think I need any parameter for docker or docker-py in dockerspawner, then I post my question in this Issues.
Thank you for your kindly reply.
I'll discuss on the http://discourse.jupyter.org/ forum.
