### ISSUE TITLE
Dealing with sqlite on NFS mounts

### ISSUE THREAD

**Issue by cgsanchez** [jupyterhub/dockerspawner#46]
I'm using a setup where the user's home directory is in an NFS mount (heavily inspired by https://github.com/compmodels). Everything works fine up to the point when I want to create a new notebook, then a "filesystem error" occurs, which I've tracked down to something that looks like this:

 https://github.com/ipython/ipython/issues/2426/   

before trying to reinvent the wheel, how are you guys dealing with this?

**Comment by minrk** [comment]
@jhamrick did you hear about any of these issues from your students when you ran compmodels?

@cgsanchez I think this sort of issue can be resolved/improved with the right NFS configuration, but I'm afraid that I don't know exactly *what* NFS configuration. I've used this on NFS plenty of times without issue. Do you have control of your NFS server? What distro/version are you using?

**Comment by cgsanchez** [comment]
At the moment I'm using AWS's EFS which is almost fully NFS4 compliant except for mandatory locking (http://docs.aws.amazon.com/efs/latest/ug/nfs4-unsupported-features.html). I could just set an instance as an NFS server but the "elasticity" of EFS makes it appealing. I was wondering where to tweak the systemuser image to tell the hub which ipython_config.py to use by default, I can see now about 12 of those in the image. Can you think of a hack to the systemuser image that would force ipython to use an in memory sqlite? Would that be to harsh on functionality?

**Comment by jhamrick** [comment]
Hmm, no, I never ran into any problems like this. I did have some issues with using copytree on NFS in Python 3, but nothing to actually do with databases. So it's likely there's some subtle difference between your configuration of NFS and mine, I guess. Perhaps the mandatory locking bit is actually what's causing problems here?

I don't know enough about what gets stored in that database to know about the implications for running it purely in memory, but @minrk probably does?

**Comment by minrk** [comment]
It's your IPython command history, and probably won't be missed by most people who only use the notebook. To use in-memory history, you can set `c.HistoryManager.hist_file = ':memory:'` in ipython_config.py, or even `c.HistoryManager.enabled = False` to just turn it off.

**Comment by willingc** [comment]
I'm doing issue maintenance on this repo. Since this issue is over 6 months old and it does not appear to have a specific next action step, I am closing it.

**Comment by meffect** [comment]
have you tried mounting with `cio` option? im curious if it works, I havent tried it myself
