### ISSUE TITLE
"host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by ZhengHui-Z** [jupyterhub/dockerspawner#462]
### Bug description

Docker container conflicts with port_bindings when host network mode is used (c.DockerSpawner.network_name).

### How to reproduce

```
swarm-hub-1  |     Traceback (most recent call last):
swarm-hub-1  |       File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 732, in spawn
swarm-hub-1  |         url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
swarm-hub-1  |       File "/srv/jupyterhub/mydockerspawner.py", line 1325, in start
swarm-hub-1  |         obj = await self.create_object()
swarm-hub-1  |       File "/srv/jupyterhub/mydockerspawner.py", line 1205, in create_object
swarm-hub-1  |         host_config = self.client.create_host_config(**host_config)
swarm-hub-1  |       File "/usr/local/lib/python3.8/dist-packages/docker/api/container.py", line 596, in create_host_config
swarm-hub-1  |         return HostConfig(*args, **kwargs)
swarm-hub-1  |       File "/usr/local/lib/python3.8/dist-packages/docker/types/containers.py", line 336, in __init__
swarm-hub-1  |         raise host_config_incompatible_error(
swarm-hub-1  |     docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
```

jupyterhub_config.py

set c.DockerSpawner.network_name = "host"

### 
dockerspawner.py

```python
async def create_object(self):
    if not self.use_internal_ip:
        host_config["port_bindings"] = {self.port: (self.host_ip,)}
```

```python
@default("use_internal_ip")
def _default_use_ip(self):
    # setting network_name to something other than bridge or host implies use_internal_ip
    if self.network_name not in {"bridge", "host"}:
        return True

    else:
        return False
```

The port_bindings will be configured automatically when Docker uses "bridge" or "host" mode, which will cause conflicts.

**Comment by obilodeau** [comment]
I was also bitten by this bad API.

If you do: `c.DockerSpawner.use_internal_ip = True` before `c.DockerSpawner.network_name = 'host'` you will always get the `port_bindings` incompatibility error.

Switch them around and the problem is resolved. For a "configuration file" this is quite surprising and should probably be fixed.

**Comment by ZhengHui-Z** [comment]
> ```python
> _default_use_ip
> ```

You should try overloading method `async def get_ip_and_port(self):`
```
async def get_ip_and_port(self):
    # code
    return ip, port
```

**Comment by ZhengHui-Z** [comment]
> I was also bitten by this bad API.
> 
> If you do: `c.DockerSpawner.use_internal_ip = True` before `c.DockerSpawner.network_name = 'host'` you will always get the `port_bindings` incompatibility error.
> 
> Switch them around and the problem is resolved. For a "configuration file" this is quite surprising and should probably be fixed.



You should try overloading method `async def get_ip_and_port(self):`
```
async def get_ip_and_port(self):
    # code
    return ip, port
```
