### ISSUE TITLE
Extra Create Kwargs Overwrite Create Kwargs

### ISSUE THREAD

**Issue by daskol** [jupyterhub/dockerspawner#465]
### Bug description

Consider the following snippet.

```python
class MySpawner(DockerSpawner):
    async def start(self, *args, **kwargs):
        self.extra_create_kwargs['environment'] = {'LUPA': 'PUPA'}}
        return await super().start(*args, **kwargs)
```

The issue is a single-user server failed to start because `self.extra_create_kwargs` overwrites create kwargs on container creation. This is completely what is expected from `extra_*` parameters.

### Expected behaviour

We expect that `dockerspawner` merges a subtree of extra kwargs to the main subtree of kwargs.

### Your personal set up

```shell
pip list | grep dockerspawner
# dockerspawner              12.1.0
```

**Comment by minrk** [comment]
Indeed, the clobbering should be fixed. But if your case is specifically environment variables, the way to do that is to call `self.environment.update({'LUPA': 'PUPA'})`, which will add to the env rather than clobbering anything.
