### ISSUE TITLE
Discussion: SQLAlchemy2 compatibility issue

### ISSUE THREAD

**Issue by Sheila-nk** [jupyterhub/dockerspawner#478]
`JupyterHub` backported the `sqalchemy` compatibility fix to JupyterHub>=3.0 but didn't restrict the `sqlalchemy` version to < 2.0 for JupyterHub<3.0. Tests on GitHub Actions are failing due to this. More info: https://github.com/jupyterhub/jupyterhub/issues/4312

Solutions suggested by @GeorgianaElena include:
- dropping support for older JupyterHub versions (see also @manics comment in https://github.com/jupyterhub/dockerspawner/pull/476#issuecomment-1436708669) or
- pinning sqalchemy in older JupyterHub's versions, or in dockerspawner

Additional input is welcome.

**Comment by consideRatio** [comment]
In #485 I made us install sqlalchemy specifically when testing with jupyterhub 1 and 2, but I think we should drop support for older jupyterhub versions as well to help us maintain things a bit easier long term.

I suggest dropping support for jupyterhub 1 at least, and preferably also more, to protect us from handling issues in due time.

Here are some options:

- jupyterhub>=1.0.0 (current requirement)
- jupyterhub>=2.3.1
- jupyterhub>=3.5.1
- jupyterhub>=4.0.0

I suggest we go for `python>=3.8` and `jupyterhub>=4.0.0` to minimize long term complexity of maintaing this repo, thinking that its not so important that users without modern python or jupyterhub also get a modern version of this spawner.

**Comment by consideRatio** [comment]
@minrk @manics what do you think about dropping support for older jupyterhub versions and or python versions?

I think it would be good to drop support for python 3.7 and jupyterhub 1 to enable pytest-jupyterhub to work against this repo, which requires py38+ and jupyterhub 2+ at least.

**Comment by manics** [comment]
I think it's fine, especially if previous releases of DockerSpawner continue to work with older versions of JupyterHub.

**Comment by minrk** [comment]
I very strongly disagree with dropping support for super recent versions, especially of hard-to-upgrade packages like JupyterHub, as I think it puts the convenience of maintainers too far above users. I think this is a temptation we should work very hard against. For example, we are still _currently_ recommending that users install JupyterHub 1.5, via the-littlest-jupyterhub, as we haven't yet made a release with the 4.0 bump. Upgrading JupyterHub is a big deal, and forcing users to upgrade JupyterHub should be considered a big cost we are passing on to users.

While there are some issues _with the test suite_ with older versions of JupyterHub that aren't getting updates (mainly pinning sqlalchemy, are there any other issues?), none of them actually present compatibility issues with this package that I'm aware of.

I'd support bumping to 3.8 and 2.3.1, but I don't thing we should drop 3.5.1 unless supporting 3.5.1 is causing a significant problem _today_. In general, I do not believe it is appropriate to drop support _before_ a problem is identified. The more out-of-date a release is, the lower the bar for dropping support vs fixing whatever problem it is, but I think proactively dropping support is a pattern to avoid.

**Comment by consideRatio** [comment]
Thank you @minrk and I'm sorry for having you advocate this in a few repos!

Let's go with python>=3.8 and jupyterhub>=2.3.1!

**Comment by minrk** [comment]
No worries! Reasonable people can disagree on the trade-offs. Thanks for all your work updating everything recently!
