### ISSUE TITLE
Allow passing exposed port arguments to docker swarm service creation

### ISSUE THREAD

**Issue by dhalik** [jupyterhub/dockerspawner#498]
Hi! First time posting a feature request, please let me know if I'm missing any details or suggestions!

### Proposed change

Add the ability to include network configuration attached to the SwarmSpawner similar to the mount configuration. E.g. the ability to expose port 6006 for tensorboard development on a random high port using the command line arguments `--publish mode=host,target=6006 `. More details available in [docker docs](https://docs.docker.com/engine/swarm/services/#publish-ports)

### Who would use this feature?
Anyone who needs to run network servers inside the jupyter single user containers

**Comment by minrk** [comment]
We already have `SwarmSpawner.extra_endpoint_spec`, which lets you pass through [endpoints](https://docker-py.readthedocs.io/en/stable/api.html#docker.types.EndpointSpec). Is that not sufficient for this?

**Comment by dhalik** [comment]
Thanks for the quick response @minrk! Yes this is exactly what I was looking for, but I didn't know that "endpoint" meant "port".

Thanks for the help!
