### ISSUE TITLE
Add Support for Singleton Containers/Processes

### ISSUE THREAD

**Issue by ssanderson** [jupyterhub/dockerspawner#51]
In the Quantopian codebase, we've implemented subclasses of `JupyterHub` and `DockerSpawner` that provide support for one-per-hub services.  We use this feature for things like database connection pooling and for containers that manage data volumes, and we've found it pretty useful.

Two interesting questions:
1. Is this only a Docker feature, or could/should JupyterHub support a notion of additional managed processes?  One way of thinking about this would be as a generalization of the NodeJS proxy to allowing additional configured processes.
2. If it's only a Docker feature, is there a sane way to do this that doesn't require support from the Hub.  (Our current implementation adds an `init_singleton_containers` method to the Hub startup that ensures the singletons exist before any new Notebook servers are created.)

**Comment by ssanderson** [comment]
@minrk @richafrank @rgbkrk I'd be curious to hear your guys' thoughts on whether/how something like this might belong in the core project.

**Comment by jhamrick** [comment]
:+1: I think it would be fantastic for JupyterHub to support the notion of managed processes/services. I have several services that I start independently from JupyterHub that really would benefit from having JupyterHub manage them:

* culling inactive containers
* saving statistics on JupyterHub usage
* nbgrader formgrader

**Comment by minrk** [comment]
I think adding the notion of services is definitely something we want, I've even written a version of it a while ago. The only thing that got in my way was the idea that single-user servers can be considered a special case of Services, and I couldn't think of a way to do that cleanly. But adding services in one step without rethinking Spawners should be pretty simple, if you want to make a PR.

**Comment by ssanderson** [comment]
> The only thing that got in my way was the idea that single-user servers can be considered a special case of Services, and I couldn't think of a way to do that cleanly.

The important distinction between notebook processes and services, at least as I'm imagining them, is that the configuration of services would be static during the lifetime of a particular Hub process.  Basically, we'd just add a new `init_services` step to startup and a new `cleanup_services` to cleanup.

Since the number of single-user processes managed by the Hub is dynamic by design, I'm not sure it'd even make sense to make them services.  I **do** think we could make the Proxy work as just another service.  One question w/r/t that: we currently store a bunch of information about the Proxy in the database so that we can reconnect if we take down the Hub without taking down the Proxy.  If we made the Proxy a service, we'd either have to have some generic method for storing Service metadata in the database, or we'd have to remove the ability to reconnect to an existing Proxy.

**Comment by minrk** [comment]
@ssanderson I was mainly thinking of the notion that a 'service' is a process to start, stop, monitor, and one might want to run those services in containers or not, etc. So all the process monitoring logic and abstraction *seems* like it wants to be shared. I don't think I can come up with a good API that would actually share those things, though, so building Services as a separate item that happens to have a lot of overlap in concept but not code makes the most sense to me at the moment.

**Comment by minrk** [comment]
JupyterHub's had services for a while now. I think we've done what's in scope for the project.
