### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' https: data:"

### ISSUE THREAD

**Issue by ravitejapagala** [jupyterhub/dockerspawner#519]
I have configured the JupyterHub Dockerspawner running in container.
I am able to run the JUPYTERHUB container without any issues and able to spawn the jupyter notebook container as well.
Here the problem is having with the **content-security-policy.**
"**EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' https: data:"**"
Here I am attaching the console section in (DevTools) screenshot of jupyter notebook which is spawned up from the JupyterHub.

<img width="930" alt="Screenshot 2024-03-08 160204" src="https://github.com/jupyterhub/dockerspawner/assets/84474944/3a03fd8d-5289-40c0-b3de-ca1504c2e738">

I tried with following configuration in jupyterhub_config.py:
**c.JupyterHub.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "default-src 'self' * 'unsafe-inline' https: data: 'unsafe-eval';"
    }
}**

Even though if I add this configuration I am still facing the same issue.
Can anyone suggest how to configure in Jupyterhub_config.py and jupyter_notebook_config.py to allow CSP headers?

**Comment by manics** [comment]
Duplicate of https://discourse.jupyter.org/t/not-able-to-load-the-jupyter-notebook-ui-page-getting-error-evalerror/24480
