### ISSUE TITLE
Non-unique user id causes problem in systemuserspawner

### ISSUE THREAD

**Issue by richjoyce** [jupyterhub/dockerspawner#61]
It looks like the useradd fails if the UID conflicts with the docker image UID's. I'm not sure if there is a fix for this beyond "don't use conflicting user ids", but maybe the docker image could clean up UID 1000 at least. I don't know docker well enough to know if this is possible or easy...

Here is the `docker logs` output for the issue:
```
Creating user jupyter (1000)
useradd: UID 1000 is not unique
sudo: unknown user: jupyter
sudo: unable to initialize policy plugin
```

**Comment by richjoyce** [comment]
So one way this could be handled is checking if the UID is the same as `jovyan` before the `useradd` and then use `usermod` to change the username of `jovyan`. This remains a problem if someone had jovyan as a username with a different UID.

Another option is at the end of the build delete the jovyan user but I'm not sure if this will cause side effects. Or we could change the UID of jovyan to a system user UID.

**Comment by willingc** [comment]
I closing this issue since I believe it is addressed in the current code and the issue itself hasn't had any recent activity.
