### ISSUE TITLE
jupyter/systemuser permission error

### ISSUE THREAD

**Issue by smokedsalmonbagel** [jupyterhub/dockerspawner#67]
Hi - I am setting up a jupyterhub and dockerspawner on the same machine.  I have it all working, but cannot connect to the launched docker image.  My config looks like this:

```python
c.DockerSpawner.hub_ip_connect = 'xxx'
c.JupyterHub.hub_ip = 'xxx'
c.JupyterHub.port = 443
c.JupyterHub.cookie_secret_file = '/home/jupyter/jupyterhub_cookie_secret'
c.JupyterHub.log_level = 'DEBUG'
c.Spawner.debug = True
c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
c.SystemUserSpawner.host_homedir_format_string = '/volumes/user/{username}'
c.DockerSpawner.hub_ip_connect = 'xxx'
c.JupyterHub.proxy_auth_token = 'xxx'
c.Authenticator.whitelist = {'jupyter'}
c.Authenticator.admin_users = {'jupyter'}
c.JupyterHub.ssl_cert = '/home/jupyter/mycert.pem'
c.JupyterHub.ssl_key = '/home/jupyter/mykey.k
```

The server starts, and I can login (via local authentication), but then I get a 500 error on the web.  
I have DEBUG logging:

```
[D 2016-02-02 19:16:13.921 JupyterHub dockerspawner:309] Getting container 'jupyter-jupyter'
[I 2016-02-02 19:16:13.928 JupyterHub dockerspawner:374] Found existing container 'jupyter-jupyter' (id: 5f6551a)
[I 2016-02-02 19:16:13.928 JupyterHub dockerspawner:379] Starting container 'jupyter-jupyter' (id: 5f6551a)
[D 2016-02-02 19:16:14.124 JupyterHub spawner:261] Polling subprocess every 30s
[D 2016-02-02 19:16:23.927 JupyterHub dockerspawner:309] Getting container 'jupyter-jupyter'
[D 2016-02-02 19:16:23.934 JupyterHub dockerspawner:295] Container 5f6551a status: {'Dead': False,
     'Error': '',
     'ExitCode': 9,
     'FinishedAt': '2016-02-03T00:16:14.190673324Z',
     'OOMKilled': False,
     'Paused': False,
     'Pid': 0,
     'Restarting': False,
     'Running': False,
     'StartedAt': '2016-02-03T00:16:14.111710525Z'}
[W 2016-02-02 19:16:23.935 JupyterHub web:1521] 500 POST /hub/login?next= (67.249.20.25): Spawner failed to start [status=ExitCode=9, Error='', FinishedAt=2016-02-03T00:16:14.190673324Z]
[D 2016-02-02 19:16:23.939 JupyterHub base:415] No template for 500
[E 2016-02-02 19:16:23.989 JupyterHub log:99] {
      "X-Forwarded-Proto": "https",
      "Host": "128.153.6.128",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Connection": "close",
      "X-Forwarded-For": "67.249.20.25",
      "Origin": "https://128.153.6.128",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Accept-Language": "en-US,en;q=0.8",
      "Referer": "https://128.153.6.128/hub/login?next=",
      "Content-Length": "37",
      "Cache-Control": "max-age=0",
      "Accept-Encoding": "gzip, deflate",
      "X-Forwarded-Port": "443",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
    }
[E 2016-02-02 19:16:23.990 JupyterHub log:100] 500 POST /hub/login?next= (@67.249.20.25) 10667.63ms


I looked into the docker log (I assumed the problem was here) and found:
Creating user jupyter (1001)
/opt/conda/lib/python3.4/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
/opt/conda/lib/python3.4/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/home/jupyter' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 237, in <module>
    main()
  File "/usr/local/bin/jupyterhub-singleuser", line 233, in main
    return SingleUserNotebookApp.launch_instance()
  File "/opt/conda/lib/python3.4/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "/opt/conda/lib/python3.4/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/notebook/notebookapp.py", line 1017, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/opt/conda/lib/python3.4/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/opt/conda/lib/python3.4/site-packages/jupyter_core/application.py", line 169, in migrate_config
    migrate()
  File "/opt/conda/lib/python3.4/site-packages/jupyter_core/migrate.py", line 238, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "/opt/conda/lib/python3.4/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jupyter/.jupyter'
Creating user jupyter (1001)
useradd: user 'jupyter' already exists
Creating user jupyter (1001)
useradd: user 'jupyter' already exists
Creating user jupyter (1001)
useradd: user 'jupyter' already exists
```

I don't know if that is helpful - it looks like I had the error once but now it is just appending useradd: user 'jupyter' already exists.

I just need a nudge in the right direction - as I am not sure if the problem is with the container image or my install.

**Comment by jhamrick** [comment]
What is the user id of the Jupyter user in the container, versus the user id of the user who owns the files at `/volumes/user/jupyter`? If those are not the same user, then that would explain the permission denied error -- the user id has to match for mounted files.

**Comment by smokedsalmonbagel** [comment]
Ok - I am new to docker so I wasn't aware of that.  I changed my config to value to 
c.SystemUserSpawner.host_homedir_format_string = '/home/{username}'

After I did this, I restarted the hub and it worked!... then I added a few more users, restarted the hub again and it is failing again.  I almost didn't believe it worked but when I checked the docker logs I saw:

jupyter@msdahub:~$ docker logs jupyter-tycon
Creating user tycon (1002)
/opt/conda/lib/python3.4/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
[I 2016-02-03 22:22:06.153 tycon notebookapp:1079] Serving notebooks from local directory: /home/tycon
[I 2016-02-03 22:22:06.153 tycon notebookapp:1079] 0 active kernels
[I 2016-02-03 22:22:06.153 tycon notebookapp:1079] The Jupyter Notebook is running at: http://0.0.0.0:8888/user/tycon/
[I 2016-02-03 22:22:06.153 tycon notebookapp:1080] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2016-02-03 22:22:06.169 tycon log:47] 302 GET /user/tycon (172.17.42.1) 0.90ms
[I 2016-02-03 22:22:06.211 tycon log:47] 302 GET /user/tycon (67.249.20.25) 0.50ms
[I 2016-02-03 22:22:13.431 tycon log:47] 302 GET /user/tycon/logout (67.249.20.25) 2.57ms


It seems the container only works the first time it is run.  If I restart jupyterhub and the hub tries to use my previous container it fails with
[W 2016-02-03 17:24:04.295 JupyterHub web:1521] 500 POST /hub/login?next= (67.249.20.25): Spawner failed to start [status=ExitCode=9, Error='', FinishedAt=2016-02-03T22:23:54.499029425Z]
shown in the jupyterhub console output

The docker log just shows:
Creating user tycon (1002)
useradd: user 'tycon' already exists

To fix the issue I need to rm the docker container each time so it can be re-instantiated.  Is this normal behavior?

**Comment by jhamrick** [comment]
Ah, hmm, yes, I believe in this case you need to remove and recreate the container. You can do that by setting the `DockerSpawner.remove_containers` config option.

Ideally you shouldn't *need* to do that, though. The culprit is probably this line failing to check whether the user exists or not: https://github.com/jupyter/dockerspawner/blob/master/systemuser/systemuser.sh#L4

I *think* if that script were changed to check first if the user exists, and only create it if it doesn't, then it should work correctly.

**Comment by smokedsalmonbagel** [comment]
Ok - I tried:
c.DockerSpawner.remove_containers = True
but it didn't seem to make any difference. - not sure if this works as expected.

After much mashing around I was able to change systemuser.sh to:
`
#!/bin/sh
set -e

ret=false
getent passwd $USER >/dev/null 2>&1 && ret=true
if $ret; then
    echo "User exists - skipping useradd."
else
    echo "Creating user $USER ($USER_ID)"
    useradd -u $USER_ID -s $SHELL $USER
fi
sudo -E PATH="${CONDA_DIR}/bin:$PATH" -u $USER jupyterhub-singleuser \
  --port=8888 \
  --ip=0.0.0.0 \
  --user=$JPY_USER \
  --cookie-name=$JPY_COOKIE_NAME \
  --base-url=$JPY_BASE_URL \
  --hub-prefix=$JPY_HUB_PREFIX \
  --hub-api-url=$JPY_HUB_API_URL \
  $@
`

And its working! 
-One thing that is strange is "echo "User exists - skipping useradd."" is not displayed in the docker log even though it_ seems_ to solve the problem.  

 I am experimenting with this jupyterhub and dockerspawner for teaching data science in  Python this fall, so it is nice to get things going.... 

I guess I have a few questions - 
-I had to modify the file in  /var/lib/docker/aufs/mnt/{long_hash}/srv/singleuser/systemuser.sh, as cloning git, making changes then doing python3 setup.py install did not seem to replace the systemuser.sh - Am I doing this wrong?
-Is this normal behavior for the docker container to expect a new user each time?
 

I'm willing to do some tests with my setup, now that I know my way around a bit better. Thanks for the help!

**Comment by willingc** [comment]
I'm closing this issue since the original issue appears to be resolved. Thanks to everyone.
