### ISSUE TITLE
Config option `open_browser` not recognized by `SingleUserNotebookApp`

### ISSUE THREAD

**Issue by robnagler** [jupyterhub/dockerspawner#88]
The `jupyter_notebook_config.py` that comes with jupyter/singleuser has

```python
c.NotebookApp.open_browser = False
```

However, that doesn't work, because SingleUserNotebookApp does not define open_browser as a trailet.

This causes a warning when the container starts up:

```text
[W 2016-04-21 17:06:23.553 robnagler configurable:159] Config option `open_browser` not recognized by `SingleUserNotebookApp`, do you mean : `browser`
```

**Comment by minrk** [comment]
Indeed, it is redundant now. It can be removed here.

**Comment by willingc** [comment]
@minrk Is there any action still needed to remove open_browser? Or can this be closed?

**Comment by robnagler** [comment]
NC.

**Comment by willingc** [comment]
Thanks @robnagler :-)
