### ISSUE TITLE
{username} in container mount point

### ISSUE THREAD

**Issue by eschlon** [jupyterhub/dockerspawner#90]
Assuming my username is *eschlon*, my goal was to mount */home/eschlon* on the host to */home/eschlon* inside the container. It seemed relatively straightforward, this seems to mostly work fine:

```
c.DockerSpawner.volumes = {'/home/{username}': '/home/{username}'}
```

However, I noticed that in addition to */home/eschlon* I ended up with an additional literal ***/home/{username}***. It seems that while `user.name` is interpolated into both the local and container paths in `volume_binds` the same is not true when local volumes are created in `volume_mount_points`.

I've overridden that method in my custom Spawner like so:
```
    @property
    def volume_mount_points(self):
        """
        Override of the DockerSpawner method.

        The parent method fails to handle cases where internal docker mount points have {username} in them. Thus
        something like {'/home/{username}': '/home/{username}'} will end up creating a literal "{username}".
        """
        return [value.format(username=self.user.name) for value in list(self.volumes.values()) +
                                                                   list(self.read_only_volumes.values())]
```

Things work as expected, though it does seem like it might properly belong here. I can submit a pull request if you think it'd be useful (or an owner can just make the change, as it's pretty small).

**Comment by minrk** [comment]
@eschlon Sounds like the right fix, please do make a PR. Thanks!
