### ISSUE TITLE
jupyterhub server error 500 Spawner failed to start [status=ExitCode=1

### ISSUE THREAD

**Issue by gupepe** [jupyterhub/dockerspawner#92]
When running jupyterhub with swarm I got this error

I 2016-05-11 05:39:37.015 JupyterHub dockerspawner:402] Found existing container 'jupyter-jhuser1' (id: c564bba)
[I 2016-05-11 05:39:37.015 JupyterHub dockerspawner:407] Starting container 'jupyter-jhuser1' (id: c564bba)
[W 2016-05-11 05:39:47.028 JupyterHub web:1521] 500 POST /hub/login?next= (93.47.117.171): Spawner failed to start [status=ExitCode=1, Error='', FinishedAt=2016-05-11T05:39:37.695787745Z]
[E 2016-05-11 05:39:47.041 JupyterHub log:99] {
      "X-Forwarded-Port": "80",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Host": "jupyterhub.ddns.net",
      "X-Forwarded-Proto": "http",
      "Content-Type": "application/x-www-form-urlencoded",
      "Connection": "close",
      "Accept-Language": "en-us",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17",
      "Referer": "http://jupyterhub.ddns.net/hub/login",
      "Accept-Encoding": "gzip, deflate",
      "Content-Length": "33",
      "Origin": "http://jupyterhub.ddns.net",
      "X-Forwarded-For": "93.47.117.171"
    }
[E 2016-05-11 05:39:47.042 JupyterHub log:100] 500 POST /hub/login?next= (@93.47.117.171) 10144.62ms
[W 2016-05-11 05:40:17.387 JupyterHub user:264] jhuser1's server never showed up at http://172.31.15.174:32771/user/jhuser1 after 30 seconds. Giving up
[E 2016-05-11 05:40:17.402 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f8c81097588> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 280, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 256, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://172.31.15.174:32771/user/jhuser1 didn't respond in 30 seconds

**Comment by minrk** [comment]
Can you show `docker logs jupyter-jhuser1`?

**Comment by matteoipri** [comment]
I have a similar issue. I'm deploying on virtual machines running ubuntu and using Docker Swarm. On the main machine (the hub) I'm running jupyterhub/jupyterhub in a docker container. On the same docker host I'm running a consul and a swarm manage containers. On the secondary machine, one of the compute nodes of the swarm, I'm running the swarm join. I configured the jupyterhub with system users. I can successfully log in and reach the admin page, for example. When I want to reach my notebook server I get a too-many-redirects-error from my browser. Here are some info on my setup.
The mijupyterhub container (and image) is built from jupyterhub/jupyterhub with the addition of dockerspawner and its dependences. In the jupyterhub_config.py I added the system users I created one the virtual machine (the hub) and the option to choose the systemuserspawner.

On the hub node

    $ sudo docker -H :4000 ps -a
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
    f0231444dc5e        swarm               "/swarm join --advert"   3 hours ago         Up 3 hours          2375/tcp            ip-172-31-15-174/node1
    
    $ sudo docker ps -a
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                            NAMES
    ab48b381368d        mijupyterhub        "jupyterhub"             6 minutes ago       Up 6 minutes        0.0.0.0:8001->8001/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:80->8000/tcp             mijupyterhub
    bac59d2d07ce        swarm               "/swarm manage -H :40"   12 hours ago        Up 3 hours          2375/tcp, 0.0.0.0:4000->4000/tcp                                                 manager
    3c3950b2f878        progrium/consul     "/bin/start -server -"   12 hours ago        Up 3 hours          53/tcp, 53/udp, 8300-8302/tcp, 8400/tcp, 8301-8302/udp, 0.0.0.0:8500->8500/tcp   consul

```
$ sudo docker logs mijupyterhub
[I 2016-05-11 16:40:43.590 JupyterHub app:643] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[W 2016-05-11 16:40:43.680 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2016-05-11 16:40:43.732 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-05-11 16:40:43.736 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-05-11 16:40:43.736 JupyterHub app:968] Starting proxy @ http://*:8000/
16:40:43.835 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
16:40:43.837 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2016-05-11 16:40:43.941 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:8000/
[I 2016-05-11 16:41:00.408 JupyterHub log:100] 302 GET / (@82.59.202.151) 1.93ms
[I 2016-05-11 16:41:00.608 JupyterHub log:100] 302 GET /hub (@82.59.202.151) 0.50ms
[W 2016-05-11 16:41:00.808 JupyterHub base:161] Invalid or expired cookie token
[W 2016-05-11 16:41:00.812 JupyterHub base:161] Invalid or expired cookie token
[I 2016-05-11 16:41:00.812 JupyterHub log:100] 302 GET /hub/ (@82.59.202.151) 1.91ms
[I 2016-05-11 16:41:01.040 JupyterHub log:100] 200 GET /hub/login (@82.59.202.151) 30.20ms
[I 2016-05-11 16:41:03.865 JupyterHub dockerspawner:335] Container 'jupyter-jhuser0' is gone
[W 2016-05-11 16:41:03.865 JupyterHub dockerspawner:306] container not found
Linux ab48b381368d 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
[I 2016-05-11 16:41:03.964 JupyterHub dockerspawner:335] Container 'jupyter-jhuser0' is gone
[I 2016-05-11 16:41:04.001 JupyterHub dockerspawner:397] Created container 'jupyter-jhuser0' (id: 42faaab) from image jupyterhub/systemuser
[I 2016-05-11 16:41:04.001 JupyterHub dockerspawner:407] Starting container 'jupyter-jhuser0' (id: 42faaab)
[W 2016-05-11 16:41:13.970 JupyterHub base:327] User jhuser0 server is slow to become responsive
[I 2016-05-11 16:41:13.977 JupyterHub log:100] 302 POST /hub/login?next= (@82.59.202.151) 10129.60ms
[I 2016-05-11 16:41:13.977 JupyterHub login:86] User logged in: jhuser0
[I 2016-05-11 16:41:14.182 JupyterHub log:100] 302 GET /hub/ (jhuser0@82.59.202.151) 5.84ms
[I 2016-05-11 16:41:14.380 JupyterHub log:100] 302 GET /user/jhuser0 (@82.59.202.151) 1.93ms
[I 2016-05-11 16:41:14.590 JupyterHub log:100] 302 GET /hub/user/jhuser0 (jhuser0@82.59.202.151) 11.63ms
[I 2016-05-11 16:41:14.788 JupyterHub log:100] 302 GET /user/jhuser0 (@82.59.202.151) 1.21ms
[I 2016-05-11 16:41:14.997 JupyterHub log:100] 302 GET /hub/user/jhuser0 (jhuser0@82.59.202.151) 10.75ms
[I 2016-05-11 16:41:15.195 JupyterHub log:100] 302 GET /user/jhuser0 (@82.59.202.151) 1.34ms
[I 2016-05-11 16:41:15.404 JupyterHub log:100] 302 GET /hub/user/jhuser0 (jhuser0@82.59.202.151) 11.08ms
[I 2016-05-11 16:41:15.602 JupyterHub log:100] 302 GET /user/jhuser0 (@82.59.202.151) 1.18ms
[I 2016-05-11 16:41:15.810 JupyterHub log:100] 302 GET /hub/user/jhuser0 (jhuser0@82.59.202.151) 10.77ms
[I 2016-05-11 16:41:16.009 JupyterHub log:100] 302 GET /user/jhuser0 (@82.59.202.151) 1.48ms
[I 2016-05-11 16:41:16.220 JupyterHub log:100] 302 GET /hub/user/jhuser0 (jhuser0@82.59.202.151) 12.60ms
[I 2016-05-11 16:41:16.419 JupyterHub log:100] 302 GET /user/jhuser0 (@82.59.202.151) 1.25ms
[I 2016-05-11 16:41:16.635 JupyterHub log:100] 302 GET /hub/user/jhuser0 (jhuser0@82.59.202.151) 12.80ms
[I 2016-05-11 16:41:16.833 JupyterHub log:100] 302 GET /user/jhuser0 (@82.59.202.151) 1.30ms
[I 2016-05-11 16:41:17.042 JupyterHub log:100] 302 GET /hub/user/jhuser0 (jhuser0@82.59.202.151) 10.92ms
[I 2016-05-11 16:41:17.240 JupyterHub log:100] 302 GET /user/jhuser0 (@82.59.202.151) 1.25ms
[W 2016-05-11 16:41:34.245 JupyterHub user:264] jhuser0's server never showed up at http://127.0.0.1:32774/user/jhuser0 after 30 seconds. Giving up
[I 2016-05-11 16:41:34.251 JupyterHub dockerspawner:460] Stopping container jupyter-jhuser0 (id: 42faaab)
[I 2016-05-11 16:41:34.329 JupyterHub dockerspawner:466] Removing container jupyter-jhuser0 (id: 42faaab)
[E 2016-05-11 16:41:34.349 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f3344874f28> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 280, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 256, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:32774/user/jhuser0 didn't respond in 30 seconds
```

On the compute node:

    $ sudo docker ps -a
    CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                       NAMES
    42faaab16fb3        jupyterhub/systemuser   "tini -- sh /srv/sing"   14 seconds ago      Up 13 seconds       127.0.0.1:32774->8888/tcp   jupyter-jhuser0
    f0231444dc5e        swarm                   "/swarm join --advert"   2 hours ago         Up 2 hours          2375/tcp                    node1

```
$ sudo docker logs jupyter-jhuser0
Creating user jhuser0 (1000)
/opt/conda/lib/python3.5/site-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[I 2016-05-11 16:38:25.332 jhuser0 notebookapp:1116] Serving notebooks from local directory: /home/jhuser0
[I 2016-05-11 16:38:25.332 jhuser0 notebookapp:1116] 0 active kernels 
[I 2016-05-11 16:38:25.332 jhuser0 notebookapp:1116] The Jupyter Notebook is running at: http://0.0.0.0:8888/user/jhuser0/
[I 2016-05-11 16:38:25.332 jhuser0 notebookapp:1117] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

I think the problem is here: `TimeoutError: Server at http://127.0.0.1:32774/user/jhuser0` because of the 127.0.0.1...
What config am I missing?
Where can I find the documentation of all the configuration options?

**Comment by minrk** [comment]
@jhamrick or @jtyberg any tips on the likely configuration options needed for SwarmSpawners and Hub to talk to each other?

**Comment by jhamrick** [comment]
In SwarmSpawner I had to manually get the IP address of the node and set it on the container (see https://github.com/compmodels/jupyterhub/blob/master/swarmspawner.py#L60) but my understanding was that that's no longer necessary based on @rgbkrk 's comment here: https://github.com/jupyterhub/dockerspawner/pull/54#issuecomment-184728721 I haven't redone my configuration that way yet, though, so I'm not really sure what the problem might be.

@gupepe and @matteoipri would you mind sharing your `jupyterhub_config.py` files?

**Comment by jtyberg** [comment]
I use plain DockerSpawner for my JHub + Swarm deployment.  

As for networking, I try to get out of the way and let Docker handle it for me.  I use an overlay network.  

Here are the interesting bits in my setup:

```
# Activate Swarm manager node (from laptop)
eval "$(docker-machine env --swarm jupyterhub-manager0)"

# Create an overlay network
docker network create --driver overlay --subnet=172.31.0.0/24 jupyterhub-network
```

When I bring up JupyterHub (here using a Docker Compose config), I make sure JHub belongs to the overlay network, and I pass the network name to JHub as an environment variable:

```
services:
  hub:
    networks:
      - default
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      ...

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
```

I then configure JHub to pass the network name along to DockerSpawner, so that DockerSpawner can spawn all containers on the same network:

```
# Connect containers to this Docker network
network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = network_name
# Pass the network name as argument to spawned containers
c.DockerSpawner.extra_host_config = { 'network_mode': network_name }
c.DockerSpawner.extra_start_kwargs = { 'network_mode': network_name }
# User containers will access hub by container name on the Docker network
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8080
```

FWIW, I'm using [consul](https://www.consul.io) as my key store for the overlay network.  When using an overlay, the Docker daemons on your Swarm nodes must have these options:

```
--cluster-store=consul://<consul_ip>:8500
--cluster-advertise=<node_ip>:2376 
```

With this setup, Docker resolves the spawned container IP addresses from container names and provides the IPs to JHub.  Here's an excerpt from my JHub log after I first login:

```
[I 2016-05-13 14:22:54.029 JupyterHub dockerspawner:397] Created container 'jupyter-jtyberg' (id: da5c6eb) from image jupyter/scipy-notebook:2d878db5cbff
[I 2016-05-13 14:22:54.029 JupyterHub dockerspawner:407] Starting container 'jupyter-jtyberg' (id: da5c6eb)
[I 2016-05-13 14:22:56.426 JupyterHub base:306] User jtyberg server took 2.653 seconds to start
[I 2016-05-13 14:22:56.426 JupyterHub orm:159] Adding user jtyberg to proxy /user/jtyberg => http://172.31.0.3:8888
```

I hope this helps.

**Comment by gupepe** [comment]
Thanks very much ! I was missing extra_host_config. Unfortunately there is route error from hub can't connect to node http proxy even though they are in the same network know.

**Comment by gupepe** [comment]
Final recap of the issue : 
1) We created an overlay network as suggested by @jtyberg  

2) We installed the discovery service (i.e. consul) on a different box (different docker from what is hosting juyterhub + swarm)
and we set --cluster-advertise --cluster-store params for the docker according to (i.e on the discovery service and all the clients docker daemon)

3) We created rules on AWS for the port as suggested by @jtyberg 

4) Docker daemon must be initialised with **--ip-forward=true** (see [https://docs.docker.com/v1.8/articles/networking](url)
otherwise containers on different node won't communicate)

5) jupyterhub was configured to use internal ip(and names)  as suggested

`# Connect containers to this Docker network
network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = network_name
# Pass the network name as argument to spawned containers
c.DockerSpawner.extra_host_config = { 'network_mode': network_name }
c.DockerSpawner.extra_start_kwargs = { 'network_mode': network_name }
# User containers will access hub by container name on the Docker network
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8080`


(i.e. we were missing extra_host.., extrastart..)

And finally it worked spawning user containers on different nodes!

Thanks very much for the help and especially to @minrk and @jtyberg ! Hopefully this experience may help other guys to buildup a multi node distributed jupyterhub!

**Comment by mangelov95** [comment]
Slightly off-topic perhaps, but @jtyberg how did you decide on the subnet for the overlay network here?

**Comment by jtyberg** [comment]
@mangelov95 I just used a random subnet in a [private address](https://en.wikipedia.org/wiki/Private_network) space.
